### ISSUE TITLE
Magisk Manager downloading v-null

### ISSUE THREAD

**Issue by ChooTingFeng** [topjohnwu/Magisk#1037]
Steps to reproduce:
1. Open the manager
2. Tap on install before magisk manages to check the latest version
3. It will ask you if you want to install vnull (-1)
4. Tapping on install will give an error. (Failed to download)

Just a minor bug with the manager.

See attached picture
https://i.imgur.com/UBSfboI.png

**Comment by NaderKabir** [comment]
Hi 

Error for OnePlus 6 Android 9 ver 18.1

Very weak for OnePlus 6

**Comment by martyfender** [comment]
Wow, I noticed that in the last week or two, but I didn't realize it was because it had not updated the list for updates available, yet. It only happened to me once, on one of my 5, same devices, so I dismissed the error and tried again. I didn't realize what had caused it.

Nextbook Ares 8A, x86, Android 6.0.1, 5 devices.
