### ISSUE TITLE
Unsupported Nexus 6 running MultiROM and Dark Energy Level

### ISSUE THREAD

**Issue by andrewjt19** [topjohnwu/Magisk#114]
I'm using 7.1.1 lite on my Nexus 6 and can't get latest installer to work. I don't know how to retrieve my boot image though. Please advise. Thanks

**Comment by Didgeridoohan** [comment]
Doesn't that ROM come with SuperSU built-in? The Magisk installer often have a problem with SuperSU pre-rooted ROMs where it can't restore the stock ramdisk.

You'll find your boot image in the ROM zip and you should also upload a recovery log from the failed installation. You might see something in there about finding SuperSU patched boot image and not finding a stock backup, but this is pure guesswork on my part. If that's the case though, since you're using a pure stock based ROM you could try the following:

- Download the factory image from Google and extract the boot image.
- Flash that boot image.
- If you want to use SuperSU. Flash that. If not you should first remove SuperSU. Use osm0si's unSU script.
- Flash Magisk zip.
- Boot up and install Magisk Manager from Play store.

Or, you could choose a ROM that doesn't come pre-rooted.

If you need detailed instructions for anything of the above, google it.

**Comment by topjohnwu** [comment]
If the above is the case, then closed
