### ISSUE TITLE
some memory inaccessible under root

### ISSUE THREAD

**Issue by babarosaM** [topjohnwu/Magisk#1222]
after upgrade mate 20 to emui 9.0.1, the newest rom of chinese variant, the phone could not see about 500MB memory.

before root, android could see 5668 usable and 476 in reserve measured in MB.
after root, android could see 5416 usable and 216 in reserve.
here is canary debug log.
[magisk.log](https://github.com/topjohnwu/Magisk/files/2979414/magisk.log)

official_ramdisk 
https://drive.google.com/open?id=1l81hueWWVbwxFiteVtJESdjzBjsFOGzt

**Comment by babarosaM** [comment]
I find another problem after root.
I cannot open system sms app to check or send sms.
it crashes and system produces this log:
 E AndroidRuntime: Caused by: android.database.sqlite.SQLiteException: unable to open database file (Sqlite code 14 SQLITE_CANTOPEN), (OS error - 13:Permission denied)
which means system sms app has no permission to open sms database.

after reboot to normal system without root, everything is fine.

**Comment by babarosaM** [comment]
my magisk version is canary(945f88)

**Comment by topjohnwu** [comment]
The reduction in RAM might be caused by the fact that many files are copied from system partition to rootfs, which is a ram based filesystem.
Also, regarding the SQLite crash, simply reporting the error is not enough, you have to prove that it has something to do with Magisk itself (e.g. SELinux audit errors). If you don't know what I'm talking about, please at least provide a more complete log recording the whole crashing event

**Comment by babarosaM** [comment]
I finally find the solution to sms app permission error. 

after first flash magisk patch img, clear sms data.

otherwise sms app has no permission to access sms data.

**Comment by babarosaM** [comment]
I notice newest canary magisk also does the same thing on samsung platform by format data partition.
