### ISSUE TITLE
[pixle2][android Q] install magisk in twrp failed

### ISSUE THREAD

**Issue by xlc1540697096** [topjohnwu/Magisk#1232]
twrp version : 3.2.3.1 [twrp](https://dl.twrp.me/walleye/)  

magisk vesion :  v18.1 

`https://dl.twrp.me/walleye/`

![](https://hololenspic.oss-cn-shenzhen.aliyuncs.com/fail.png)

**Comment by Didgeridoohan** [comment]
You claim using Magisk v18.1, your screenshot show v18.0, and neither is compatible with Android Q.

You can close this issue (so that @topjohnwu doesn't have to) and check out the [Canary builds](https://forum.xda-developers.com/apps/magisk/dev-magisk-canary-channel-bleeding-edge-t3839337) (there's Q support for Pixel and Pixel 2), or wait for the next stable/beta release.
