### ISSUE TITLE
Backup functionality

### ISSUE THREAD

**Issue by Artim96** [topjohnwu/Magisk#1282]
Now with Magisk saving modules in a folder in /data instead of an image in /cache it might be neat to have some kind of backup functionality for people tending to forget to save everything where it won't be deleted in the typical ROM installation procedure. Like a (flashable) zip file in the not wiped internal storage or external (if existent). Of course you make backups in TWRP but it was much faster to just get back an image from a small partition like /cache in comparison to restore a probably very big partition like /data.

**Comment by VR-25** [comment]
My Magisk module, Migrator lets you achieve that. Soon it'll be able to backup/restore individual sets of data.

**Comment by Artim96** [comment]
that's something that could very well be implemented in Magisk Manager.

**Comment by RikkaW** [comment]
Some module contains Android version related or ABI related binary, so the backup feature is not "copy all files". I don't think a reliable backup feature could be possible without changing the current module format.
And personally, I don't think the backup feature is that meaningful since users can keep module zips themselves.

**Comment by topjohnwu** [comment]
@RikkaW has a very good point. Case closed 😀
