### ISSUE TITLE
Magisk 19.0 not working on Android Q, Pixel 2

### ISSUE THREAD

**Issue by windchime11** [topjohnwu/Magisk#1284]
steps to reproduce:

1. download Android Q and ./flash-all.sh

2. adb push ~/Downloads/Magisk-v19.0.zip /sdcard

3. fastboot flash boot ~/Downloads/twrp-3.2.3-1-walleye.img

4. restart. within TWRP choose "install" and then Magisk-v19.0.zip

5. then device is like this for 1 hr so far and no sign of any change

![IMG_3334](https://user-images.githubusercontent.com/1188350/55362782-06b14d80-54a9-11e9-9d30-cab85828c6f6.JPG)

**Comment by 1dopewrx** [comment]
I know this is late but the reason you boot looped was because you sent the fastboot flash command to temp boot TWRP instead of the correct command: fastboot boot "TWRP.img location". Hopefully you have caught your mistake by now and are not continuing to flash TWRP instead of temporarily booting it and using the installer.
