### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by diareuse** [topjohnwu/Magisk#1327]
Hey @topjohnwu!

I'm working on a redesign (and complete rewrite for that matter) of the original Manager. The reason is I appreciate your work highly and I want for the community to have amazing looking app and for you better code that is maintainable, readable and extendable.

As I'm maybe few week in this rewrite and I have the core maybe 70% done, it occurred to me that it was in it's entirety written in Java and I carelessly jumped straight to the Kotlin. I want to hear your input too. 

Jump to my [fork](https://github.com/diareuse/Magisk) if you want to see more, otherwise ask anything. I really want this to be *the* manager, not some stupid copy. So what are you thoughts?

**Comment by topjohnwu** [comment]
Hello, I appreciate your work! I checked the code and at a first glance it is looking very good!

Unfortunately, I will not accept a complete rewrite (like what you are currently doing), because I personally would not accept code that I cannot maintain/understand myself. Such huge changes means it would cost me weeks to understand the whole code base, which I would really want to avoid. 

However, I am completely open for contributions. In fact, I'm looking for someone who can take over maintaining the application part because I really do not enjoy it LOL (I find the native part more *fun*), and you seem to be more than qualified for that :). But still, I would prefer refactoring a small portion at a time (ideally via PRs) so I can slowly absorb all the changes and not interrupt the whole development., since the application is deeply tied to the native part.

I would really love to have further conversation with you. I would prefer to add you to the Magisk internal slack group, if you are willing to join (which I hope so), give me an e-mail and I'll invite you to the group.

**Comment by diareuse** [comment]
Sure :) email is `info@depasquale.wiki`. Let's continue the discussion there :)

**Comment by topjohnwu** [comment]
Invitation sent
