### ISSUE TITLE
Suggestion: Custom font for Magisk Manager

### ISSUE THREAD

**Issue by AndreaCioccarelli** [topjohnwu/Magisk#1363]
Wouldn't it be nice to have a nice and device-independent font on Magisk, i.e. [Manrope](https://github.com/sharanda/manrope), that performs very well on mobile devices?

We could use [Calligraphy](https://github.com/chrisjenx/Calligraphy) to apply it over the app. If you like the idea I can make a pull request to add it.

<a href="https://ibb.co/GtTwBwL"><img src="https://i.ibb.co/8dc3T3p/Screen-Shot-2019-04-26-at-00-00-03.png" alt="Screen-Shot-2019-04-26-at-00-00-03" border="0"></a>

**Comment by nakedpwr** [comment]
I think it's a fantastic idea.

**Comment by topjohnwu** [comment]
The decision is on @diareuse, but me personally won't spend effort on making the app more fancy than necessary.

**Comment by diareuse** [comment]
@AndreaCioccarelli I'm certainly considering a custom font as long as it doesn't mess up the design (too wide, tall, narrow or small, has no unnecessary spacing etc.). I'm currently set on Fira Code for console stuff but have no preference for the UI yet. It doesn't seem too relevant at this point.

Definitely *nice to have* though.

Nevertheless using Calligraphy is deprecated since we can use font families from within the Android framework.
