### ISSUE TITLE
magiskpolicy --live in parallel service scripts

### ISSUE THREAD

**Issue by kitsunyan** [topjohnwu/Magisk#1394]
Service script is the best place to alter runtime SELinux policy since this operation takes a significant amount of time and post-fs-data scripts are limited to 10 seconds. This pattern is also used in [Unity](https://github.com/Zackptg5/Unity/blob/4ae5386bbe3cfea6995c10e14ca3e5f8cf852385/common/unityfiles/util_functions.sh#L545).

Starting from Magisk 19.0 all service scripts are [executed in parallel](https://github.com/topjohnwu/Magisk/commit/8b84039f1fd10be5c2383048db5bfc422ca8a05a), which means that multiple scripts can try to alter the policy at the same time causing `EBUSY` errors:
```
fopen: /sys/fs/selinux/policy failed with 16: Device or resource busy
```

The only way to fix it right now is making a loop and parsing the command stderr output which is extremely dirty and bulky solution. It also breaks all existing modules which alter SELinux policy in service script.

**Comment by topjohnwu** [comment]
Handling error should be part of the job of the developer. Even if Magisk execute scripts in sequence, you still can't assume scripts won't launch background processes to patch sepolicy. So I don't think this is a valid reason to *NOT* run scripts in parallel.

Live patching sepolicy is a very bad idea to begin with. Live patching sepolicy on boot can fail system services under some circumstances, and I learnt it the hard way because back in the day Magisk relies on live sepolicy patches and it bootloops devices. And also, live patching sepolicy is simply impossible on some devices like Huawei (the kernel does *NOT* accept a second policy load)

**Comment by kitsunyan** [comment]
> Handling error should be part of the job of the developer. Even if Magisk execute scripts in sequence, you still can't assume scripts won't launch background processes to patch sepolicy. So I don't think this is a valid reason to NOT run scripts in parallel.

I didn't say scripts shouldn't run in parallel. But I think handling these errors in magiskpolicy would be a better solution. Right now I even can't rely on exit code since it's always `1` for any kinds of errors so I need to check the output.

> Live patching sepolicy is a very bad idea to begin with. Live patching sepolicy on boot can fail system services under some circumstances, and I learnt it the hard way because back in the day Magisk relies on live sepolicy patches and it bootloops devices. And also, live patching sepolicy is simply impossible on some devices like Huawei (the kernel does NOT accept a second policy load)

So, why `magiskpolicy --live` exists if it can break something and doesn't work on some devices? Which alternatives should be used instead?
