### ISSUE TITLE
MagiskSU times out root requests

### ISSUE THREAD

**Issue by jcgruenhage** [topjohnwu/Magisk#141]
MagiskSU doesn't prompt the user whether they wan't to grant or deny SuperUser in some cases (see this issue: jcgruenhage/PlayMusicExporter#22).

Apparently, re-flashing Magisk sometimes helps. For me it hasn't fixed the issue though. Any recommendations?

**Comment by jcgruenhage** [comment]
Well.. It just started working again, without changing anything. I didn't even reboot or anything. Well, I guess I'll leave this open though, since the issue is not really resolved, just unpredictable.

**Comment by topjohnwu** [comment]
I cannot fix it without any information lol

**Comment by jcgruenhage** [comment]
Well, I've linked an issue above, where I have some logging. If you need more, just tell me what you need, and I'll see if I can get that.


lol

**Comment by birdgofly** [comment]
I just installed Magisk (v12.0).. MagiskSU did not prompt for superuser access in two of my apps, Tasker and Lucky Patcher. Googling shows that others have had this problem for both apps.. 

For Tasker, I was able to get MagiskSU to prompt by running a Run Shell command in Tasker prefaced with /sbin/su -c. 

I still have not gotten Lucky Patcher to work however. Others have suggested that forcing root mode within the Lucky Patcher settings ("exotic root"), and then closing and reopening the app causes MagiskSU to prompt, but I have not had any luck with this. 

https://www.reddit.com/r/tasker/comments/5sfc8p/fyi_if_you_upgrade_to_magisk_v11/ddge2el/
https://www.reddit.com/r/Piracy/comments/6709kt/lucky_patcher_with_magisk_120/

Several other apps have prompted no problem though. Not sure if the issue is on Magisk's end or the apps themselves. Just wanted to let you know that it is an issue.

**Comment by Didgeridoohan** [comment]
@birdgofly 
Are you seriously asking a developer for help with an app that cheats developers? Bad form...

**Comment by Jasi2169** [comment]
this issue is from long to be honest i have been experiencing this from long!

right now it is not prompting for me either but the quick fix is by reflashing SYSTEM IMAGE by twrp and flashing magisk.zip again

last time it worked itself it was not prompting and then after some hours prompts came when i was in middle of youtube watching
