### ISSUE TITLE
Magisk root toast changes activity focus

### ISSUE THREAD

**Issue by tobadia** [topjohnwu/Magisk#1412]
Hi,
The latest update somehow messes with Oneplus original camera app. Confirmed on my OP5T and on another OP6, under OOS 9.0.4 and 9.0.5.

Symptoms : camera app somehow reboots the camera module every few seconds, also resetting the focus. See here for video : https://youtu.be/mZOcQasDWG4

Third party apps accessing camera aren't affected, surprisingly.

Edit: actually, some third party apps aren't affected (e.g whatsapp) but others still are
Edit2: this seems somehow related to the Cerberus app, each reset coincides with an su request that gets granted, as if the app was stuck in a loop asking for su privileges

**Comment by F-i-f** [comment]
This issue is extremely annoying for anyone having "su" invoked in the background (eg. through Tasker, AFWall, etc).  Even though the apps (Tasker, AFWall) have root granted, every time su is called, the current running app looses focus.
I'm running the latest Canary build (7.1.2-0dbbcad8 Manager + 7.1.2-80cd85b0 Magisk), and the problem seems to be solved there.
Please consider pushing a new beta or stable release with this fix in.

**Comment by Didgeridoohan** [comment]
Of course there'll be a beta/stable release based on the current code base. Use the Canary builds or wait patiently, those are your options.
