### ISSUE TITLE
Video get minimized if root request accepted in background

### ISSUE THREAD

**Issue by Senliast** [topjohnwu/Magisk#1413]
If I am watching YouTube or Netflix and some app tries to get root in background (toast root granted shows), the video minizes in this small pop up window, as if I had opened another app.
No matter which app asks root, for example Tasker or Automate or FolderSync, video always get minimized.
May be, there is an overlay or invisible windows that Magisk creates for one moment while giving root? Do you have this problem too or only me?

Latest Magisk Canary, Pixel 2, stock Pie.

**Comment by Cubox-** [comment]
I have this as well, on Magisk 19.1 and Manager 7.1.2

I have no toast nor prompt when the video gets minimised, but this problem appeared when I updated Magisk 19 to 19.1 (and the Manager update that went with it)

**Comment by Cubox-** [comment]
Reverting to Magisk 19 fixes this problem.

**Comment by Ingan121** [comment]
I have similar problem, keyboard goes down when the toast appears.
A transparent activity comes out for a short time then closes.
I think [this commit](https://github.com/topjohnwu/Magisk/commit/8d4c407201519f39dcaf38a942808141d0ff9fbc) caused the issue since this happened since the canary version which contains this commit.

**Comment by topjohnwu** [comment]
#1412
