### ISSUE TITLE
TV Banner Magisk Manager

### ISSUE THREAD

**Issue by bubuleur** [topjohnwu/Magisk#1481]
Hello,
I allow myself to come back to you to put a shortcut on androidtv oero for magisk manager
attached modified apk file
[MagiskManager-v7.2.0-TV-Banner.zip](https://github.com/topjohnwu/Magisk/files/3206120/MagiskManager-v7.2.0-TV-Banner.zip)
I tested on my nvidia shield tv 2017 it works very well attached photo to see
![Atv](https://user-images.githubusercontent.com/21688137/58155127-94244900-7c73-11e9-86e6-6407d9193ce1.png)
Is it possible to put this shortcut in your next update
Thanking you

**Comment by bubuleur** [comment]
![magisk_manager](https://user-images.githubusercontent.com/21688137/58249108-446e7c00-7d5e-11e9-8300-77fa7aaf3fb8.png)
Enclosed picture sorry png I do not speak English I use a translator I did not understand your message very well
it is possible if you can do it?
I do not know much about it
thank you so much

**Comment by mo123** [comment]
Hi

I made 5 Magisk Manager shortcuts apps with different pictures for AndroidTV.
If you install a new Magisk Manager app or update it, the shortcut app will still work.
In Android - Settings - Apps - There will be an extra Magisk Manager app of 90KB.
Your image is app number (4).
[Magisk_Manager_ATV.zip](https://github.com/topjohnwu/Magisk/files/3212154/Magisk_Manager_ATV.zip)

**Comment by bubuleur** [comment]
Thank you for your help but what will this shortcut be in the next Magisk manager update?

**Comment by mo123** [comment]
These changes must be added for it to show a banner and get a tv layout.
https://developer.android.com/training/tv/start/start to
https://github.com/topjohnwu/Magisk/blob/master/app/src/main/AndroidManifest.xml

So you must fork the Magisk Github repo apply the changes and submit a Pull Request so it can get merged and be included in the next update.
Maybe someone else can do it, since I'm not 100% sure how. 

My shortcut app was just a simple way to use 2 apps to do something similar without building a whole new app with patches that is more complicated.

**Comment by topjohnwu** [comment]
I don't own an Android TV device, so I can't fix it properly. If you are a developer, contribute via PR
