### ISSUE TITLE
Some writings are too small in Magisk Manager

### ISSUE THREAD

**Issue by MarcAnt01** [topjohnwu/Magisk#1508]
![image](https://user-images.githubusercontent.com/43090263/58383460-70e0fd00-7fd7-11e9-8820-e89822a977e4.png)

**Comment by MarcAnt01** [comment]
default DPI values and 115% font

**Comment by martyfender** [comment]
I also have this issue on my 8", 188 DPI tablets, Nextbook Ares 8A, Intel x86, Android 6.0.1. I use the light theme and root prompt windows are very light and hard to read, also. I had also reported this to @diareuse , the author of the new Magisk Manager UI, In a thread he had created for the new UI and stated he was closing that thread. He asked to report to him through PM's. I have not since I had already reported the issues in that thread.

[https://forum.xda-developers.com/showpost.php?p=79452270&postcount=33](url)

**Comment by MarcAnt01** [comment]
> I also have this issue on my 8", 188 DPI tablets, Nextbook Ares 8A, Intel x86, Android 6.0.1. I use the light theme and root prompt windows are very light and hard to read, also. I had also reported this to @diareuse , the author of the new Magisk Manager UI, In a thread he had created for the new UI and stated he was closing that thread. He asked to report to him through PM's. I have not since I had already reported the issues in that thread.
> https://forum.xda-developers.com/showpost.php?p=79452270&postcount=33

I definitely think reporting on GitHub is the best solution, as he can avoid thousands of equal reports and also users can keep track of the bugs

**Comment by diareuse** [comment]
This is a known issue. Nevertheless the redesign is gonna take longer than originally anticipated so this will be fixed in the next MM release.

**Comment by martyfender** [comment]
Thank for letting us know and for all of your work with this new ui.

**Comment by diareuse** [comment]
> ![Screenshot_20190526-170118](https://user-images.githubusercontent.com/29962147/58387167-90c4f080-7fd8-11e9-99af-f29e3898e168.png)

This has been already fixed. It's waiting for internal approval alongside with other QOL improvements and internal app changes.

I'm gonna close this issue and both of your reports are being tracked [here](https://github.com/diareuse/Magisk/projects/2#card-22003600) and [here](https://github.com/diareuse/Magisk/projects/2#card-22003585) respectively.
