### ISSUE TITLE
Realme 3 Pro Magisk V.19.2

### ISSUE THREAD

**Issue by TaiHoki888** [topjohnwu/Magisk#1533]
Hello, i tried flashing Magisk v.19.2 and in my phone (Realme 3 Pro) it detects that the boot image has been tampered as it can be seen in the attached screenshot and thus it fails to boot. Is there any workaround for this?

**Comment by fawazahmed0** [comment]
@TaiHoki888  Where is the attached screenshot

**Comment by TaiHoki888** [comment]
![IMG_20190531_172240](https://user-images.githubusercontent.com/26304866/58716660-b0eb1a00-83f3-11e9-9652-5122b2ab9189.jpg)

**Comment by TaiHoki888** [comment]
Why is this closed @topjohnwu ???

**Comment by Ingan121** [comment]
Because it is natural to see that warning if you unlocked the bootloader. Currently, there is no workaround for this.

**Comment by chankruze** [comment]
@Ingan121 @topjohnwu Flashing Magisk bricks device and it boot loops. I am not asking for a solution here, i want to know what is the possible issue. Do this favor, cause realme3 and 3 pro both has this same issue.

**Comment by fawazahmed0** [comment]
@chankruze can you post the kernel logs, that might be helpful for them to solve the problem.
The bootloop log is stored here :/proc/last_kmsg

**Comment by Snaxeko** [comment]
> Because it is natural to see that warning if you unlocked the bootloader. Currently, there is no known workaround for this.

??? Sorry for updating this so late, but the warning never talks about unlocking bootloader. It's just dm-verity that needs to be disabled the 1st time Magisk is installed. 

So the fix is, before installing (Magisk-boot-image-patched).img, just disable dm-verity and verification. What you need to do to install Magisk on Realme devices:

1. Extract boot.img & vbmeta.img from the ozip file (need to decrypt the ozip file to convert it to .zip, cannot be done easily)
2. **fastboot --disable-verity --disable-verification flash vbmeta (stock-vbmeta).img**
3. fastboot flash boot (Magisk-boot-image-patched).img

There you go, Magisk works like a charm.

**Comment by Mek101** [comment]
@Snaxeko What version of Magisk were you using?

**Comment by Snaxeko** [comment]
@Mek101 It works up to 21.4, I didn't installed the last version

**Comment by Mek101** [comment]
@Snaxeko Ok, I installed the latest version (22.0) and it works well. I had a problem on my previous install, but apparently it was unrelated to Magisk itself.
