### ISSUE TITLE
[Module development] $MODPATH not writable 

### ISSUE THREAD

**Issue by alexa-v2** [topjohnwu/Magisk#1565]
Hi @topjohnwu and others

My module normally is a ~450MB zip. Pretty hefty, but I need to include apk and libs for several architectures

So I decided to host the zips for each arch in a separate repository, and at runtime dynamically download the necessary files and unzip to $MODPATH, thereby making base zip less than 1MB and each separate set of files for each arch 120-160MB 

Problem is, any attempts to write to $MODPATH have zero effect. CP, MV, unzip, mkdir, touch all don't have an effect 

Why can't my module instar write to my $MODPATH?

**Comment by alexa-v2** [comment]
Instar= installer

**Comment by topjohnwu** [comment]
I don't know what you are talking about. If `$MODPATH` is not writable, **NON** of the existing modules currently on the repo can be installed

**Comment by alexa-v2** [comment]
Permit me to rephrase:

After the initial zip is installed to $MODPATH no further adjustments can be made

To test this, I created a dummy module and in the installer script put "touch $MODPATH/itworks". Guess what file never showed up

**Comment by alexa-v2** [comment]
@topjohnwu I'm sorry if I wasn't clear

**Comment by Didgeridoohan** [comment]
@alexa-v2 There's no issue creating or copying files in/to $MODPATH. If there was, no modules would be able to install at all...

Sounds more like you need module creation support, and since the issue tracker isn't a support forum you're better off opening up a "I need help with my module"-thread on xda (or forum of your choice).
