### ISSUE TITLE
Android Q Beta 3 Incompatibility

### ISSUE THREAD

**Issue by refi64** [topjohnwu/Magisk#1578]
I'm aware a similar issue has been fixed recently, but [several people have reported experiencing this on beta 4](https://forum.xda-developers.com/showpost.php?p=79683753&postcount=1634) (including me I guess), symptoms include:
- Apps randomly take insane amounts of time to open.
- System UI will crash sometimes when attempting to take screenshots because the start-up lag is so bad.

At least for me, I'm definitely on Magisk 19.3, and afaik nothing major has changed on the canary builds since.

You're probably already aware of this issue, but I figured reporting here is still worthwhile.

**Comment by jpcaldwell30** [comment]
I am experiencing this as well. I can provide logcat if necessary.

**Comment by refi64** [comment]
Some people on XDA seem to have reported that [flashing Magisk *twice* and wiping Dalvik fixes it](https://forum.xda-developers.com/apps/magisk/dev-magisk-canary-channel-bleeding-edge-t3839337/post79716536#post79716536).

**Comment by jpcaldwell30** [comment]
No luck with flashing twice and wiping cache. I've tried pretty much every variation of install/twrp/delete cache that I can think of. I'm gonna keep trying things and ill report back if I can figure it out but for now having magisk installed either causes infinite boot (stuck on boot or "pixel is starting") or crazy lag

**Comment by 8lexliu** [comment]
Crazy lags all over the system(both system apps and third-party apps

**Comment by 8lexliu** [comment]
> Crazy lags all over the system(both system apps and third-party apps

Tried the method on XDA (flash magisk twice and wipe dalvik  magically fixed the issue at my side )

**Comment by jpcaldwell30** [comment]
> > Crazy lags all over the system(both system apps and third-party apps
> 
> Tried the method on XDA (flash magisk twice and wipe dalvik magically fixed the issue at my side )

Can you provide more info about your setup? Phone and os version? Did you flash with twrp? Which version? Just want to try and replicate your procedure exactly. I have an original pixel xl running QPP4.190502.019 dirty flash upgrade from Q beta 3. Really trying not wipe my phone so ive been dirty flashing everything.

**Comment by 8lexliu** [comment]
OG Pixel XL running latest version of Q
Flash patched image via fastboot twice didn't work for me,So I restored to original boot image.
The method which worked for me:
1; Fastboot boot latest twrp.img
2;Use twrp to flash the latest magisk TWICE then wipe the dalvik and that's it.

**Comment by refi64** [comment]
Hmm I don't think it's canary (nothing important has really changed since 19.3), but the use of TWRP seems interesting...

**Comment by jpcaldwell30** [comment]
Did you get the twrp error messages "can't mount /system", "can't mount /vendor" at the end of the twrp operations (both flashes and deleting cache). I tried exactly as described but I just ended up getting stuck at "Pixel is starting" after boot. Tried booting twrp again and wipe cache again (first wipe after last magisk flash as instructed). When I booted after wiping cache I got stuck at the Google boot screen with the loading bar at the bottom

**Comment by refi64** [comment]
@jpcaldwell30 Did you select to remount as rw in the TWRP screen? IIRC this messes with it somehow.

**Comment by jpcaldwell30** [comment]
You mean skipping the twrp decrypt step before flashing magisk? No i decypted magisk because i had the magisk file in my internal storage so i needed to decrypt. I did try flashing magisk without decrypting at one point the other day but nothing came of it.

**Comment by refi64** [comment]
I mean after that, when TWRP asks you if the system should be mounted as read-write or read-only.

**Comment by jpcaldwell30** [comment]
> I mean after that, when TWRP asks you if the system should be mounted as read-write or read-only.

I don't get that option. After the decrypt step it goes straight to the home screen of twrp (the screen that lists all of twrps functions)

**Comment by jpcaldwell30** [comment]
So to give a better idea of what is going on I decided to flash stock and take logcats of all the different things I have tried and encountered. All of these are dirty flashes though because I want to keep my data (deleted -w from flash-all.bat). The first logcat is a normal boot after flashing stock which results in a fully normally functioning phone. The second is after following my understanding of the magisk flashing steps. 1. boot (not flash) twrp.img via fastboot. 2. At the decrypt data step, enter device pin and wait for decrypt to finish. 3. At twrp home screen choose "install" then navigate to downloaded magisk zip. In my case this is Magisk-v19.4-c1602d25(19301).zip and swipe to confirm flash. Wait for flash to finish. 4. Upon finishing flash, select "Wipe Dalvik" option that appears next to "Reboot System". 5. Confirm wiping dalvik by swiping to confirm. 6. After waiting for dalvik wipe to complete, choosing "Reboot System". I ran the logcat command for the second logcat directly after performing step 6 and seeing the bootloader unlocked warning. Another thing to note is that after performing the magisk flash and dalvik wipe, at the end of both of those scripts where it "Updating partition details", I got two red error messages saying "failed to mount /system (invalid argument)" and directly after another line saying  "failed to mount /vendor (invalid argument)" for both. After flashing with the previous steps, my phone was stuck at the google booting screen with the loader bar underneath for about 10 minutes with no change. Finally, the third logcat is from following the same steps as the first attempt at flashing magisk except I flashed stock boot image after aborting the last boot (the one mentioned above) and between steps 3 and 4, I tapped back a few times to get to the install step again (without wiping dalvik in between) and selected the same magisk zip again to try and double flash as mentioned in this thread above. After the completion of the second flash I then tapped the "Wipe Dalvik" button and followed the rest of the steps outlined for the first flashing attempt. I also encountered the same twrp mounting errors on this attempt as well. After rebooting twice (first time boot took too long and the second system ui crashed) the third boot I got into the system however the slowness of some apps persisted. The third logcat includes this successful boot with me opening a few apps that ended up being slow. Google play and maps were the two that I noticed to be slow. After rebooting a 4th time I opened magisk and noticed it was in core only mode. So I disabled that because I wanted to use modules and rebooted. I then got stuck "Pixel is starting" screen. I then started a final logcat and booted to this state. 

1. [stock-boot.txt](https://github.com/topjohnwu/Magisk/files/3297920/stock-boot.txt)
2. [magisk-boot.txt](https://github.com/topjohnwu/Magisk/files/3297917/magisk-boot.txt)
3. [magisk-boot-dual-flash.txt](https://github.com/topjohnwu/Magisk/files/3297918/magisk-boot-dual-flash.txt)
4. [magisk-boot-dual-flash-core_only_disabled.txt](https://github.com/topjohnwu/Magisk/files/3297919/magisk-boot-dual-flash-core_only_disabled.txt)

**Comment by 8lexliu** [comment]
1: Fastboot boot TWRP.img
2: install "uninstallmagisk.zip"
3: reboot to bootloader then flash stock image
4: reboot to system (I used it for 10+ mins? And magisk app still exists and I didn't uninstall it )
5: fastboot boot TWRP.img
7:install magisk *twice* then wipe the dalvik
8:Reboot to system
This solution works for me.

**Comment by refi64** [comment]
> reboot to bootloader then flash stock image

You mean the stock boot.img?

**Comment by jpcaldwell30** [comment]
I THINK THAT MAY HAVE ACTUALLY DONE IT! Thank you everyone! So far so good. One thing to note however is that upon first boot after flashing magisk twice as stated, the system was still slow opening some apps and I had internet connectivity issues (both cellular and wifi). I rebooted however and now everything seems to be working.

**Comment by JohnLGalt** [comment]
>  3: reboot to bootloader then flash stock image



> 1: Fastboot boot TWRP.img
> 2: install "uninstallmagisk.zip"
> 3: reboot to bootloader then flash stock image   **<-- Is this supposed to be Flash stock boot.img**, as opposed to the full system image
> 4: reboot to system (I used it for 10+ mins? And magisk app still exists and I didn't uninstall it )
> 5: fastboot boot TWRP.img
> 7:install magisk _twice_ then wipe the dalvik
> 8:Reboot to system
> This solution works for me.

See above in quotation.  I already cleanly installed Android Q Beta 4 Build .019, and I'm having all sorts of issues, even after the clean install.  If your step 3 is for the boot.img only (which I suspect it is, as you mention Magisk Manager still being installed, meaning your data was not wiped, but that _could be a Full System Image flash with the "-w" removed, so...._)

Please let us know, I'm frustrated with the continuing lag in a wide variety of scenarios, you can see a much more detailed list of times when it has occurred to me in the XDA Android Q thread.

**Comment by 8lexliu** [comment]
> > 3: reboot to bootloader then flash stock image   **<-- Is this supposed to be Flash stock boot.img**, as opposed to the full system image
> 
> See above in quotation. I already cleanly installed Android Q Beta 4 Build .019, and I'm having all sorts of issues, even after the clean install. If your step 3 is for the boot.img only (which I suspect it is, as you mention Magisk Manager still being installed, meaning your data was not wiped, but that _could be a Full System Image flash with the "-w" removed, so...._)
> 
> Please let us know, I'm frustrated with the continuing lag in a wide variety of scenarios, you can see a much more detailed list of times when it has occurred to me in the XDA Android Q thread.

Stock boot image

**Comment by jpcaldwell30** [comment]
> > 3: reboot to bootloader then flash stock image   **<-- Is this supposed to be Flash stock boot.img**, as opposed to the full system image
> 
> See above in quotation. I already cleanly installed Android Q Beta 4 Build .019, and I'm having all sorts of issues, even after the clean install. If your step 3 is for the boot.img only (which I suspect it is, as you mention Magisk Manager still being installed, meaning your data was not wiped, but that _could be a Full System Image flash with the "-w" removed, so...._)
> 
> Please let us know, I'm frustrated with the continuing lag in a wide variety of scenarios, you can see a much more detailed list of times when it has occurred to me in the XDA Android Q thread.

I think he meant flash stock boot img but i went ahead and flashed full stock anyway because it wouldn't hurt anything. It ended up working for me even though i was having the exact same problems as you. I followed the instructions above. It will probably not fully boot the first time, just restart and let it boot again. The second time i got a full boot but had lag issues. Rebooted. Third boot lag issues were resolved.

**Comment by JohnLGalt** [comment]
Right on.  About to do this and see how well it comes out.

Thanks for the quick replies, Alex and jp :+1:

**Comment by xunholyx** [comment]
> 1: Fastboot boot TWRP.img
> 2: install "uninstallmagisk.zip"
> 3: reboot to bootloader then flash stock boot image
> 4: reboot to system (I used it for 10+ mins? And magisk app still exists and I didn't uninstall it )
> 5: fastboot boot TWRP.img
> 7:install magisk _twice_ then wipe the dalvik
> 8:Reboot to system
> This solution works for me.

The magisk uninstall.zip restores your stock boot.img afaik. During the install of the magisk.zip it says in the readout "backing up stock boot.img" or something like that, and it does that for this reason.

**Comment by JohnLGalt** [comment]
True.  However, the previous trick of **double** installing Magisk was also a redundancy that nevertheless seemed to work for many.

I'm trying this in a couple of hours - keeping my fingers crossed.

**Comment by JohnLGalt** [comment]
OK, done - now let's see if it worked.

It was definitely a lot less laggy with Magisk uninstalled.

**Comment by JohnLGalt** [comment]
And nope - already had my first slow-down within minutes of performing all of these steps.

Sigh.

**Comment by JohnLGalt** [comment]
OK, so another day, and a new Canary build - which b0rked.  Prior to taking the new build, however, I still had slow downs this morning.

Time to make this work correctly by manually flashing the canary.

**Comment by refi64** [comment]
Wonder if this could be related somehow to #1581...

**Comment by JohnLGalt** [comment]
It might - the new canary build states the change being the following:

Delay /sbin overlay mounting, could potentially fix tons of bootloops

https://github.com/topjohnwu/magisk_files/blob/master/canary_builds/notes.md#magisk-1058aeb0-19302

I'm in the process of removing the device screen lock so I can obtain recovery.log, as it tries to save to an encrypted location if I don't try to unlock in TWRP, and thus is unavailable to get to make a bug report for the new canary build.

**Comment by refi64** [comment]
So I tried the steps mentioned before and it...didn't work. However, I did notice something in the logcat, where it mentioned the activity that lagged on opening timed out.

**Comment by refi64** [comment]
Ah some more stuff of interest: 
- Shortly before the timeout, ActivityManager logs `Process ProcessRecord{44827be 30410:com.dp.logcatapp/u0a157} failed to attach`.
- When the System UI timed out while taking a screenshot, some process crashed every time the screenshot button combination was pressed, but no tombstone was written due to permission errors. I might try monitoring it somehow.

Also, I think I'll try dropping disabling MagiskHide and see how it goes, mostly since GPay is broken with Magisk on Q anyway.

**Comment by refi64** [comment]
Well this isn't ideal but disabling Magisk Hide definitely seems to have 100% fixed the slow app starts and screenshots. I suspect this is related to the ptrace system somehow...

**Comment by JohnLGalt** [comment]
Not for me - it has definitely stopped interfering with screenshots, but I'm still suffering some incompatibilities elsewhere.

However, now that the Google app has updated as well, it might be related to that instead.

I plan to flash the canary build again, disable Magisk Hide, and force install an older Google App and set it to not automatically update, and see if that (all of it together) makes a difference.

**Comment by JohnLGalt** [comment]
OK, about to try the previous canary build - I've got the older 10.4.5.21 Google App installed with auto update disabled in Play Store for it, and thus far the experience on Q Beta 4 seems to be a lot smoother.

I suspect that the combination of both the older Google App + disabling Magisk Hide will result in far, far fewer slowdowns (hopefully eliminate them entirely!).

**Comment by JohnLGalt** [comment]
**Disabling Magisk Hide + Force installing Google App 10.4.5.21** (and disabling auto update of it in Play Store) has removed _**all** lagginess_ with Magisk Canary (debug) build c1602d25 (19.4-c1602d25 (19301)).

I've since updated Magisk **_Manager_** to **7.3.1-1058aeb0 (225)**, as that is the latest offered on the Canary (debug) channel, and no issues whatsoever.

Thanks, @refi64 for testing and figuring out the Magisk Hide was a part of the issue, and thanks @xunholyx for posting at XDA about the specific Google App version number to avoid the lag.

As of right now, I'm not taking the Magisk update to 19.4-1058ae0 as it has caused me bootloops galore, but all is well when running as stated in this post.

**Google Pixel 2 XL (aka _Taimen_)**
**Android Q Beta 4 build .019**

![Screenshot_20190626-155755](https://user-images.githubusercontent.com/7432512/60210645-55158480-982b-11e9-8292-3452cbb04a80.png)

**Comment by refi64** [comment]
@JohnLGalt Do you want to share that on the XDA thread?

**Comment by JohnLGalt** [comment]
Good idea :+1:

**Comment by topjohnwu** [comment]
Full Q support is live in the latest canary

**Comment by refi64** [comment]
Flashed and been running for a bit, was admittedly a bit apprehensive of using a Canary build but it's working perfectly thus far!
