### ISSUE TITLE
Superuser tab shows no apps

### ISSUE THREAD

**Issue by gordboy** [topjohnwu/Magisk#1592]
New Manager version 7.3.0 shows no apps in the Superuser tab. Everything else seems OK.

**Comment by DarkenLX** [comment]
Same issue Magisk 19.3 Manager 7.3.0 device Samsung Galaxy S9 plus SM-G9650 Android 8.0.0

**Comment by diareuse** [comment]
> Same issue Magisk 19.3 Manager 7.3.0 device Samsung Galaxy S9 plus SM-G9650 Android 8.0.0

Please refrain from posting this kind of replies. It provides no additional info apart from your device maker, type and OS version. These are ofter super irrelevant as the issue can come up on all variety of devices.

> New Manager version 7.3.0 shows no apps in the Superuser tab. Everything else seems OK.

Thanks for reporting this issue. Can you provide a full logcat ***after*** replicating the issue, please?
_(Ideally force quit the app - or swipe it away from recents - then replicate the issue and post a logcat here.)_
[Here's how to use logcat cmd tool](https://developer.android.com/studio/command-line/logcat)
[Or pick up logcat reader app](https://play.google.com/store/search?q=logcat&c=apps)

**Comment by AngelFalse** [comment]
Same issue for Oneplus A6000, H2OS 9.0.4 Android 9.  Magisk 19.3, manager 7.3.0
**No such issue** for LineageOS lineage_libra-userdebug 7.1.2 NJH47F Android 7.1.2 Xiaomi Mi-4C. **Same Magisk and manager version.**
Android version difference problem.


Apps requesting root permission: OK
New App (com.dp.logcatapp) requesting root permission: Popup Window: OK. Fingerprint Authentication: OK. Granting root permission: OK.

Logcat Fragments: 
1.Logcat of Manager app starting:
https://privatebin.net/?91ab3d3d54a9d68a#s1yQYeHJSvryYI+Spd9E8Tj+6uMeJAgdfBAp1S0ZVtw=
2.Logcat of ES File Explorer requesting root permission:
https://privatebin.net/?3a191568419be0de#QaFrFIoXU1/bVtnnP/8bOJXC/Vu//iCHZeTzYpCVGOI=

Because there's way to many information in the logcat log, these two pastebin documents will _self-distruct in 30 days_, and _information considered irrelevant (like WifiStateMachine etc.) is removed_.
If reviewing these logcat didn't solve the problem, reply to me.

**Comment by diareuse** [comment]
https://github.com/topjohnwu/Magisk/commit/f4f0961076a891bec6811fcf2d6ded24b68fd52b

**Comment by adrenochrome25** [comment]
sorry for the duplicate #1599
here's a minimal log ( clean all buffers ; launch magiskmanager ; go to Superuser menu entry ; wait 2 sec on the empty listing )
[magiskmanager_logcat.log](https://github.com/topjohnwu/Magisk/files/3294165/magiskmanager_logcat.log)
(com.amaze.filemanager is a filemanager that was uninstalled long ago but was probably root granted when it was installed)
