### ISSUE TITLE
Unable to pipe MagiskHide output

### ISSUE THREAD

**Issue by davidramiro** [topjohnwu/Magisk#1610]
Hi,

never had an issue with Magisk itself, although I am experiencing a minor inconvenience when trying to use pipes with MagiskHide in a su shell. I'd love to use the command within a shell script.

For example, using `grep` with the regular magisk binary works fine, e.g. checking the version:
```
# magisk -c  | grep -q '19300' && echo 'This works and prints this string.'
This works and prints this string.
```

Along the same lines, it doesn't work with MagiskHide:
```
# magiskhide status | grep -q 'enabled' && echo 'This does not work and instead prints the MagiskHide output.'
MagiskHide is enabled
```

I'd like to be able to use that command within a conditional statement in a shell script among other things. Am I missing something here or is this behaviour intended?

**Comment by alvinhochun** [comment]
Two things that I see (by reading the source code without testing):

1. Output of `magiskhide status` is written to stderr instead of stdout, so in order to pipe its output to other commands you need to add `2>&1` before the pipe to redirect stderr to stdout.
2. `magiskhide status` appears to return different status codes depending on the state of MagiskHide (`0` when enabled and `1` when not enabled) so I don't think `grep` is needed at all.

**Comment by davidramiro** [comment]
>Output of magiskhide status is written to stderr instead of stdout

Ah, that was exactly the info I was missing! Working with status codes would indeed be easier for this particular command, although not for parsing output from e.g. `magiskhide ls`, hence I wanted to use `grep`.

Thank you!
