### ISSUE TITLE
Magisk Manager 7.3.1 crashes

### ISSUE THREAD

**Issue by Qyrln** [topjohnwu/Magisk#1619]
Magisk Manager crashes when pressing at superuser section
Custom Rom 7.1.2
Log : https://del.dog/radupiviku

**Comment by RegFau1t** [comment]
I had blank super user tab before 7.3.0. At 7.3.0 it worked, and at 7.3.1 it crashes when i enter super user tab too. Exact same problem. Original ROM.

**Comment by RegFau1t** [comment]
Edit: rebooted phone. Magisk still crash on super user tab. Lucky patcher asked for root permission, and since this event. It now crash 1 time, and after it auto restart, the Super User tab works. If i leave Magisk Manager and remove it from background. Same thing happens. 1 crash, then work good. Before the reboot and luckypatcher pop up for root. It crashed no matter how many time i relaunch app. (Maybe it can help discover the reason)

**Comment by diareuse** [comment]
Inconsistency fixed here https://github.com/topjohnwu/Magisk/commit/0a1c54175382420a510550581a9b043aa0416a11
Crashes fixed here https://github.com/topjohnwu/Magisk/commit/5aa15a2b61083b8a2d95b8870da4de3d1aaab6b8
