### ISSUE TITLE
com.starfinanz.mobile.android.pushtan detects root with enabled Magisk Hide (again)

### ISSUE THREAD

**Issue by lopez1de** [topjohnwu/Magisk#1710]
Exact same issue as described here:

https://github.com/topjohnwu/Magisk/issues/1084

**Comment by Didgeridoohan** [comment]
FFS...

First of all: https://github.com/topjohnwu/Magisk/issues/1152 (It's pinned to the top of the issues page, so shouldn't be this easy to miss).

Second: https://github.com/topjohnwu/Magisk/blob/master/README.MD#bug-reports

Third: You're doing something wrong, because I still have no issues opening the app. Here's how: https://www.didgeridoohan.com/magisk/MagiskHide#hn_Hiding_root_from_apps

Fourth: you can close this now, so that John doesn't have to waste his time doing it for you.

**Comment by lopez1de** [comment]
Ok thanks...
