### ISSUE TITLE
magiskboot unable to process sfx gzip kernel

### ISSUE THREAD

**Issue by 13-beta2** [topjohnwu/Magisk#1714]
Magiskboot util is unable to detect and unpack zImage with "classic" layout:
* decompressor code (starts with a bunch of arm32 nops)
* gzipped kernel
* dtbo chunk

As seen in 7-zip:  
![image](https://user-images.githubusercontent.com/2017168/61590147-e2df5800-abbc-11e9-993f-0bbf1740d305.png)
Not a problem in case of pre-P kernel, but my kernel is system-as-root, so it must be patched to force using injected ramdisk.

Att: [patched kernel of xiaomi redmi 7a](https://github.com/topjohnwu/Magisk/files/3414513/magisk_patched.zip).

**Comment by topjohnwu** [comment]
Unfortunately, there is no way to patch armeabi zImage kernel since the gzip size cannot be ensured to be the same size when repacking after patching. The gzipped kernel size depends on the compression algorithm, and there is no guarantee that after modifying the original file, the deflate algorithm (what gzip uses) will produce a binary with the same size.

I had tried to patch the offset/pad zeros in the case when the size mismatch, but none of it works.

BTW, I think your device should be using A only system-as-root right? You should try to install Magisk to the recovery as normal boot images might not work anyways.

**Comment by 13-beta2** [comment]
@topjohnwu Thanks for prompt reply. Your concerns are clear. Re-compress patched binary into same sized file is barely achievable.
But pls let me add some details. AFAIK vendor kernel are usually compressed using default settings and any optimized compression *usually* leads to smaller file. I've managed to successfully boot with patched boot.img using re-compressed kernel binary simply OVERWRITTEN over original binary in zImage. (So I had next layout: **untouched** decompressor code, then **patched** gzipped kernel, then short tail of original gzipped kernel and at last **untouched** dtbo binary.) In this case there is no need to do any kind of fixups in decompressor code nor dtbo.

Agree. This sounds like quite dirty workaround, but I believe this way of magisk delivery much more convenient for end users.

**Comment by f1-outsourcing** [comment]
@13-beta2 

> But pls let me add some details. AFAIK vendor kernel are usually compressed using default settings and any optimized compression _usually_ leads to smaller file. I've managed to successfully boot with patched boot.img using re-compressed kernel binary simply OVERWRITTEN over original binary in zImage. (So I had next layout: **untouched** decompressor code, then **patched** gzipped kernel, then short tail of original gzipped kernel and at last **untouched** dtbo binary.) In this case there is no need to do any kind of fixups in decompressor code nor dtbo.

You can just append the file to the correct size, not?

`SIZE=10485760; dd if=/dev/zero of=test.tar.gz bs=1 count=$(expr $SIZE - $(stat -c%s test.tar.gz)) seek=$(stat -c%s test.tar.gz)`
