### ISSUE TITLE
[Regression] App lock once again causing root to be ungrantable

### ISSUE THREAD

**Issue by alexa-v2** [topjohnwu/Magisk#1715]
Back in 19.3 iirc the issue with app lock (full screen and steals focus) causing me to be unable to use my fingerprint to grant root access, and I had to deny and manually go in and grant, was fixed

Now with the latest canary the issue is back. I use sophos mobile security for app lock, but have tested with other apps

I'm using Resurrection Remix 7.0.2 with Magisk 19307 and manager 228 on a Moto z3 play

Will upload logs ASAP

**Comment by alexa-v2** [comment]
Logs:
https://drive.google.com/folderview?id=1-3HM5qjB3R5TiMSNaJtBSzkmBm7uIu4Y

**Comment by Didgeridoohan** [comment]
@alexa-v2 That's definitely not a log (wrong link?).

The fix for su requests claiming focus was in v19.2, but it can only work if the OS doesn't block broadcasts. Nothing has changed on that part in 19307, and I can confirm that su is not claiming focus on my device (just like it's been working since v19.2).

If you have this the same issue back, your ROM is likely blocking broadcasts and there's nothing wrong with Magisk. Or, it's a whole new issue and more investigation is necessary.

**Comment by topjohnwu** [comment]
@alexa-v2 your rom is broken or blocking boot complete broadcasts. The daemon will try to send a broadcast to Magisk Manager at boot , and if it received it, it'll notify the daemon to use broadcasts instead of starting activities.

**Comment by alexa-v2** [comment]
@didgeridoohan it's the zip provided by matlog
@topjohnwu I can confirm neither is true - other apps can receive boot broadcasts, and I haven't blocked it for Magisk

**Comment by Didgeridoohan** [comment]
@alexa-v2 webview.zip with webview.apk inside?

If that's the case you've clearly got something else going on. Figure that out first...

**Comment by alexa-v2** [comment]
@didgeridoohan lool didn't even realize I still _had_ that in my Google drive...wtf

**Comment by alexa-v2** [comment]
https://drive.google.com/file/d/1-07nJLZ9DClTPw416v3Sdbrs2LBgX0Lw/view?usp=drivesdk this should be it
