### ISSUE TITLE
Offline charging doesn't work on the Xiaomi Redmi 7

### ISSUE THREAD

**Issue by rtmreza** [topjohnwu/Magisk#1723]
on xiaomi Redmi 7 or codename : onc/onclite   running android 9 with latest security patch and magisk 18~19.3

When the phone is charging and i turn it off, it reboots itself and hangs on android one logo. Same if the phone is put in charge when turned off.
 the phone will not display the charging animation when you try to charge the device while off.
when i remove root or flash stock boot.img its be ok

**Comment by Didgeridoohan** [comment]
You saw my link on xda, otherwise you probably wouldn't be here... Why didn't you read it? Here it is again (and it's pinned at the top of the issues page so I don't know how you missed it): https://github.com/topjohnwu/Magisk/issues/906

Bottom line: it's not Magisk's fault, nothing that can be fixed here, and you can close this issue now (to save John the trouble).

**Comment by rtmreza** [comment]
on mi6 magisk 19.3 has this problem but magisk 19 is ok
