### ISSUE TITLE
Failsafe in system

### ISSUE THREAD

**Issue by MaximilianGaedig** [topjohnwu/Magisk#1726]
Add a failsafe in /system cause in the Android q beta scoped Storage restricts access to Internal Storage in twrp, and if you can't get into the system you can't uninstall magisk

**Comment by fox8091** [comment]
It's not Scoped Storage denying that most likely, but rather the fact that most TWRP builds don't support V3 encryption, which has been forced since the May security update and the entire time on Q betas. Besides that, by modifying /system, you can break SafetyNet permanently (as even remounting can cause issues), making a reflash mandatory. However, I agree that there should be an alternate fallback location besides /data.
