### ISSUE TITLE
Can't Linked Data (ext.) With Magisk in Link2Sd

### ISSUE THREAD

**Issue by ignitexe99** [topjohnwu/Magisk#1800]
Hey there. I cant linked app data (ext.) with Link2sd when i use Magisk root ( cant bind data in sdext2). But when i use SuperSU it work, i can link data (ext.)
Please how to fix this??

**Comment by martyfender** [comment]
I use a very similar app: Apps2SD. In Magisk Manager settings, I set the Mount Namespace Mode to global. That is what was recommended in the past by the author of the program. I'm not sure if that is at all relevant to your problem, it is just something to try. Have you tried the Canary builds? I use Canary debug and unofficial builds by ianmacd on my devices and have no problem with binds with Apps2SD. The app does occasionally looses root, though and gives me the root prompt, especially after reboots or when the tablets have been asleep for some time. Other apps that have similar apply on boot settings also suffer from this occasionally, such as Kernel Aduitor and Lspeed.
My recommendation is to try the Canary debug build and provide logs:
[https://www.didgeridoohan.com/magisk/MagiskHelp](url)

**Comment by H42121** [comment]
ha ha ha, its funny ... I experienced the same thing, after three days after working hard to install root, install rom lineage 14.1, following installing magisk, all of which turned out to be not enough once installed, the last problem with link2sd, until I tried back and forth  and tried in various ways, browsing here and there until the root was lost, finally gave up for a while, I fiddled with the second partition with fat32 the same, ran link2sd, it turned out well, thank God .......
