### ISSUE TITLE
Package parse error when trying to update a hidden Magisk Manager.

### ISSUE THREAD

**Issue by martyfender** [topjohnwu/Magisk#1828]
On a hidden Magisk Manager only, there is a parse error when trying to update the manager to the latest build. Unhiding MM in settings and it is successfully updated. Then it must be rehid. If the user had the update channel set to anything other than the Canary debug, then it must be changed back twice, also.
Attached are filtered logcats using LogcatX's per app logcat.
[Log_2019-9-08_13-15-01.txt](https://github.com/topjohnwu/Magisk/files/3587828/Log_2019-9-08_13-15-01.txt)
[Log_2019-9-08_13-13-49.txt](https://github.com/topjohnwu/Magisk/files/3587829/Log_2019-9-08_13-13-49.txt)

If there is any better way to log this issue, please let me know.
Nextbook Ares 8A, Intel x86, Android 6.0.1 tablet, updating Magisk 19307 to 19308, updating MM 232 to 233, debug build.

Several users in the Unofficial thread also reported this issue over the last few, unofficial, @ianmacd builds.
I believe it was the commits around August, 21st or 22nd, when this started, @ianmacd 2019082201 build, if I am not mistaken.

Thanks

**Comment by IdanHo** [comment]
Happens to me on a redmi note 5 pro (whyred) android pie, only started on the latest magisk canary

**Comment by lemmy04** [comment]
this seems to be back in 7-3-5 -> 7.4.0, but also, restoring to the "unhidden" magisk manager does not work, it tries to restore the updated version which is already failing to parse.

**Comment by meadowsjared** [comment]
I was having this issue going from 7.3.5 to 7.4.0 on a Nexus 6p, and I did have my Magisk Manager hidden.
https://www.didgeridoohan.com/magisk/ManagerIssues
I attached screenshots of before when I was having the problem, as well as two screen shots showing how I was able to work around it.  I had to go to settings, then tap on "Restore Magisk Manager", then I was able to update the app, then after updating, I was able to go back into settings and tap "Hide Magisk Manager" and it seems to all work fine again.
Notably, I wasn't able to take a screenshot after hiding Magisk normally, I'm assuming this was due to the fact that it's hiding, but I was able to workaround not being able to take a screenshot by using an app called longshot.
![Screenshot_20191108-093147_Manager](https://user-images.githubusercontent.com/1596759/68508157-87e07800-0222-11ea-837b-3e5c3544e4c0.png)
![Screenshot_20191108-093141_Package_installer](https://user-images.githubusercontent.com/1596759/68508169-8ca52c00-0222-11ea-9414-f6b5a3940e92.png)
![2019-11-8_12-18-0](https://user-images.githubusercontent.com/1596759/68508309-e9a0e200-0222-11ea-93d2-931ffa6a702f.png)
![Screenshot_20191108-121502_Magisk_Manager](https://user-images.githubusercontent.com/1596759/68508312-ec033c00-0222-11ea-95f1-5e8525a4d9bd.png)
