### ISSUE TITLE
poor error reporting in magisk manager

### ISSUE THREAD

**Issue by ossilator** [topjohnwu/Magisk#1843]
i have a device with custom android 7.1.2, but a stone-aged 3.0 kernel (presumably because of proprietary binary-only modules). this of course won't work with magisk hide due to missing namespace mount support, but magisk manager just won't tell me - attempts to enable the option produce no error messages and nothing in the log. but the UI (the option and the corresponding menu entry) seemingly randomly succeed at enabling the option, so i lost hours chasing workarounds for the previously reported persistence bugs, etc., until i tried magiskhide on the command line, which finally gave me a clear error message.

this isn't the only problem of this type - for example, automated download attempts (be in magisk itself or modules) sometimes fail, and all i get is android's grey "failed download" notification, which is about as useless as it gets. similarly, i installed (or at least tried to) the magiskhide prop config module, but there is no "props" command line app after rebooting, and there is no indication whatsoever what is wrong - maybe it's the module's fault, but maybe not.

therefore, i'd urge you do make an audit of the complete code base for proper error checking and reporting.

**Comment by martyfender** [comment]
Are you using the Canary debug build, because it will give you much better logging. As far as the MagiskHide Props config, if you provide the proper logs to @Didgeridoohan, here:

[https://forum.xda-developers.com/apps/magisk/module-magiskhide-props-config-t3789228](url)
You will have to provide them the manual way as documented here, since you are not able to to get the props command in the terminal:
[https://github.com/Magisk-Modules-Repo/MagiskHide-Props-Config/blob/master/README.md#logs-etc](url)

**Comment by ossilator** [comment]
are you kidding me? i reported three separate issues that indicate a systemic problem, and you're closing this with no comment? somebody offering an approach to one of the issues is *not* an adequate justification, and not even something i asked for.

**Comment by topjohnwu** [comment]
You can get all detailed logging information from installing the debug canary builds, and obtain either Magisk logs (for the native side) and verbose logging for Magisk Manager (the app side). Complaining here with unfriendly and entitled comments like this does not help an open source program that you use for free.

**Comment by ossilator** [comment]
yeah, how dare i complain that your first interaction with me is showing me the finger.

quite fittingly, you seriously suggest to install a debug build to obtain essential error messages. in case you didn't know, debug builds are about identifying issues _in your code_, not about your code telling the user that something is wrong with their environment - the latter is generally understood to be an essential feature of high-quality software.

i suggest you learn something about usability, and rethink your attitude towards people who want to help you make your toy more polished (i don't have the impression that you really care about helping users, so i won't suggest that you work on that).

**Comment by SuperSandro2000** [comment]
Always wondered why there are debug builds.

**Comment by osm0sis** [comment]
Wait, debug builds are for debugging?

**Comment by Eudeferrer** [comment]
@ossilator....if you don't like the free software (Magisk) and what it does, you are free to write your own error-free one buddy. Rather than complaining, you should offer your own code that fixes things. You shouldn't point a gun at the hand that feeds you. If Topjohn got tired of your crap and threw in the towel on development of magisk, the entire rooting world-wide community would suffer. Stop demanding crap that you have no right to demand for on the first place. You never paid any money for this software. Topjohn was kind enough to make it available for free to us all. You should be grateful and stop demanding things.

**Comment by ossilator** [comment]
yes, i'm infinitely grateful for this software that had literally negative value to me, and for the disrespectful treatment i got for my suggestion how to improve things. i surely should shut up and suck it up, lest topjohn's fragile ego implodes and makes him quit.

**Comment by Eudeferrer** [comment]
Urging and demanding that someone spend endless hours of their personal time reviewing and doing a complete audit of the code to suit YOUR personal phones needs is irrational at best. For a great majority of us, Magisk has worked without flaw and has been a life-line to continue rooting or phones, something impossible without Topjohn's contributions to the community. Perhaps, you may have had a valid point somewhere in your argument but the way you ask and your choice of words was totally inappropriate. Furthermore, your continued sarcasm further shows your complete lack of gratitude for the contributions done by Topjohn. I await for YOUR future contributions to the rooting community when you yourself do what you expect others to do for you for free. Learn to code and YOU sir, do the "complete code audit" and then submit the corrections. Perhaps then, some of us would respect anything you say.

**Comment by percy-g2** [comment]
Sometimes end users get error and doesn't know how to use GitHub and get a solution. Debug build solves current user issues but there can be a better way to resolve this in a better way. Think about the solution rather than justifying the work. I have top most respect for @topjohnwu for his free open source project, but we as a open source community can help him improving this. Just saying, don't take my words in wrong way.

**Comment by ossilator** [comment]
@Eudeferrer:

so you find it irrational to make sure that a piece of software is robust, even when there are multiple pieces of evidence that it currently isn't. good to know.

if you put away your completely ridiculous expectation that anyone's contributions grant them extra credit to behave like a dick, and learn some basic perspective taking skills, you'll understand that my responses to the treatment here aren't all that unexpected.

i would also suggest that you do yourself the favor to learn something about your interlocutor before ridiculing yourself by making outlandish assertions based on bogus assumptions.

**Comment by percy-g2** [comment]
@ossilator it doesn't help your cause of reporting some issues with these type comment after you have already explained your issues properly in opening an issue. I understand owner closed it but you can still ask for proper solution instead of explaining each and everyone. Already one good old developer suggested him few things to improve upon on twitter, @topjohnwu will improve the debugging and reporting in release build in future when he gets time. So take some time off and see the development.

**Comment by Eudeferrer** [comment]
I do not intent of being an "interlocutor" of any kind as I did not have any of your issues and do not feel I need to defend anyone involved. As I previously pointed out, perhaps you may have had a point with your comment. However, your poor communicative skills made you look like a demanding idiot and a complete jerk. Of course everyone's would want software to be "robust" and perfect, but there is a way to ask for things/favors without demanding from someone to do a complete reviews at your will; specially when it involves their time. My assertions were far from bogus. I can clearly see with your persistence in this matter that selfishness is perhaps your most admirable quality.

**Comment by martyfender** [comment]
Did you provide any logs, as I had suggested, for topjohnwu to properly troubleshoot your issues? No you did not. He is not a mind reader. I have not seen you make any effort to do this, even minimally.
I can't believe the entitlement mentality of today. It kind of reminds me of a customer I had today in my electronics department. They thought I should drop everything and help them first over all of the other customers who had waited patiently, in turn, for help.

Every time I have posted bug reports here with logs, topjohnwu has been very quick to respond to me, even, in the case of my most recent report, where he could not reproduce my issue. In the past he has went above and beyond to fix bugs that I reported, as well as many other user here who take the time to give **proper** bug reports.

**Comment by robertosartori** [comment]
@ossilator  is actually right. We are talking about good UI or good logging for known features/issue. 
It is known that that feature needs support for namespaces, any programmer would expect to give the user notice in case of missing support from the kernel, just like you can get the 'No sim inserted' from your phone when calling someone instead of the Phone app just closing itself.

I repeat: there is NO NEW issue here to debug.

**Comment by robertoglxda** [comment]
@ossilator is actually right. We are talking about good UI or good logging for known features/issue.
It is known that that feature needs support for namespaces, any programmer would expect to give the user notice in case of missing support from the kernel, just like you can get the 'No sim inserted' from your phone when calling someone instead of the Phone app just closing itself.

I repeat: there is NO NEW issue here to debug, why are you guys insisting on this debug thing?

**Comment by ossilator** [comment]
thanks @robertoglxda , exactly my point.

on twitter @topjohnwu talks about obfuscated builds and stuff, yet "magiskhide enable" on the command line gives exactly the clear error message one would reasonably expect. there is just no coherent argument to be made why magisk manager shouldn't do this as well - it appears to be a simple omission.

as i ran into three such issues despite having interacted with the app only little, i concluded that there might be a pattern - which wouldn't be particularly surprising, as sloppy error handling is a common affliction of software, free or not. i thought it would be nice to spare the next sucker who runs into this the frustration, so i took the time to make a report, suggesting a way forward which i as a seasoned developer know to be the correct one. i was quite aware that the prospect of having to do a full audit wouldn't be received enthusiastically, so i made a strong recommendation to take it seriously nonetheless.

to anyone with a clue who's also paying attention it would have been clear from the first message that my device cannot possibly support magisk hide, _and that i know that_. from this follows directly that (for the time being) there is absolutely *nothing* to gain for me personally from these issues being addressed now. yet somehow people managed to conclude that i'm entitled, and "clearly see" that i'm selfish. what _i_ see is a mind-boggling display of poor reading comprehension, preconceptions, tribalism, and sheer arrogance. i'm quite aware that my condescending responses don't help, but i'm not the one who will de-escalate by returning more respect than he receives. sorry, not sorry.

**Comment by VivaLaAndroid** [comment]
The sense of entitlement commonly seen in today's development communities is not only blatantly disrespectful, obnoxious, rude and counterproductive, but also quite unsettling on a moral standpoint. Not only does such behavior equate to bad manners,  it reeks of a major character defect. In fact, let's look at the textbook characterization of Narcissistic Personality Disorder, per the DSM-5: a belief that he or she is special and unique; a demonstration of arrogant and haughty behaviors or attitudes; having a grandiose sense of self-importance; a lack of empathy; a sense of entitlement. 
It is these parasitic leeches -- these non-contributing sponges -- that have created such a volatile and negative atmosphere in development communities. They are the reason that, after six dedicated years at XDA and providing custom support for over a dozen Android based devices, I threw in the proverbial towel. Now don't get me wrong or construe my point as a stark overdramatization, there are going to be a-holes like that guy on every road in life. Great communities like XDA have become overly tolerant with such behavior and quite complacent with the sense of entitlement mentality as a whole. Forums and threads which exist as the result of a self-sacrificing sense of community have become commonplace for demanding jerks and disrespectful little punks who will never contribute anything except narcissistic vitriol and incoherent dictum from the school of troll ideology. Developers like Topjohnwu, Osm0sis, Chainfire... the list goes on ... are the heartbeat -- the driving force -- of the Android community. I have the utmost respect for individuals like these when, on a regular basis, developers are disrespected by jerks who use their work completely free of charge...and by the likes of a self-proclaimed know-it-all who obviously doesn't possess the rudimentary skills to port an up-to-date kernel for his Nougat ROM,. yet wants to condescend the coder and developer of the top rooting interface on the planet. 
Anyway, I've been loquacious to say the least, but I feel that jerks like this are slowly poisoning the atmosphere of this great community of brilliant minds.
