### ISSUE TITLE
CTS Profile Match : False on MIUI 8 7.4.27 custom

### ISSUE THREAD

**Issue by szamuka** [topjohnwu/Magisk#186]
I have CTS: false. How to fix it?

**Comment by fruhu** [comment]
What I write is actual for xiaomi phones, will it work on ported firmware of other phones - I do not know
First: on magisk 12 hidding works incorrectly on some devices, can be fixed by fixing or restarting the hiding daemon manually / by a module or third-party program
[Magisk12.0_Hide_fixed.zip](https://github.com/topjohnwu/Magisk/files/967717/Magisk12.0_Hide_fixed.zip)
Second: on variation xiaomi devices on a weekly firmware pass the test safetynet "out of the box" can not in principle. This, too, can be fixed, for this it is necessary to replace the fingerprint of the firmware, on the fingerprint from stable firmware. 
You can do this for example using a module, the ready module is exactly for mi5, for mi5s I will attach below.
Whether there is similar for other devices - I do not know, in general you will have to do it yourself (for this I attach the module from the mi5s).
[magisk-capricorn-safetynet-props-v3.zip](https://github.com/topjohnwu/Magisk/files/967723/magisk-capricorn-safetynet-props-v3.zip)
Now a little instruction how to do this:
1 Open this module in archiver, open the folder common, you need a file post-fs-data.sh
2 This is a text file and can be edited in any text editor with the exception of the standard notepad from Microsoft Windows.
3 In the lines

`$resetprop ro.build.description "xxx"`
`$resetprop ro.build.fingerprint "xxx"`
`$resetprop ro.bootimage.build.fingerprint "xxx"`

You replace the information, by analogy with the information from the module - on the information for a stable version of the firmware of your phone.
Where to get this information:
1 Assemble manually by file build.prop
or
2 View with a program, for [example](https://play.google.com/store/apps/details?id=org.freeandroidtools.root_checker) on stable firmware, or ask someone to provide this information

Attention, I can not predict how the incorrect data will behave in these fields, in the worst case there will be a bootloop, which can be corrected by removing the module / by reinstalling the magisk

**Comment by szamuka** [comment]
Is it possible for Redmi Note 3 and Redmi 3?

01.05.2017 1:36 PM "fruhu" <notifications@github.com> napisał(a):

**Comment by fruhu** [comment]
@szamuka Probably yes, but I can not guarantee, need to check on the device. And to do this, change this module for your device. I "played" with the mi5c module, as it turned out that the lines 
`$resetprop ro.build.description "xxx"`
`$resetprop ro.bootimage.build.fingerprint "xxx"`
in general, then do not need, in the module for myself, I deleted them.
I myself use the firmware from xiaomi.ee and for the current time the version that I use is -7.4.27, safetynet passed

**Comment by szamuka** [comment]
Is it patche for kenzo and ido?

01.05.2017 2:58 PM "fruhu" <notifications@github.com> napisał(a):

**Comment by fruhu** [comment]
The module attached to me is for capricorn, alas, I do not know the fingerprint of stable firmware for R3 and RN3 to write data to the post-fs-data.sh module

**Comment by szamuka** [comment]
I uninstall and want install and I havent root

1 maj 2017 3:04 PM "fruhu" <notifications@github.com> napisał(a):

**Comment by szamuka** [comment]
When I installed magisk v12 fixed then I haven't root
http://i.imgur.com/K1Zssxs.png

**Comment by szamuka** [comment]
When I reboot its ok

http://i.imgur.com/QuAgr6U.png

**Comment by fruhu** [comment]
If that - here a person assembles a universal [module](https://forum.xda-developers.com/apps/magisk/xiaomi-safetynet-fix-t3600431) for various models xiaomi, the module does what I suggested doing here
