### ISSUE TITLE
feature request: add support for magiskboot to dump dts from real machine

### ISSUE THREAD

**Issue by 99degree** [topjohnwu/Magisk#1914]
Hi,

Just post code to demo for enable dtc -I fs in magiskboot does. attached is the trial diff version RFC.

why do this is needed? due to a poorly written lk, m3note dtb is heavily overwritten/modified prior jump kernel. thus to the android image, resulting dtb might not the same as expected. so a handy tool to dump and verify it from real machine is a good thing.

the added code is not clean enough, but it is simple for inclusion. if possible, please include it in next version.

changes:
(1) dtc -I fs
(2) a potential fix for a bug at enum dev

output:

`
~ # chmod a+x ma*
~ # ./magiskboot dtb /sys/firmware/devicetree/base/ dtc /sys/firmware/devicetree
/base/
args: /sys/firmware/devicetree/base/
args: 1
args: 2
args: 3
/dts-v1/;

/ {
        #address-cells = <0x02>;
        #size-cells = <0x02>;
        compatible = "mediatek,MT6755";
        interrupt-parent = <0x01>;
`

I usually do with below:

`~ # ./magiskboot dtb /sys/firmware/devicetree/base/ dtc /sys/firmware/devicetree/base/  > wt6755.dts  `

regards.

[change.diff.txt](https://github.com/topjohnwu/Magisk/files/3717759/change.diff.txt)

**Comment by topjohnwu** [comment]
The dtb running on the device is always from somewhere in the boot image, in a separate partition, or split across DTBOs. You should try to find the correct place to extract the dtb, not reading from your device because that only works on your specific model. Most of the time, the firmware contains multiple device trees because there could be multiple small variations in the hardware of the same model
