### ISSUE TITLE
Feature request - [hide/unhide] checkbox for modules listed in Magisk Manager Downloads

### ISSUE THREAD

**Issue by Randulff** [topjohnwu/Magisk#195]
Hello and thank you the great work!

My suggestion, even if I think you might have it in plan or thought about it, is the following:

1. [Custom hide/unhide checkbox adjacent to the module] Let the user of Magisk hide/unhide modules that are listed in the Downloads menu. It will then be quicker to see if new and interesting modules have become available. As Magisk will grow, this issue will be even more requested as it takes time to go through the Downloads list. To the future, maybe hundreds of modules working with Magisk for one or another handset could be present.

2. [Automatic hide/unhide compatible checkbox in the settings menu] If you have a handset, lets say Samsung Note4 running Marshmallow, then all other modules for Nougat or Lollipop (if a Marshmallow version is available) is irrelevant, further all other modules specific for any other brand (One, Nexus (*), Sony ...) and irrelevant to any modules for specific Samsung models, lets say S7 Edge functionality.

This feature will require a checking routine towards a database of modules with a compatible variable [Yes,No]. *Further, if a user of a handset tries to install a module for Nexus and it works - as Nexus run pure(r) android, he could tick Compatible [Yes/No] in another checkbox adjacent to that module. The database thus could have an internal voting routine based on these responses to alter the default automatic compatible yes/no value for that specific handset. Multiple confirmed compatibility votes could trigger a publishing of a string variable to be written along with the description of the module in the Downloads list.

One way to start implementing the automatic feature could be to require such parameters to be supplied from the developer to become an official module. Alternatively the module starts out blank on compatibility and obtain its values by the internal database voting routine.

In itself, the automatic hide/unhide is a project in itself as a big file with all the options included with Magisk installment might be unpractical. Therefore, only the custom hide/unhide at first could be evaluated to implement and the automatic routine could be an idea for another module from independent developers. The automatic routine will result in a lower boundary for new users after time and reduce reports on crashes from incompatible installed routines. The voting system will help the developer to pinpoint areas for where to focus to get the module work on most possible handsets.

**Comment by topjohnwu** [comment]
Thanks for the suggestion! However, some of the features you've requested is not possible (at least currently). I do not own a server, so all Magisk repos are hosted on Github. The flexibility is limited, since not everything can be done through Github servers.  

A filter to filter models is not easy and impractical: how to determine a specific model? Using the model codename is not a good option, because for instance a module that works on modern Samsung devices, how can the module developer know all the models/variants Samsung has created?  

A filter to filter Android version is viable, because it is very clear and easy to distinguish between different Android versions by the API version code. I would put this into consideration.  

A custom hide list is also possible, it can be done in the Magisk Manager side, I will also put it into my TODO list.
