### ISSUE TITLE
The affect of "Core only mode" should be show at Modules and Download page

### ISSUE THREAD

**Issue by RikkaW** [topjohnwu/Magisk#1991]
Every few days there are noob users who enable "Core only mode" and complain like #1990.

It's simple to solve the problem, add a card with "Core only mode enables, all modules are invalid" at Modules and Download page.

I have learned the UI is under reworking form another issue, so I create this issue only as a suggestion.  <del>And almost every part of the current UI has problems, I'm afraid that I can't stop myself to change other parts if I start to change this.</del>

**Comment by Mister-Hope** [comment]
I don't think I closed it in #1990, also, I opened it and did uninstall. When installed again, I still found it is opened. 
It is closed by default in magiskV19(at least 19.3-). If I am not misunderstand ing something, you silently made a breaking change here. 
So I am also suggesting to marked it at the release page.

**Comment by Mister-Hope** [comment]
Wow, I just found it's your thread,Mr.Nobody @RikkaW

**Comment by diareuse** [comment]
"Core mode" will be rebranded to "Safe mode" in the redesign. This message will appear in Modules screen in order to inform users about having "Safe mode" enabled.
![image](https://user-images.githubusercontent.com/5982859/67878926-63a6dc00-fb3c-11e9-8ad6-de8e942c4792.png)

Is there anything you'd like to add @RikkaW ?
