### ISSUE TITLE
Missing Work Profile Apps

### ISSUE THREAD

**Issue by adi90x** [topjohnwu/Magisk#2011]
Hello,
Firstable thanks a lot for this very nice development !
Just a quick question, would it be possible in MagiskHide to list not only user 0 Apps but also for other user ? Especially User 10 which seems to be the user use by Android Work Profile. 

I guess it is just a listing issue, as hiding work perfectly if you install it as user 0 and hide it.

Regards,

**Comment by chilliger** [comment]
Seems to be connected to #1888

**Comment by martyfender** [comment]
"Install Magisk Manager in the work profile, and allow it to gain root access in the device owner profile."

**Comment by chilliger** [comment]
Is this commit somehow an improvement to this issue? #2060

**Comment by adi90x** [comment]
@chilliger : how can I test this commit ?

**Comment by l0ud** [comment]
I can confirm that no apps from work profile are visible in magisk hide. Phone integrity violation is detected by MS Apps in work profile and access is locked.

**Comment by wokhan** [comment]
> That is not possible, Work Profile is handle exclusively by my company, so I can't install what I want in it, what is really abnormal is that app only in Work Profile is not shown in MagiskHide, but when also install in Personal Profile, then root is hide on both Profile.

In fact you can... Either using adb or through a root shell (with pm install --user [work profile id] package.apk)
I know it was an old statement, but someone might find my post useful anyway and the issue is still open so...

@topjohnwu It looks like Magisk Hide in the device owner profile takes precedence over whatever is set in Magisk Hide in the work profile. Am I wrong? Do you know why we have to install and magisk-hide apps in both profiles for this to work?

**Comment by misterpyrrhuloxia** [comment]
#2181
