### ISSUE TITLE
[Vote] Installing Modules in Bulk

### ISSUE THREAD

**Issue by mikesew1320** [topjohnwu/Magisk#2036]
Many uers download modules from the repo and place them to their storage device for another time, I am from one of them I always place the modules that I have downloaded from the Magisk Modules repo, from xda and ... because I can easily install them from my sdcard if I lost one of them or after resetting the data on my device and upgrading my device ROM.

So, Then I started to think on my mind...

Is it possible to add Multiple Modules installation feature into Magisk Manager like what TWRP have.

If not, why?

**Comment by diareuse** [comment]
The installation process is not this versatile - input implies that there's exactly >one< zip file to install, so installing modules in bulk is not supported because of that.

I can see this being very useful and eventually implemented. However not anytime soon, firstly I need to finish the redesign.

---

I'd would be super awesome if users voted with 👍 on your OP so let me know whether I should prioritise this among other improvements.

**Comment by alexa-v2** [comment]
Unsure if this is related, but I'd like to see the ability to flash modules without directly opening the manager, eg magisk manager registers itself as a handler for .zip files so I can tap to it from a file manager, and magisk manager offers to flash (with a confirmation dialogue, eg "app" is requesting you to install a magisk module! Do you wish to continue?"

Should I open another issue for this though?

**Comment by diareuse** [comment]
That is completely different feature, there should be completely different issue for that :) thanks

**Comment by topjohnwu** [comment]
This might come in the future, we'll see
