### ISSUE TITLE
safenet false

### ISSUE THREAD

**Issue by diiegg** [topjohnwu/Magisk#2057]
I have magisk 20.1 and manager 7.0.4,

I get cts profile and basicintegrity false 

I have installed edexpose module running Android 9+ on a OnePlus 5t

**Comment by bmg002** [comment]
I am pretty sure as soon as you put xposed (or any additional flavor of it like edexpose), you will fail safetynet.

**Comment by diiegg** [comment]
it's any way to pass the safenet? it just happened with the last update of magisk.

**Comment by qnorsten** [comment]
This is an edexposed issue rather than a magisk issue. 
Saftey net started detecting edxposed a few days ago (I am surprised it took them this long) 
For more info see this issue https://github.com/ElderDrivers/EdXposed/issues/386 . That also contain a fix that works for now. 

If you ever want to know if it is a magisk error or not, disable edxposed module and reboot. If you still fail saftey net there is a non edexposed related error.

**Comment by topjohnwu** [comment]
#1152
