### ISSUE TITLE
Magisk Causes OnePlus 7 Pro Vendor Software to Fail

### ISSUE THREAD

**Issue by zedseven** [topjohnwu/Magisk#2059]
Installing Magisk on a brand-new OnePlus 7 Pro causes the OS to act up - namely the Wi-Fi stops working altogether (turns off and turning it on in settings leads it to flick the switch off again) and system apps like the camera freeze after 1-2 seconds of use.

I have tried installing Magisk v20.1 and v19.4 as well as [pre-patched versions of the OnePlus boot image with Magisk](https://forum.xda-developers.com/oneplus-7-pro/how-to/magisk-patched-boot-image-oneplus-7-pro-t3964345) - all have an identical effect.

Using `adb logcat` while Android is running (on the home menu, fresh, patched install of OxygenOS 21(?), Android 10, I get the following repeated errors in the logs:

```
11-09 01:44:51.867  1191  1191 E /vendor/bin/adsprpcd: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/adsprpcd.c:48:adsp daemon will restart after 25ms...
11-09 01:44:51.872  1192  1192 I /vendor/bin/adsprpcd: remote_handle_open: Successfully opened handle 0x60 for '":;./\createstaticpd:audiopd on domain 0
11-09 01:44:51.873  1192  1192 E /vendor/bin/adsprpcd: Error 0xffffffff: apps_dev_init failed for domain 0, errno Transport endpoint is not connected
11-09 01:44:51.873  1192  1192 E /vendor/bin/adsprpcd: Error 0xffffffff: open_dev (-1) failed for domain 0
11-09 01:44:51.874  1192  1192 E /vendor/bin/adsprpcd: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/adsprpcd.c:48:adsp daemon will restart after 25ms...
11-09 01:44:51.896  1191  1191 I /vendor/bin/adsprpcd: remote_handle_open: Successfully opened handle 0x63 for '":;./\attachguestos on domain 0
11-09 01:44:51.896  1191  1191 E /vendor/bin/adsprpcd: Error 0xffffffff: apps_dev_init failed for domain 0, errno Transport endpoint is not connected
11-09 01:44:51.896  1191  1191 E /vendor/bin/adsprpcd: Error 0xffffffff: open_dev (-1) failed for domain 0
```

For the record, the root itself works fine, as well as Magisk Manager. I can use `adb shell` and `su` in without a problem.

From my relatively uneducated perspective, I suspect it has something to do with Magisk not correctly redirecting/masking vendor stuff - I'd appreciate some help with a solution. I've spent a few hours looking online for similar issues, but I haven't found anyone else with this problem.

**Comment by zedseven** [comment]
I was able to fix the issue by patching a copy of OxygenOS myself according to the instructions in [the above link](https://forum.xda-developers.com/oneplus-7-pro/how-to/magisk-patched-boot-image-oneplus-7-pro-t3964345) - I'm not sure what differences could have existed, but I had to download the full OS img, extract the `boot.img` from the `payload.bin`, and patch it using the beta patcher built into Magisk Manager.

I'm leaving this issue open as clearly an issue still exists with the provided patch method and I wouldn't consider my solution to be a permanent fix.

**Comment by topjohnwu** [comment]
If the official way to install Magisk is working properly, where is the issue? Apparently this means there is nothing wrong on my side.

**Comment by zedseven** [comment]
Because following [the provided instructions](https://magisk.me/root-oneplus-7-pro/) and using the installer ZIP file was what I did all but the last time. @topjohnwu

**Comment by ikelos** [comment]
Magisk: 20.1
Phone: OnePlus 7
OS: Oxygen 10.0.2

I ran into this this evening.  I updated my OnePlus 7 to 10.0.2 by manually downloading the update, extracting the payload.bin, patching the boot.img using magisk and then flashing that to the boot partition.  I noticed that the boot animation lasted much longer than with the stock install, and when it booted back up wifi would not work and I saw the `/vendor/bin/adsprpcd` errors as described above (and also in a post from March on XDA).  This is the same procedure I followed for 10.0.1, which worked just fine.

Something I noticed is that the repacked boot.img was only 50Mb rather than 100Mb, however I don't think this is part of the problem since this was also the case with 10.0.1 (which worked fine) and I also tested just the magiskboot unpack/repack steps on the ramdisk.cpio and even though it also produced a 50Mb image, that one seemed to boot fine (and allowed wifi, etc).  Booting either the unpacked repacked boot.img, or the original, allowed wifi to work and gave no adsprpcd errors.  Flashing back to the magisk packed one showed the symptoms again.

I flashed the previously patched magisk kernel (10.0.1) onto the new system.  I had expected it to fail, but provide more data.  It failed in exactly the same way as the 10.0.2 (so ran, but no wifi and the adsprpcd errors), it appears that it's something about the system image, rather than the boot image, based on patching in magisk, which is causing the new problems.

I'm not sure how to further debug this, but happy to help if I can?

Link to [Full OTA](https://otafsg1.h2os.com/patch/amazone2/GLO/OnePlus7Oxygen/OnePlus7Oxygen_14.E.22_GLO_022_1911070324/OnePlus7Oxygen_14.E.22_OTA_021-022_patch_1911070324_3cb7a5b3c35.zip) used

**Comment by ikelos** [comment]
I had these errors recently with a OnePlus 7 when I updated to 10.0.2 but it turned out to be either the wrong kernel file or the canary version of magisk manager.

**Comment by Didgeridoohan** [comment]
> Because following [the provided instructions](https://magisk.me/root-oneplus-7-pro/) and using the installer ZIP file was what I did all but the last time. @topjohnwu

Just want to point out that the linked website has absolutely nothing to do with official Magisk. Everything official is found right here on [Github](https://topjohnwu.github.io/Magisk/) and on XDA.
