### ISSUE TITLE
Magisk needs to be force-closed to check biometric setting availability

### ISSUE THREAD

**Issue by Jon8RFC** [topjohnwu/Magisk#2088]
https://youtu.be/iwFa24zU1Ns
(no worries...I changed my password to "magisk", specifically to record this video)

When enabling the app sign-in and payments option in Settings>Security>Face unlock:
https://imgur.com/a/yZuMmsa
Magisk won't recognize the change and must first be forcefully closed to have it check if the setting has been enabled.

Maybe it's not quite a bug, but a feature request for Magisk to check for the change whenever the Magisk settings are opened.

Pixel 4 Google Edition
Build QD1A.190821.007.A3

**Comment by topjohnwu** [comment]
@Jon8RFC Android does not have a callback/event for changes with Biometric settings. The current implementation does not recreate fragments everytime you switch to a section due to performance. I don't think it is worth recreating the whole settings page every time just to make this small settings in sync
