### ISSUE TITLE
Magisk Nougat support

### ISSUE THREAD

**Issue by crunk1** [topjohnwu/Magisk#21]
I looked around to see if there are requests for this anywhere else, but couldn't find anything. I'm sure you have had others asking you for this, but I figured I'd file a formal issue.

I have a Pixel XL running 7.1.1.
I tried sideloading Magisk-v9 via TWRP adb sideload. The install fails after mounting /system, /data, /cache, etc. It looks for /system/build.prop which doesn't exist on my phone at the moment. I got past this step by `cp /system/default.prop /system/build.prop`, however, the install still fails saying that Magisk is meant for Lollipop 5.0+.

**Comment by Lrs121** [comment]
Im pretty sure the issue lies with the new partition structure for the background updates and not to do with android 7.1.1. If this was working for you on 7.1.0 then i might be wrong.

some reading related to how chainfire got supersu working.
https://plus.google.com/+Chainfire/posts/CBL8pnKtA8F
https://plus.google.com/+Chainfire/posts/24xhJN724HG

**Comment by crunk1** [comment]
I didn't try it on 7.1.0.

**Comment by topjohnwu** [comment]
The issue is the Pixel device. Magisk has been one of the best compatible rooting method for Nougat.
I will have access to Pixel XL soon, please stay tuned.
