### ISSUE TITLE
Version 20.1 cannot install the magic module

### ISSUE THREAD

**Issue by maoyaotang1** [topjohnwu/Magisk#2106]
sp9853i Android 8.1 Version 20.1 cannot install the magic module  Whether the magick manager brushes in magick.zip to restart or show that Magick is not installed

**Comment by wilsonhlacerda** [comment]
This happened to me yesterday with Lineage 16, Android 9, on old Samsung device.  I've never had this kind of problem earlier.  What happened and how I solved it:  

I was ok on newest Canary (cause I was testing some stuff).  I completely uninstalled it with Magisk Canary Uninstaller.  And even regular Magisk Uninstaller,  UnSU by osm0sis, flashed stock boot, at the end formated System and flashed ROM/Gapps again. All that because every time I had tried to have stable Magisk 20.1 it failed (flash without error but companion version Magisk Manager only says "Magisk not installed" ).  

What solved my problem was to flash Magisk v19.4 zip. That was fine. And then updated it to v20.1 using Magisk Manager.
