### ISSUE TITLE
Sony Xperia - Stuck at sony logo on Slot B

### ISSUE THREAD

**Issue by MartinX3** [topjohnwu/Magisk#2129]
It happens only if I install magisk on slot B
Slot A works without problems.

The symptom is, that the phone is stuck at the Sony logo (before the ROM animation).

I always get a pstore which sadly everytime only contains a partially corrupted console-ramoops-0.log.

[recovery.log](https://github.com/topjohnwu/Magisk/files/3927825/recovery.log) (fresh after the installation)
[magisk.log](https://github.com/topjohnwu/Magisk/files/3927847/magisk.log) (i rebooted to twrp to get it)
[console-ramoops-0.log](https://github.com/topjohnwu/Magisk/files/3927786/console-ramoops-0.log) (i rebooted to twrp to get it)

If there is more I can do, please advise me.
I followed the following links, but have no clue if there is a better source of logs somewhere.
https://www.didgeridoohan.com/magisk/MagiskHelp
https://forum.xda-developers.com/apps/magisk/dev-magisk-canary-channel-bleeding-edge-t3839337

**Comment by topjohnwu** [comment]
Sorry, but this doesn't make any sense at all. If Sony has some weird issues with its A/B partitioning scheme in the bootloader, then there is nothing Magisk can fix about that

**Comment by MartinX3** [comment]
It boots fine without magisk, @topjohnwu

**Comment by kholk** [comment]
If Android works fine on Xperia devices with a clean boot.img on both A and B slots, then I wouldn't say that the issue is the Sony bootloader.

What is not working here is Magisk only when booting on slot B, so, since the only thing that gives issues is Magisk, then, with all respect, I'd say the the problem happens to be in Magisk, not in the Sony bootloader, as that's totally unrelated.
