### ISSUE TITLE
Support Creating Boot Images with Safe Mode Enabled

### ISSUE THREAD

**Issue by topjohnwu** [topjohnwu/Magisk#2131]
As currently there is no easy way to let users wipe out incompatible Magisk Modules that causes bootloop, and more and more devices no longer have a functional custom recovery that decrypts `/data`, a mechanism to create a rooted but no-modules-loaded Magisk installation is necessary for a smooth user experience to get out of the bootloop situation.

This feature is currently planned to roll out along with @diareuse's Magisk Manager redesign, so it will be a joint collab effort to make this happen. Please stay tuned for more updates in the future.

P.S. Core Only mode will be rebranded as Safe Mode in the future as the old name is actually pretty confusing.

**Comment by nttan2805** [comment]
#2131

**Comment by alvinhochun** [comment]
Since the option to create an image with safe mode / core only mode enabled has not yet been implemented, what would be the easiest way to create such an image now?

Since I already have a setup to build Magisk from source and can patch a boot image with it, am I right that just changing `bootstages.cpp` to replace the checks for `DISABLEFILE` with hard-coded conditions would be enough?

**Comment by krokofant** [comment]
@alvinhochun That is my impression based on a guide from xda https://forum.xda-developers.com/pixel-3a-xl/themes/magisk-modules-disabler-booting-magisk-t3976625

**Comment by H4NG-MAN** [comment]
> As currently there is no easy way to let users wipe out incompatible Magisk Modules that causes bootloop, and more and more devices no longer have a functional custom recovery that decrypts `/data`, a mechanism to create a rooted but no-modules-loaded Magisk installation is necessary for a smooth user experience to get out of the bootloop situation.
> 
> This feature is currently planned to roll out along with @diareuse's Magisk Manager redesign, so it will be a joint collab effort to make this happen. Please stay tuned for more updates in the future.
> 
> P.S. Core Only mode will be rebranded as Safe Mode in the future as the old name is actually pretty confusing.

**Comment by zgfg** [comment]
Unfortunately, this method with putting overlay.d with a shell script to the ramdisk directory in the image does not work for all devices.
At least not working for Xiaomi Mi 9T, but due to the layout of MIUI boot.img, doubt that it could work on the other Xiaomi devices as well.
Reported at:
https://forum.xda-developers.com/showpost.php?p=82438847&postcount=40
discussion (with the author of the method on the subsequent page), with no solution yet

Btw, proposed an alternative solution (and easier for users than the need for a special Core Only Magisk installation) as the Issue #2756

**Comment by topjohnwu** [comment]
a5d7c41d209527fe7b45a2ef7d031add9b6fad24

**Comment by linuxandria** [comment]
Nice work @topjohnwu didn't even think of that but it's along the lines of my idea anyhow 🎉
