### ISSUE TITLE
Samsung Account

### ISSUE THREAD

**Issue by alroy214** [topjohnwu/Magisk#2180]
Since rooting my Galaxy S10 Android 10, I get this persistent Samsung Account notification, I can't log in cause I have root and every time I remove it, it shows and loops again
![Screenshot_20191226-043500](https://user-images.githubusercontent.com/31711733/71454383-3ae83f00-2799-11ea-8822-d35db0697c2e.jpg)
![Screenshot_20191226-043609_Chrome](https://user-images.githubusercontent.com/31711733/71454387-4176b680-2799-11ea-8cfd-9f278aebfa36.jpg)

**Comment by dcoolArne** [comment]
I have a rooted s9, I had this error in the past but it was not directly related to rooting. After a reset and fresh root I am now able to sign into my account. But I think if I clear the dalvik cache it stops working.

**Comment by topjohnwu** [comment]
Sorry, but I don't think this is related to Magisk itself. You might want to ask on XDA for more help regarding this issue

**Comment by bubbleguuum** [comment]
I have the same issue on my SGS9

**Comment by alroy214** [comment]
> Sorry, but I don't think this is related to Magisk itself. You might want to ask on XDA for more help regarding this issue

I think if I ask they will just redirect me to here, the problem only happens when booted into Magsik rooted mode

**Comment by alroy214** [comment]
> I have a rooted s9, I had this error in the past but it was not directly related to rooting. After a reset and fresh root I am now able to sign into my account. But I think if I clear the dalvik cache it stops working.

So a fresh root did help you out? So it is clearly directed to rooting or I'm completely lost

**Comment by alroy214** [comment]
![Screenshot_20200108-001254_Samsung account](https://user-images.githubusercontent.com/31711733/71933908-e20ea280-31ab-11ea-9678-2aaf1e4730c3.jpg)

**Comment by alroy214** [comment]
This isn't a safetynet issue as when EdXposed is disabled, passes safetynet but fails to sign in, does sign in on non-rooted mode but still blocks functionality and spams on rooted mode

**Comment by bubbleguuum** [comment]
I have retrieve the logcat corresponding to that "Processing failed" toast and it seems to be caused by an  java.security.UnrecoverableKeyException (see attached logcat) itself caused by  "android.security.KeyStoreException: -62". When you Google that error -62 you find this [StackoverFlow post](https://stackoverflow.com/questions/58999536/android-security-keystoreexception-62) which says that it should not happen and something is broken...

This is definitely caused by rooting which makes something fail here. You can find a few XDA post mentioning that "Processing failed" error but with no solution to workaround it, making logging to a Samsung account with Magisk impossible.
[samsung_fail3.txt](https://github.com/topjohnwu/Magisk/files/4032953/samsung_fail3.txt)

**Comment by alroy214** [comment]
@bubbleguuum but it was possible on the Android 9 (pie) so it's not impossible, @topjohnwu can you explain the error? Like mentioned above still can't find a fix, as Samsung Account itself shouldn't be able to be visible during hide or at least past it before

**Comment by alroy214** [comment]
@bubbleguuum I solved the problem with the fallowing steps: Install a custom rom (beyoned 6.2), install a custom kernel (nemsis v4), reboot twice, install "no device check" xposed module (yes that one from 2015), clear cash from twrp, done, log in and have a small happy dance c:
