### ISSUE TITLE
Can't remount /system to RW

### ISSUE THREAD

**Issue by Jomme5** [topjohnwu/Magisk#2199]
Hi, 
I want to move binaries from` /data/app` to `/system/app`. My data-partition is almost full, but I have still 1.5GB on my /system partition. Therefore I want to move the most-used apps to /system.
Nevertheless can't mount /system/app in RW.
After `mount -o remount,rw /system` I got this:
`'/dev/block/platform/soc/7824900.sdhci/by-name/system' is read-only`

Neither does Module Magisk Systemize the trick, because systemize puts only a symlink in the /system/app partition without moving the binaries from /data to /system.

Solution?

**Comment by Didgeridoohan** [comment]
Github issues is not the place for general troubleshooting and asking for help. You've got XDA for that...

For some info on why you can't mount /system rw, take a look here:
https://didgeridoohan.com/magisk/Magisk#hn_Cant_edit_system_files

Then please close this issue so that John doesn't have to.

**Comment by alexa-v2** [comment]
You can script this on boot, have said binaries moved automatically. It's be just as effective because the system doesn't know the difference
