### ISSUE TITLE
Prevent kernel from blocking Magisk modules 

### ISSUE THREAD

**Issue by Paget96** [topjohnwu/Magisk#2202]
Seems like some uneducated developers does some stupid updates on their kernels:
https://github.com/YaroST12/RAPHAEL_Kernel/blob/4c52097cbde31e9360cadf6f8f2732685dc880c4/fs/file_blocker.h

Even worse thing, newly baked kernel developers are just cherry pick things blindly. So stupid idea to block job by someone else.

**Comment by alexa-v2** [comment]
This would be extremely hard to implement

What are you supposed to look for? What if they created something new that breaks something? What if the kernel does it in a different way? There's too many variables to deal with here

**Comment by Paget96** [comment]
> This would be extremely hard to implement
> 
> What are you supposed to look for? What if they created something new that breaks something? What if the kernel does it in a different way? There's too many variables to deal with here

The last time I took a look at it, it was breaking processes who contains a string in a name, well for script it'll be a file name, for app it'll be a package name, now it simply hide a files from our modules, and it cannot be triggered on boot.

Here is one of the previous (their blocker went trough several phases)
https://github.com/abdoi94/kernel_xiaomi_sm8150/commit/9f5e69591d9b6c070cea3b1dddc70fa3d93a064d

> Added a preset of files to hide to render lspeed and fde.ai modules useless.
This is for laughing, what, you are making my project useless even if it's not... shame on you

**Comment by alexa-v2** [comment]
I'm not suggesting that kernel development isn't getting stupid and wreckless, I'm just asking how in the world is magisk supposed to deal with everything they could have done?

**Comment by Paget96** [comment]
> I'm not suggesting that kernel development isn't getting stupid and wreckless, I'm just asking how in the world is magisk supposed to deal with everything they could have done?

Well now it's not just problem for modules, those kernel devs actually block the stuff of Magisk property, isn't it?

There are a lot of things that should be done, instead of having all the modules files in a dir, we can use a sqlite or something else to keep the files what should be triggered on boot, there are so many ways.

**Comment by squabbi** [comment]
If the kernel hides those files and Magisk is able to keep track of what files are supposed to be triggered on boot, etc. 

All Magisk could do is put up a message saying that someone/something has tampered with loading Magisk modules, or to an extreme, put the phone in a bootloop?

I'm just thinking if it's even possible for Magisk to override or ignore a function like that in the kernel.

I don't know much about the kernel/bootstages of Android, but this is interesting.

**Comment by YaroST12** [comment]
> Seems like some uneducated developers does some stupid updates on their kernels:

You can't even write a cpu detection algorithm.

**Comment by THEBOSS619** [comment]
> > Seems like some uneducated developers does some stupid updates on their kernels:
> 
> You can't even write a cpu detection algorithm.

You can't even upstream a kernel 🤣

**Comment by YaroST12** [comment]
![IMG_20200103_113547_149](https://user-images.githubusercontent.com/26440429/71714016-30731880-2e1d-11ea-95d9-0a163d926238.jpg)


> > > Seems like some uneducated developers does some stupid updates on their kernels:
> > 
> > 
> > You can't even write a cpu detection algorithm.
> 
> You can't even upstream a kernel

**Comment by aiamuzz** [comment]
> > Seems like some uneducated developers does some stupid updates on their kernels:
> 
> You can't even write a cpu detection algorithm.

@YaroST12 ... forget about writing an algorithm to detect something ... i may not be able to just read one ...

but of i have understood ... seems some dev's have coded stuff that'll block certain things that others may want to use !!!

@YaroST12 ... assuming you are that dev ... shouldn't you be explaining/justifying why you have blocked some parameter rather then playing a condescending tone ?

**Comment by YaroST12** [comment]
> shouldn't you be explaining/justifying why you have blocked some parameter

Lspeed, nfs and fde are not providing sources for most of their tweaks so how do I know what they are tweaking?

**Comment by Paget96** [comment]
> > shouldn't you be explaining/justifying why you have blocked some parameter
> 
> Lspeed, nfs and fde are not providing sources for most of their tweaks so how do I know what they are tweaking?

L Speed is open sourced. Everything is visible

**Comment by YaroST12** [comment]
> Everything is visible

https://github.com/Magisk-Modules-Repo/lspeed/blob/master/app/LSpeedManager-v1.6.apk

Huh.

**Comment by YaroST12** [comment]
I hope you guys realize that you are the ones who promoted the blocker. Without you guys it'll be in 2-3 kernels at most.

**Comment by Paget96** [comment]
> > Everything is visible
> 
> https://github.com/Magisk-Modules-Repo/lspeed/blob/master/app/LSpeedManager-v1.6.apk
> 
> Huh.

Just simple app which doing sh on a module to execute it's parts.

**Comment by aiamuzz** [comment]
now this is what i call a healthy discussion ...

**Comment by YaroST12** [comment]
> > > Everything is visible
> > 
> > 
> > https://github.com/Magisk-Modules-Repo/lspeed/blob/master/app/LSpeedManager-v1.6.apk
> > Huh.
> 
> Just simple app which doing sh on a module to execute it's parts.

And ads.

**Comment by THEBOSS619** [comment]
> > > > Everything is visible
> > > 
> > > 
> > > https://github.com/Magisk-Modules-Repo/lspeed/blob/master/app/LSpeedManager-v1.6.apk
> > > Huh.
> > 
> > 
> > Just simple app which doing sh on a module to execute it's parts.
> 
> And ads.

Where? Please define ads.. and no I won't ask Google 😁

**Comment by YaroST12** [comment]
> > > > > Everything is visible
> > > > 
> > > > 
> > > > https://github.com/Magisk-Modules-Repo/lspeed/blob/master/app/LSpeedManager-v1.6.apk
> > > > Huh.
> > > 
> > > 
> > > Just simple app which doing sh on a module to execute it's parts.
> > 
> > 
> > And ads.
> 
> Where? Please define ads.. and no I won't ask Google

I have no idea.
![IMG_20200104_014622_550](https://user-images.githubusercontent.com/26440429/71753591-11639d80-2e94-11ea-96ce-559f3b82994c.jpg)

**Comment by feravolt** [comment]
### This will be a long read. 
The situation is so childish. Not even gonna make a dialog with anybody here, just wanna left my opinion since my creation ([FDE.AI](https://play.google.com/store/apps/details?id=com.feravolt.fdeai)) is under BLOCK too.

I stayed aware from this situation due to one day mr. @YaroST12 came in my support group in telegram, called me faggot for nothing, calling my creation "tweaks from 2011" in git and asking for source code - I don't even know him & never talked with him before. So I thought this guy is just another retard which wants to hype or smth and I don't wanna even bother with him. Until today. I'm sorry for sharing this pic, but people should know his personality. Niko was'nt offencive to him.

![photo5224454831274569226](https://user-images.githubusercontent.com/2546305/71760228-7b0b9800-2ee4-11ea-95b1-baffb619f60a.jpg)

I admit that there were issues on some k20pro devices after installing old (v5.3 i guess) version of FDE due to changing EXT4 mount flags which lead to various problems with storage further. As soon as I find out this issue I immediately uploaded new version of FDE which detects device's board and if it's raphael (k20pro) - doesn't applies ANY storage/IO related tweaks. I also created troubleshooting group to help users which had issues afterwards (~20 people). I'd like to highlight few things from this k20pro problem:
- Almos all users who get problem, got their devices from china (non-global version) with unoficially pre-unlocked bootloader & global rom. (what kind of warraties they want when buy device with unofficially unlocked bootloader?)
- This problem happens ONLY on SOME of k20pro devices. Some k20pro were using same FDE versions without 0 issues. And this issue at all happened only on this device - none of UFS 2/3 storages never suffered from this ever before. 
- Issue **never** happened before on any device since 2015 (FDE born year).
- This problem was not fixable by EDL flash

_In conclusion from all theese highlights i guess that there were a batch of k20pro which got poor quality internal memory. That's it. A healthy internal storage should not die due to changed FS mount flags. I also put a disclaimer on my own product that i provide no warraties for anything, despite this tried my best at helping & troubleshooting the issue. We even achieved some positive results for some users. Even though i believe a problem could appear even without FDE in a matter of time. (it really did appeared - i saw reports of bricked devices due to this or that reason) Almost half-year gone since that k20pro issue and no new issues happening with newer FDE versions on k20pro's due to i added _raphael_ board check._

### To the topic
**Today** got 1 star rating for my app on google play due to user buys my app and it just doesn't start tue to **THIS BLOCK**. And user don't even knew about this block due to some ROM devs blindly inline this kernel or cherry-pick that blocking shet in their kernels..

I understand that it's up to **user** to install that kernel or not, but at the same time it's up to **USER** to decide using any tweaker app or not. I never said my users don't use this or that kernel. Instead I tell them to use custom kernels if possible because they may extend the features supported by FDE. **So why should I suffer now from this?**

Talking personally - I am a kernel developer for completely different devices since 2012 (not all sources are open due to i worked for a company) and I at least know how to tune things. The idea of FDE was to extend my tweaks partially beyond my custom kernels and let any Android device users taste my vision of tweaking OS. FDE since 2015 was a companion for my custom ROM & kernel and lately became a fully independent universal project. Why I say I'm a kernel dev? Because I always believed that custom kernel is about **EXTENDING** features, not BLOCKING them.

If you block things because you can't see it's source code, why not blocking most of the other apps from Google Play or even Google Play services? _They are closed source and do tune OS too._ My app was checked via various analyses from Google before it was pushed to public. If app is on Google play - it's safe and users are aware of risks (if any).

My personal opinion is that this blocking shet is non-democratic to end user, especially when user doesn't even know about this block.  Situation is childish and i see this all as a pure hype.

Thanks & Cheers.

[FeraVolt.](https://github.com/feravolt)

**Comment by YaroST12** [comment]
I asked you to share which exact "tweaks" caused devices to malfunction in your 4pda thread, you didn't reply. That's when I started working on the blockers because I knew that you most likely won't share any info.



> Niko was'nt offencive to him.

You know that's not true. Niko was shifting blame on me and device tree creators for **your** fuckup (which you can see in the last message on your pic)

You are suffering from my blocker, I'm suffering from your optimisers and your lovely friends, asking me to help them with their bricks.

**Comment by Paget96** [comment]
> I asked you to share which exact "tweaks" caused devices to malfunction in your 4pda thread, you didn't reply. That's when I started working on the blockers because I knew that you most likely won't share any info.
> 
> > Niko was'nt offencive to him.
> 
> You know that's not true. Niko was shifting blame on me and device tree creators for **your** fuckup (which you can see in the last message on your pic)
> 
> You are suffering from my blocker, I'm suffering from your optimisers and your lovely friends, asking me to help them with their bricks.

We don't need to act against each other, much better is to work all together like a healthy community. We should support and help each other.

**Comment by celtare21** [comment]
> > I asked you to share which exact "tweaks" caused devices to malfunction in your 4pda thread, you didn't reply. That's when I started working on the blockers because I knew that you most likely won't share any info.
> > > Niko was'nt offencive to him.
> > 
> > 
> > You know that's not true. Niko was shifting blame on me and device tree creators for **your** fuckup (which you can see in the last message on your pic)
> > You are suffering from my blocker, I'm suffering from your optimisers and your lovely friends, asking me to help them with their bricks.
> 
> We don't need to act against each other, much better is to work all together like a healthy community. We should support and help each other.

No real dev who respects himself even 1% will ever work with people like you.

**Comment by THEBOSS619** [comment]
> > > > > > Everything is visible
> > > > > 
> > > > > 
> > > > > https://github.com/Magisk-Modules-Repo/lspeed/blob/master/app/LSpeedManager-v1.6.apk
> > > > > Huh.
> > > > 
> > > > 
> > > > Just simple app which doing sh on a module to execute it's parts.
> > > 
> > > 
> > > And ads.
> > 
> > 
> > Where? Please define ads.. and no I won't ask Google
> 
> I have no idea.
> ![IMG_20200104_014622_550](https://user-images.githubusercontent.com/26440429/71753591-11639d80-2e94-11ea-96ce-559f3b82994c.jpg)

You call this an ads? Come on! 🤦‍♂️

**Comment by YaroST12** [comment]
> **Today** got 1 star rating for my app on google play due to user buys my app and it just doesn't start tue to **THIS BLOCK**.

Mind sharing a link to this 1 star review? The latest 1 star review I see is from 26th of November :)

**Comment by THEBOSS619** [comment]
> I asked you to share which exact "tweaks" caused devices to malfunction in your 4pda thread, you didn't reply. That's when I started working on the blockers because I knew that you most likely won't share any info.
> 
> > Niko was'nt offencive to him.
> 
> You know that's not true. Niko was shifting blame on me and device tree creators for **your** fuckup (which you can see in the last message on your pic)
> 
> You are suffering from my blocker, I'm suffering from your optimisers and your lovely friends, asking me to help them with their bricks.

Well.. then I guess your kernel doesn't work/developed correctly if your users are suffering from optimisers... don't just put the blame on optimisers blindly... look at my kernel on xda... I fully support FDE.AI & L speed Officially!

**Comment by ab123321** [comment]
> Well.. then I guess your kernel doesn't work/developed correctly if your users are suffering from optimisers... don't just put the blame on optimisers blindly... look at my kernel on xda... I fully support FDE.AI & L speed Officially!

ok boomer.

**Comment by YaroST12** [comment]
> look at my kernel on xda...



> then I guess your kernel doesn't work/developed correctly if your users are suffering from optimisers...

**YES, YOU GUESSED IT! MY KERNEL DOESN'T PROPERLY WORK WITH OPTIMIZERS! THIS IS THE EXACT REASON WHY I BLOCK THEM, CONGRATULATIONS, YOU FIGURED IT OUT.**

**Comment by raphielscape** [comment]
> Well.. then I guess your kernel doesn't work/developed correctly if your users are suffering from optimisers... don't just put the blame on optimisers blindly... look at my kernel on xda... I fully support FDE.AI & L speed Officially!

Ok hex editor

**Comment by wloot** [comment]
> > 我要求您分享造成4pda线程故障的确切“调整”，您没有答复。那是我开始使用阻止程序的时间，因为我知道您很可能不会共享任何信息。
> > > 尼科对他没有冒犯。
> > 
> > 
> > 你知道那是不对的。尼科正在转向我和设备树创指责**你** fuckup（你可以在最后的消息中看到你的PIC）
> > 您正在遭受我的阻止者的痛苦，我正在遭受您的优化器和您可爱的朋友的痛苦，请我帮助他们解决问题。
> 
> 好吧..那我想如果您的用户正在使用优化器，那么您的内核将无法正常工作/开发...不要只是盲目地指责优化器...在xda上查看我的内核...我完全支持FDE.AI＆L速度正式！

Congratulations

**Comment by YaroST12** [comment]
> not BLOCKING them

FDE binary blocks all the other optimisers lol, nice.

**Comment by alexa-v2** [comment]
Although honestly it's probably not a good idea to start another argument, just gonna throw my two cents in

I agree, a lot of these "optimizers" are placebo and mess up more than they fix (absolutely no offense meant @Paget96 @feravolt ). There, however, is a better solution than providing inferior user experience by blocking any file with the name of the module in it (please do correct me if that's not exactly how this blocker works), and it's tried and tested for years.
Don't provide support for anyone who uses it.
That's right, no need to f*** up someone's experience, no need to deal with the extra headache if you don't want to try to figure out why tweaks break things. Just demand to know if they use any AIO tweakers, if they do, tell them to remove it and reproduce the issues they had or GTFO because it's _not your problem it's the tweakers_.

Myself, I generally only tweak things myself, trying one thing at a time so I can easily reverse anything that breaks something (Franco Kernel Manager being my preferred method of execution), but I can understand the attraction of these tweakers: press a button or literally do nothing and get either good performance or battery saving (arguments about the effectiveness notwithstanding).

My argument has never been about how great these tweakers are or how bad ones kernel is @YaroST12 . Quite frankly I don't use that device and have the know-how to remove that from the Kernel and build it on my own (though I don't claim to be an expert in kernels). My argument is it's the users prerogative to install the kernel yes, but also their prerogative to tweak it as they please (after all, isn't that the theory behind custom kernels in general? To be able to tweak beyond what Google has determined?)

Besides the logical arguments here I've only seen two actual arguments from you @YaroST12: it's my damn kernel and personal attacks on myself and the developers of these tweakers. You have yet to produce one shred of evidence this helps users in any way. No statistics, no user reporting, nada. I understand and respect that yes, it's your kernel to do with as you see fit, but like ever other developer out there you must consider user experience in daily usage. How many false positives is this bound to create, this blocker, also?

I guess my rather lengthy response boils down to one thing: no, it's not your problem, so don't deal with it. Don't block it but certainly don't bother providing support for it.

And once again I will reiterate this cannot be solved by magisk, short of either encryption of modules or obfuscation and I don't like to support either.

Anyhow really hope you all can come to some sort of agreement and stop fighting like children

I'm out
- Alexandria

**Comment by YaroST12** [comment]
> Don't provide support for anyone who uses it.

Not all people disclose their use of optimisers. They will just tell you that experience was terrible and run away.



> How many false positives is this bound to create, this blocker, also?

None. It's limited to magisk modules folder. I haven't encountered any false positives. If I will, I'll refine the algorithm.

> You have yet to produce one shred of evidence this helps users in any way.

First of all, FDE bricked about 10-15 Redmi K20 Pro devices. Second is this pic. It's from my chat, before the blocker was shipped.
![Screenshot_20200104-173930](https://user-images.githubusercontent.com/26440429/71767093-567de300-2f19-11ea-876b-05f6d0eb8dd6.png)


> after all, isn't that the theory behind custom kernels in general? To be able to tweak beyond what Google has determined?

It's not about kernels, it's about rooting in general. Theory behind custom kernels (at least for me) is to provide users with better UX with more features, better performance or battery life than what ships with the ROM by default.

I do not think that module-blocking on kernel level should be in kernels that ship with ROMs by default. It was never my intend to make optimisers blocking a widespread "feature", but you guys started this promotion campaign.

I hope that authors of optimizer modules will not go the route of obfuscating their products and we can continue co-existing like before.

I rewrote file-blocking code slightly. Now tweakers' files will be hidden.

**Comment by alexa-v2** [comment]
@YaroST12 fair point, people may not disclose it

My vote then goes to use already existing code to not hide the files but eg log to kmsg (logs or GTFO right?). Eg "WARNING! $BADMODULE DETECTED! NO SUPPORT IS PROVIDED FOR THESE MODULES." Display same error on kernel install as well. 

Once again, just my two cents and it's still your kernel and I have huge admiration for the many people who develop things like kernels (I don't touch kernels with a 10-foot stick lmao) even if I don't agree with everything you do.

**Comment by LLJY** [comment]
> > > > > > > Everything is visible
> > > > > > 
> > > > > > 
> > > > > > https://github.com/Magisk-Modules-Repo/lspeed/blob/master/app/LSpeedManager-v1.6.apk
> > > > > > Huh.
> > > > > 
> > > > > 
> > > > > Just simple app which doing sh on a module to execute it's parts.
> > > > 
> > > > 
> > > > And ads.
> > > 
> > > 
> > > Where? Please define ads.. and no I won't ask Google
> > 
> > 
> > I have no idea.
> > ![IMG_20200104_014622_550](https://user-images.githubusercontent.com/26440429/71753591-11639d80-2e94-11ea-96ce-559f3b82994c.jpg)
> 
> You call this an ads? Come on!

"Ok Google, define an advertisement"

![Screenshot_20200105-001808~2](https://user-images.githubusercontent.com/18326476/71768460-0458b400-2f51-11ea-97dc-f26560b0e961.png)

The picture you showed is the literal definition of an advertisement, it is a promotion of a service in a public medium.

I have nothing against @Paget96 or @feravolt .
But I do have a problem with retards, if you (@THEBOSS619 ) are going to argue, say something intelligent. This is GitHub, it's supposed to be a website for developers, not for the intellectually inept to defend whatever point they have to make.

If you want to say something, say something relevant, you're not going to solve anything by being an idiot.
 
As for @YaroST12 yes, he's aggressive. But he has a point. LSpeed and FDE.AI need to provide sources, providing a binary in an open source project is NOT OPEN SOURCE. Like how pasting an apple sticker on a car doesn't make it an Apple branded vehicle. I'm not going to attack the projects here as that will add no merit to me or "intellectual(-y disabled) conversation" we're having.

At the end of the day this is a stupid issue to bring up for a stupid problem we have to begin with. @YaroST12 's kernel breaking these so called "optimizers" are his problem to deal with, it's his project and his choice. If you have an issue with it, bring it up with him personally. It's not up to magisk to fix this mess, that's like asking Microsoft to fix something that Dell fucked up on their Computer.

Now will we end this stupid fucking argument, thank you very much.

**Comment by Paget96** [comment]
> > > > > > > > Everything is visible
> > > > > > > 
> > > > > > > 
> > > > > > > https://github.com/Magisk-Modules-Repo/lspeed/blob/master/app/LSpeedManager-v1.6.apk
> > > > > > > Huh.
> > > > > > 
> > > > > > 
> > > > > > Just simple app which doing sh on a module to execute it's parts.
> > > > > 
> > > > > 
> > > > > And ads.
> > > > 
> > > > 
> > > > Where? Please define ads.. and no I won't ask Google
> > > 
> > > 
> > > I have no idea.
> > > ![IMG_20200104_014622_550](https://user-images.githubusercontent.com/26440429/71753591-11639d80-2e94-11ea-96ce-559f3b82994c.jpg)
> > 
> > 
> > You call this an ads? Come on!
> 
> "Ok Google, define an advertisement"
> 
> ![Screenshot_20200105-001808~2](https://user-images.githubusercontent.com/18326476/71768460-0458b400-2f51-11ea-97dc-f26560b0e961.png)
> 
> The picture you showed is the literal definition of an advertisement, it is a promotion of a service in a public medium.
> 
> I have nothing against @Paget96 or @feravolt .
> But I do have a problem with retards, if you (@THEBOSS619 ) are going to argue, say something intelligent. This is GitHub, it's supposed to be a website for developers, not for the intellectually inept to defend whatever point they have to make.
> 
> If you want to say something, say something relevant, you're not going to solve anything by being an idiot.
> 
> As for @YaroST12 yes, he's aggressive. But he has a point. LSpeed and FDE.AI need to provide sources, providing a binary in an open source project is NOT OPEN SOURCE. Like how pasting an apple sticker on a car doesn't make it an Apple branded vehicle. I'm not going to attack the projects here as that will add no merit to me or "intellectual(-y disabled) conversation" we're having.
> 
> At the end of the day this is a stupid issue to bring up for a stupid problem we have to begin with. @YaroST12 's kernel breaking these so called "optimizers" are his problem to deal with, it's his project and his choice. If you have an issue with it, bring it up with him personally. It's not up to magisk to fix this mess, that's like asking Microsoft to fix something that Dell fucked up on their Computer.
> 
> Now will we end this stupid fucking argument, thank you very much.

L Speed already have a sources, everything what's going to be executed on boot is visible.
 https://github.com/Magisk-Modules-Repo/lspeed/tree/master/system/etc/lspeed/binary

**Comment by YaroST12** [comment]
> Eg "WARNING! $BADMODULE DETECTED! NO SUPPORT IS PROVIDED FOR THESE MODULES." Display same error on kernel install as well.

Not many users even know what a kernel log is. Even less actually read it. What about users installing kernel first and then optimizer, how do I warn them? Exactly, I can't.

**Comment by Paget96** [comment]
> > Eg "WARNING! $BADMODULE DETECTED! NO SUPPORT IS PROVIDED FOR THESE MODULES." Display same error on kernel install as well.
> 
> Not many users even know what a kernel log is. Even less actually read it. What about users installing kernel first and then optimizer, how do I warn them? Exactly, I can't.

That's true, people actually just using stuff without reading, even if you put a disclaimer. Well log is for you not for them, just put an output so you'll know what is user using, make a list of all modules from /data/adb/modules so you should know can you give him support or no. Make a submission or something how the people will send you a bug report, what's the requirements and so on.

**Comment by THEBOSS619** [comment]
> > > > > > > > Everything is visible
> > > > > > > 
> > > > > > > 
> > > > > > > https://github.com/Magisk-Modules-Repo/lspeed/blob/master/app/LSpeedManager-v1.6.apk
> > > > > > > Huh.
> > > > > > 
> > > > > > 
> > > > > > Just simple app which doing sh on a module to execute it's parts.
> > > > > 
> > > > > 
> > > > > And ads.
> > > > 
> > > > 
> > > > Where? Please define ads.. and no I won't ask Google
> > > 
> > > 
> > > I have no idea.
> > > ![IMG_20200104_014622_550](https://user-images.githubusercontent.com/26440429/71753591-11639d80-2e94-11ea-96ce-559f3b82994c.jpg)
> > 
> > 
> > You call this an ads? Come on!
> 
> "Ok Google, define an advertisement"
> 
> ![Screenshot_20200105-001808~2](https://user-images.githubusercontent.com/18326476/71768460-0458b400-2f51-11ea-97dc-f26560b0e961.png)
> 
> The picture you showed is the literal definition of an advertisement, it is a promotion of a service in a public medium.
> 
> I have nothing against @Paget96 or @feravolt .
> But I do have a problem with retards, if you (@THEBOSS619 ) are going to argue, say something intelligent. This is GitHub, it's supposed to be a website for developers, not for the intellectually inept to defend whatever point they have to make.
> 
> If you want to say something, say something relevant, you're not going to solve anything by being an idiot.
> 
> As for @YaroST12 yes, he's aggressive. But he has a point. LSpeed and FDE.AI need to provide sources, providing a binary in an open source project is NOT OPEN SOURCE. Like how pasting an apple sticker on a car doesn't make it an Apple branded vehicle. I'm not going to attack the projects here as that will add no merit to me or "intellectual(-y disabled) conversation" we're having.
> 
> At the end of the day this is a stupid issue to bring up for a stupid problem we have to begin with. @YaroST12 's kernel breaking these so called "optimizers" are his problem to deal with, it's his project and his choice. If you have an issue with it, bring it up with him personally. It's not up to magisk to fix this mess, that's like asking Microsoft to fix something that Dell fucked up on their Computer.
> 
> Now will we end this stupid fucking argument, thank you very much.

Oh yet you asked Google... even I said not to do so 🤣 PATHETIC 🤢🤮 who's idiot now .... eh? This is Github and this not place for people like you to be here faggot 😂
Please be useful rather NOTHING or you're just a human being consuming Oxygen for nothing in return

I hope you read this correctly because I said don't ask Google and yet... YOU DID!... please ask Google if you worthless or not

**Comment by THEBOSS619** [comment]
> > Well.. then I guess your kernel doesn't work/developed correctly if your users are suffering from optimisers... don't just put the blame on optimisers blindly... look at my kernel on xda... I fully support FDE.AI & L speed Officially!
> 
> Ok hex editor

Ok brainless bastard

**Comment by LLJY** [comment]
> > > > > > > > > Everything is visible
> > > > > > > > 
> > > > > > > > 
> > > > > > > > https://github.com/Magisk-Modules-Repo/lspeed/blob/master/app/LSpeedManager-v1.6.apk
> > > > > > > > Huh.
> > > > > > > 
> > > > > > > 
> > > > > > > Just simple app which doing sh on a module to execute it's parts.
> > > > > > 
> > > > > > 
> > > > > > And ads.
> > > > > 
> > > > > 
> > > > > Where? Please define ads.. and no I won't ask Google
> > > > 
> > > > 
> > > > I have no idea.
> > > > ![IMG_20200104_014622_550](https://user-images.githubusercontent.com/26440429/71753591-11639d80-2e94-11ea-96ce-559f3b82994c.jpg)
> > > 
> > > 
> > > You call this an ads? Come on!
> > 
> > 
> > "Ok Google, define an advertisement"
> > ![Screenshot_20200105-001808~2](https://user-images.githubusercontent.com/18326476/71768460-0458b400-2f51-11ea-97dc-f26560b0e961.png)
> > The picture you showed is the literal definition of an advertisement, it is a promotion of a service in a public medium.
> > I have nothing against @Paget96 or @feravolt .
> > But I do have a problem with retards, if you (@THEBOSS619 ) are going to argue, say something intelligent. This is GitHub, it's supposed to be a website for developers, not for the intellectually inept to defend whatever point they have to make.
> > If you want to say something, say something relevant, you're not going to solve anything by being an idiot.
> > As for @YaroST12 yes, he's aggressive. But he has a point. LSpeed and FDE.AI need to provide sources, providing a binary in an open source project is NOT OPEN SOURCE. Like how pasting an apple sticker on a car doesn't make it an Apple branded vehicle. I'm not going to attack the projects here as that will add no merit to me or "intellectual(-y disabled) conversation" we're having.
> > At the end of the day this is a stupid issue to bring up for a stupid problem we have to begin with. @YaroST12 's kernel breaking these so called "optimizers" are his problem to deal with, it's his project and his choice. If you have an issue with it, bring it up with him personally. It's not up to magisk to fix this mess, that's like asking Microsoft to fix something that Dell fucked up on their Computer.
> > Now will we end this stupid fucking argument, thank you very much.
> 
> Oh yet you asked Google... even I said not to do so  PATHETIC 🤮 who's idiot now .... eh? This is Github and this not place for people like you to be here faggot 
> Please be useful rather NOTHING or you're just a human being consuming Oxygen for nothing in return
> 
> I hope you read this correctly because I said don't ask Google and yet... YOU DID!... please ask Google if you worthless or not

If you're getting into specifics



> > > > > > > > > Everything is visible
> > > > > > > > 
> > > > > > > > 
> > > > > > > > https://github.com/Magisk-Modules-Repo/lspeed/blob/master/app/LSpeedManager-v1.6.apk
> > > > > > > > Huh.
> > > > > > > 
> > > > > > > 
> > > > > > > Just simple app which doing sh on a module to execute it's parts.
> > > > > > 
> > > > > > 
> > > > > > And ads.
> > > > > 
> > > > > 
> > > > > Where? Please define ads.. and no I won't ask Google
> > > > 
> > > > 
> > > > I have no idea.
> > > > ![IMG_20200104_014622_550](https://user-images.githubusercontent.com/26440429/71753591-11639d80-2e94-11ea-96ce-559f3b82994c.jpg)
> > > 
> > > 
> > > You call this an ads? Come on!
> > 
> > 
> > "Ok Google, define an advertisement"
> > ![Screenshot_20200105-001808~2](https://user-images.githubusercontent.com/18326476/71768460-0458b400-2f51-11ea-97dc-f26560b0e961.png)
> > The picture you showed is the literal definition of an advertisement, it is a promotion of a service in a public medium.
> > I have nothing against @Paget96 or @feravolt .
> > But I do have a problem with retards, if you (@THEBOSS619 ) are going to argue, say something intelligent. This is GitHub, it's supposed to be a website for developers, not for the intellectually inept to defend whatever point they have to make.
> > If you want to say something, say something relevant, you're not going to solve anything by being an idiot.
> > As for @YaroST12 yes, he's aggressive. But he has a point. LSpeed and FDE.AI need to provide sources, providing a binary in an open source project is NOT OPEN SOURCE. Like how pasting an apple sticker on a car doesn't make it an Apple branded vehicle. I'm not going to attack the projects here as that will add no merit to me or "intellectual(-y disabled) conversation" we're having.
> > At the end of the day this is a stupid issue to bring up for a stupid problem we have to begin with. @YaroST12 's kernel breaking these so called "optimizers" are his problem to deal with, it's his project and his choice. If you have an issue with it, bring it up with him personally. It's not up to magisk to fix this mess, that's like asking Microsoft to fix something that Dell fucked up on their Computer.
> > Now will we end this stupid fucking argument, thank you very much.
> 
> Oh yet you asked Google... even I said not to do so  PATHETIC 🤮 who's idiot now .... eh? This is Github and this not place for people like you to be here faggot 
> Please be useful rather NOTHING or you're just a human being consuming Oxygen for nothing in return
> 
> I hope you read this correctly because I said don't ask Google and yet... YOU DID!... please ask Google if you worthless or not

If you want to be specific you said

"Where? Please define ads.. and no I won't ask Google"

that means I can ask Google, you didn't specifically state that we couldn't :D . And now you're trying to get at me for english? Pathetic.

I'm going to repeat my point, if you want to say something, say something intelligent. Else, please direct your comments to /dev/null.

I have better things to do now, don't bother arguing again.

Lucas out.

**Comment by dev-harsh1998** [comment]
> > I asked you to share which exact "tweaks" caused devices to malfunction in your 4pda thread, you didn't reply. That's when I started working on the blockers because I knew that you most likely won't share any info.
> > > Niko was'nt offencive to him.
> > 
> > 
> > You know that's not true. Niko was shifting blame on me and device tree creators for **your** fuckup (which you can see in the last message on your pic)
> > You are suffering from my blocker, I'm suffering from your optimisers and your lovely friends, asking me to help them with their bricks.
> 
> Well.. then I guess your kernel doesn't work/developed correctly if your users are suffering from optimisers... don't just put the blame on optimisers blindly... look at my kernel on xda... I fully support FDE.AI & L speed Officially!

Okay <Developed> Boomer.

**Comment by THEBOSS619** [comment]
> I'm going to repeat my point, if you want to say something, say something intelligent. Else, please direct your comments to /dev/null.

And I'm going to repeat my point, if you want to say something, say something intelligent. Else, please direct your comments to /dev/null.... I have a life instead than not having one like you, Pathetic!

Your BOSS OUT!

**Comment by YaroST12** [comment]
@feravolt, why don't you tell @Paget96 and @HafizZiq that you block their modules too?

**Comment by alexa-v2** [comment]
You all are seriously acting like absolute children now

Besides that this isn't the place for it. Take your insults somewhere else

**Comment by alexa-v2** [comment]
@topjohnwu I'm in favor of locking this issue

**Comment by NitroVenom** [comment]
Having a problem with shitty optimizer that claim to give you more battery and performance? Don't use them!
