### ISSUE TITLE
Magisk Manager 7.5 installing module cannot take effect

### ISSUE THREAD

**Issue by FoxHoundLuo** [topjohnwu/Magisk#2225]
I have a question about Magisk Manager 7.5, my phone is Pixel 4.
I used Magisk Manager for boot cracking and successfully rooted.
But after installing the module
[EnableSoli.zip](https://github.com/topjohnwu/Magisk/files/4029706/EnableSoli.zip)

, the module cannot take effect.
I can only reinstall older versions of Magisk for the module to take effect.
Effective Magisk Manager is 7.3.5, Magisk version is 19.4.
I can send it to you if you need to provide the corresponding module.
I do n’t know what caused the module to fail to take effect. It ’s a problem with the module or a problem with Magisk. Please help. Thank you.

**Comment by Didgeridoohan** [comment]
It's a module issue, so please close this so that John doesn't have to.

The module is using an outdated template format and can therefore not be installed properly on the current Magisk release. If you want to update the module yourself, take a look at the docs: https://topjohnwu.github.io/Magisk/

Or, since the module only sets prop values, you can simply use a boot script and the resetprop tool (again, see the docs) or use a module like MagiskHide Props Config (available in the Magisk repo) to set the prop values you want.
