### ISSUE TITLE
Oppo A9 2020 support

### ISSUE THREAD

**Issue by sresam89** [topjohnwu/Magisk#2235]
Requesting support for oppo A9 2020 phone. Attached the boot.img. The application says
! Unsupported /Unknown image format
! Installation failed

[boot.zip](https://github.com/topjohnwu/Magisk/files/4034204/boot.zip)

**Comment by shakalaca** [comment]
Because it's encrypted, find a tool (like this one: https://github.com/bkerler/oppo_ozip_decrypt) to decrypt first then patch it.

**Comment by sresam89** [comment]
Got the file decrypted, still cannot patch, same error

**Comment by sresam89** [comment]
@topjohnwu Can you please re-open the issue?
I can provide any supporting logs

**Comment by Ahmadhaidare33** [comment]
im sorry i have OPPO A9 2020 CPH1933 can you help me for rooting this devices 
because me phone OMEUnlouck is off and i can't on that and also i don't know my bootloader is unlock or louck 
![Screenshot_2026-09-20-05-09-16-70_fc704e6b13c4fb26bf5e411f75da84f2.jpg](https://github.com/user-attachments/assets/9617e41f-1d14-4506-a0dd-f9e5cbb080a1)
