### ISSUE TITLE
Update the new version of Magisk Template

### ISSUE THREAD

**Issue by zjw2017** [topjohnwu/Magisk#2310]
Can the author upload the new version of Magisk Template？

**Comment by martyfender** [comment]
https://topjohnwu.github.io/Magisk/guides.html

**Comment by zjw2017** [comment]
I don't know how to write install.sh and cusotmize.sh

**Comment by zjw2017** [comment]
> https://topjohnwu.github.io/Magisk/guides.html

我不知道如何编写install.sh和cusotmize.sh

**Comment by zjw2017** [comment]
> https://topjohnwu.github.io/Magisk/guides.html

I don't know how to write install.sh and cusotmize.sh

**Comment by Didgeridoohan** [comment]
> I don't know how to write install.sh and cusotmize.sh

A template is not necessary... Just follow the linked instructions.

Install.sh shouldn't be in the installer, so you can forget about that one.

Customize.sh is only needed if you need special installation procedures, and then a template won't help you anyway.

Please close this issue, so that John doesn't have to.
