### ISSUE TITLE
Questions: Rundown of security implications

### ISSUE THREAD

**Issue by eike-fokken** [topjohnwu/Magisk#2414]
This issue is rather a couplie of question and not (yet?) a feature request. It is rather long, I'm sorry about that.

I've rooted my device (Pixel sailfish with lineageos 16 with microg, if thats important) with magisk and everything works as intended.

Seeking to secure the root access against unauthorized use I came across the following claims, which I don't understand. Therefore I would be grateful for someone to enlighten me (and hence anyone who finds this issue) and I offer to make a pull request for the docs if that's useful.

1. Claim: Having a rooted phone is intrinsically insecure and there is no way to secure root access apart from never letting anyone get your device.

I find this to be true as I have not found a way to prevent app installation through apk, so. But is this statement true in principle or would it just require (minor) changes on part of the rom producer?

2. Claim: Apps can fake my consent to the root privilige prompt.

I heard that it is connected to accessibility settings(?). Under what conditions can apps do that?

3. Claim: Apps cannot fake my fingerprint on that prompt.
True?

4. Claim: The fingerprint on the prompt only protects against malicious apps, not against an attacker physically present at the unlocked phone.
Is this to do with point 1?

**Comment by wangdaning** [comment]
Root itself does not do much. Having an unlocked bootloader might (someone could potentially get in your device with an unlocked bootloader). I think in 1) you meant adb. You can restrict root access through adb in magisk settings. Also, in dev options. That would mean adb gets no root access. For 2) I think you would have to give an app the permissions to do such a thing, so make sure you are only installing known apps. 3 and 4 I have no clue.

**Comment by eike-fokken** [comment]
I really meant apk. The scenario I had in mind was that someone could download an apk, e.g. a terminal emulator, that then asks for root permission which it gets (if 2 is true).
For adb I thought that preventing adb in developers options fixes security on that side.

**Comment by wangdaning** [comment]
OK, but that would suppose you device was unlocked into android. They could force the apk in another way, but they could not get to the dialogue unless it was actually open in runtime.

**Comment by eike-fokken** [comment]
Yes, but this is a scenario I would like to be safe against. My questions are in the end about:
Can I have a rooted phone and still hand it to someone else unlocked (admittedly I don't expect anyone I give my phone to, to actually bear me ill-will).
I would just enable the fingerprint on root access prompt but this entails that I have to use fingerprint for unlocking which I dont want for various reasons.
Therefore I'm trying to understand better, what's possible security-wise so I can make the right feature request at the right point.
One possible feature request would be: enable the current screen-unlock method for root prompt instead of only fingerprint.
But I'm not sure how much security that gives me (see 1.).

**Comment by wangdaning** [comment]
If you are giving them the device and you are not going to be watching what they are doing give it to them in a guest account and disable root for guest account.

**Comment by eike-fokken** [comment]
Well, you are right. The other scenario I had in mind was that someone snatches the phone from my hand, but even then he can access all my data as far as it is not unencrypted (like password manager) so I guess this is just too paranoid and will let it go.
Nevertheless I think answers on my questions would make a fine addition to the documentation.

**Comment by Fox2Code** [comment]
Well I have an answer for the 4 questions you asked 
**1.** _Claim: Having a rooted phone is intrinsically insecure and there is no way to secure root access apart from never letting anyone get your device._
**Response:** In fact is unlocking the bootloader that causes a problem since an unlocked bootloader allows running custom code(kernel/recovery) with physical access  so even if you have a password locked recovery or stock recovery even if your current ROM is not rooted your phone can't be secure against physical access
(This can be fixed by modifying the bootloader but changing the bootloader is a very high chance of definitely hard brick your phone so it's not recommended and it's why no one does that)
**2.** _Claim: Apps can fake my consent to the root privilege prompt._
**Response:** App can set flags to prevent custom input or control by accessibility services by setting a custom security flag to their activity and by searching I found that Magisk currently don't have this flag on their SU Request activity si, in theory, yes apps can force click on yes at the moment but it really easy to patch and will be fixed very soon
**3.** _Claim: Apps cannot fake my fingerprint on that prompt._
**Response:** No apps can't fake your fingerprint except if they use a security vulnerability
**4.** _Claim: The fingerprint on the prompt only protects against malicious apps, not against an attacker physically present at the unlocked phone._
**Response:** some security researcher found a way to bypass fingerprint sensor on phone with "universal fingerprint" but it doesn't work for all phones so it mainly depends on the quality of the fingerprint sensor of your phone

I hope I responded correctly of the 4 questions you asked

**Comment by topjohnwu** [comment]
1. Yes, unlocking bootloader disabled Android verified boot, which freely opens the gate for unauthorized code to run on your device (which is why Magisk works)

2. This is not easily achievable. Unless there is a security vulnerability within Magisk itself, then there should be no possible way to do so.
Do note that any root app can grant additional apps to root access as they can just simply modify the database Magisk uses to check against. So choose carefully who to trust when you grant root to any process.

3, 4. This depends on your device manufacturer. If your device is properly created, the fingerprint data is stored within hardware no software can access, and cryptography guarantees the legitimacy of the fingerprint data. However, if the security of your device is not properly implemented, there will be vulnerabilities that can possibly fake your fingerprint.

**Comment by eike-fokken** [comment]
Thank your for your detailed response, @Fox2Code and for the additional remarks @topjohnwu!
So with a rooted phone I'm basically where I am with usual Gnu/Linux computers. Secureboot is off (I know this is not neccessary with Linux anymore) but it is still worthwile to keep my root password from others.
