### ISSUE TITLE
Magisk greater than v19.2 requires MagiskHide to be toggled off/on to work

### ISSUE THREAD

**Issue by RomikB** [topjohnwu/Magisk#2428]
Same problem as here https://github.com/topjohnwu/Magisk/issues/1654.
Samsung Galaxy Note 3 N9005
Android v5.0

Can't add log file because its size is 0.

**Comment by Fox2Code** [comment]
Please try again but send logcat instead of Magisk logs
`adb logcat`
In this situation, we currently don't know what causes the bug because of lack of information.
Also, MagiskHide is fully supported only in Android 6 or you need a custom patch to kernel support isolated mount spaces.
So if you can also send your kernel version it would help too. (Visible in about phone)
