### ISSUE TITLE
Section in tutorial on disabling OTA updates outdated

### ISSUE THREAD

**Issue by bladeSk** [topjohnwu/Magisk#2463]
[The section](https://topjohnwu.github.io/Magisk/tutorials.html#ota-installation) describing how to disable automatic OTA updates no longer works. The toggle has no effect and some updates (not all, presumably only those marked as "mandatory") are downloaded and installed without user consent, which unroots the phone on next restart and the user may not even be aware of it if they disabled update notifications. This applies to Android 9 or newer with the latest Google Play Services. I'm using Xiaomi Mi A1, for the reference.

I've made a simple Magisk module that runs `chmod 550 /data/ota_package` on boot. It's probably not the most elegant way of disabling updates - a notification saying "not enough disk space for update" is generated on every update attempt (about twice a day), but the notifications can be muted and at least it prevents updates.

Anyway, this seems like an issue that should be addressed. I could try decompiling Google Play Services and make a module that would disable forced OTAs without annoying notifications, if there was interest.

**Comment by wangdaning** [comment]
Disabling the updates in dev options simply stops system updates from automatically applying at reboot. If your system is trying to update automatically even with that toggled it should fail if you have root. The toggle will not stop google play services from updating. Play services has always auto updated in the background, but I don't think that should kill root either. 

That is my experience on the Pixel 3, I suppose it could be a device specific thing.

**Comment by topjohnwu** [comment]
@bladeSk the OTA should not be able to be applied anyway since your device is rooted.
This issue seems to be OEM specific and non-trivial.

**Comment by bladeSk** [comment]
It has been applied twice, un-rooting my phone in the process. I have no way of testing this on a different device at the moment, but I'm certain the update was initiated by Google Play Services - clearing its data prevented the update being applied on reboot. The toggle in dev settings or having Magisk installed did not prevent this.

How does Magisk protect against installing an OTA? I could investigate further why it failed.

**Comment by razor-91** [comment]
I can confirm this issue also happened to me on on Oneplus Nord N100, a few days ago using Magisk 25.2 boot image patch method.

I had factory reset my phone, which was on OxygenOS 10.5.8, then installed magisk 25.2 using patched boot image.

After connecting to wifi and setting up my usual root apps, a new ota update downloaded in the background and without any prompt restarted my phone. 

After the restart, when I checked the version, it was OxygenOS 11.0.3 already, and root was lost. My phone auto updated even though I have root and even unchecked the "apply updates on reboot" in dev options. I had also put google play related services in denylist if that helps. 

This made me so mad because at that time I had no update zip which I can extract the boot image to repatch again for magisk. Twrp for my device is also very buggy and have no internal data access, which made me unable to flash magisk via zip too.

Looks like this is a legit issue which should at least have a module which we can apply to stop ota updates from being forced upon.

Thanks and Regards.
