### ISSUE TITLE
@Justsnoopy30 I understand your frustration, you are young man and can be edgy, but please, have some respect while talking to adult. Everything was working before and I didn't change anything. So I request a fix for that problem because my financial operations are currently blocked.

### ISSUE THREAD

**Issue by S555555** [topjohnwu/Magisk#2536]
@Justsnoopy30 I understand your frustration, you are young man and can be edgy, but please, have some respect while talking to adult. Everything was working before and I didn't change anything. So I request a fix for that problem because my financial operations are currently blocked.

It doesn't matter if licence has no warranty, I suffered moral and financial damage because of this issue and we can prevent more damage to happen if fix is provided within given time. All financial and moral damage after 48 hour period will be counted and attached to the lawsuit.

With respect,
Todd

_Originally posted by @SachseConstruct in https://github.com/topjohnwu/Magisk/issues/2534#issuecomment-598429186_

**Comment by Justsnoopy30** [comment]
What is this? Why did you open an issue with a comment as the title and mention the issue with the comment?

**Comment by linuxandria** [comment]
Argh

**Comment by linuxandria** [comment]
Are you trying to tick off John so much he'll quit magisk entirely? Or are you just plain stupid?

Get over yourself. You're hardly the only one hard hit by Google's decision. If nothing else hit a star on https://issuetracker.google.com/issues/151316418 (probably won't actually get anything done but never hurts to try)

Otherwise lock your bootloader, enjoy your working safety net and get the f*** off this issue tracker

@topjohnwu if you ever want to discuss ways to restructure this project so you don't have to deal with crappy users like him I'll be happy to share a few pointers
