### ISSUE TITLE
To John

### ISSUE THREAD

**Issue by ToddSachse** [topjohnwu/Magisk#2542]
Hello, dear John.

I'm grateful that we found solution to this problem, my bank apps do work now. I didn't want to make a threat with court, but I had to. I'm glad it got fixed within 24 hours. I wish you didn't ban me and we had great conversation! Cheers!

With big respect,
Todd

**Comment by People-11** [comment]
This is not Magisk's fault!

Dear user, I understand your feeling. But you have to think twice about is this actually Magisk's fault?

As you know, you unlocked your bootloader by your own, and installed Magisk by your own too.
As you unlock/install Magisk, you have your own risk on your mobile phone to be unsafe. When you unlocking bl, you will receive a warn from Google. Have you read that warn or just ignored it?

Your bank my have SafetyNet detections, it runs well until yesterday--Google changed the policy that the unlocked device will not pass SafetyNet, that's why your app didn't work. it's Google made that not working, not Magisk.

Now, Google have restored the policy about SafetyNet, so your app will work properly. You should stop blaming Magisk and Google, they are not at fault, or just for security.

Best wishes

**Comment by People-11** [comment]
If you insist on a lawsuit, I can tell you that it is almost impossible to win, because it is you who agreed to take responsibility, and it was you who caused it all

**Comment by People-11** [comment]
@ToddSachse 
 You are the CEO of a company, but it does not mean that you know better than us in this regard, please do not be proud, we know more than you

**Comment by Aluminite** [comment]
@ToddSachse You are delusional. The "fix" had absolutely nothing to do with you or Magisk. Google has changed something on their end and probably will change it back sooner or later.
