### ISSUE TITLE
Permissive Magisk/Superuser settings for ROM

### ISSUE THREAD

**Issue by chrisfraser** [topjohnwu/Magisk#2646]
Hey guys.

I have a weird use cash here. I have thousands of devices that have either no screen or tiny screens. I have full control over the files in the ROM that I flash to these, but I need a way to automate Superusers settings.

I need a way to set Superuser: Automatic Response to Grant and Notification to None on first boot without user interaction. These devices are fully locked down, so I am ok with this. 

Can someone please suggest a way to achieve this?

**Comment by shakalaca** [comment]
Do the setup in phone and copy 
1. /data/user_de/0/com.topjohnwu.magisk/shared_prefs/com.topjohnwu.magisk_preferences.xml or /data/data/com.topjohnwu.magisk/shared_prefs/com.topjohnwu.magisk_preferences.xml
2. /data/adb/magisk.db

to your devices

**Comment by shakalaca** [comment]
ah didn't notice those words: 'first boot'. In that case you should compile your own version of Magisk by changing the default settings

**Comment by chrisfraser** [comment]
I have tried to copy `/data/data/com.topjohnwu.magisk/shared_prefs/com.topjohnwu.magisk_preferences.xml` into the data partition previously, but I had issues with folder owner permissions. What owners and permissions should I give those files in the /data partition of the ROM?

I have made custom builds of Magisk to achieve this before, but it becomes an issue with upgrade as signatures don't match. I will fall back to this, but was hoping there is an easy solution I did not know about.

**Comment by xerta555** [comment]
> I have made custom builds of Magisk to achieve this before, but it becomes an issue with upgrade as signatures don't match. I will fall back to this, but was hoping there is an easy solution I did not know about.

Since basically the root access management logic of the target device is basic (by default) subject to user control because Magisk is widely distributed as it has been so far, there is no so-called "magic" solution as you might expect.

The simplest (at least that's how I would do it if I were in your place) in my eyes, would be to create a script that would automate all the tasks.

That way, you'd theoretically only have to think once time seriously for the coding part.
Once you've done that, all you'd have to do is pray that John doesn't change the compilation logic used for Magisk or the signing logic for this project every month.

**Comment by osm0sis** [comment]
You guys are free to discuss this further, but it's outside the scope of Magisk to provide a solution for this very specific use-case.
