### ISSUE TITLE
Flashing patched image ends in bootloop

### ISSUE THREAD

**Issue by victornworgu** [topjohnwu/Magisk#2724]
I'm using an Infinix Note 5 X604 running Android 10. The device is a confirmed A/B device and I had Magisk on same device when it was still on Pie. The problem is after flashing the new firmware (I have the ROM), I grabbed the boot.img patched with Magisk and flashed to the device via fastboot, then I got a bootloop. One interesting thing I found out is that while the original boot image is about 32 MB, the Magisk patched image is just about 15 MB. I patched with the latest stable version. What could be wrong?

**Comment by osm0sis** [comment]
#2695

**Comment by engrahmadosama** [comment]
@victornworgu you are right, I have same device infinix x604 have been trying to root and seeking help here from a month.

But people here are arrogant and not coordinating or listening. I believe we should share our experience and knowledge.


Whenever's I try to patch magisk_patched.img boot file,I am stuck in bootloops. Which never end even I flash original boot file. I have to reflash entire room again in order to get it work.

I strongly believe there is some problem with magisk code, not any other thing.

**Comment by osm0sis** [comment]
Yeah I linked the duplicate issue so you could continue to follow and help with users with the other affected devices.

That's not arrogant, you are, right now.
