### ISSUE TITLE
magisk hide v20.4 not working on the some banking app

### ISSUE THREAD

**Issue by BlacksoftEvolution** [topjohnwu/Magisk#2734]
some banking app still detect rooted device if using v20.4
now i uninstall v20.4 and install v20.3 again 
v20.3 is fine

**Comment by osm0sis** [comment]
You just need to go enable MagiskHide in the settings most likely. It's *default* off now, but easily enabled.

**Comment by BlacksoftEvolution** [comment]
I've enabled magisk hide in settings and have hidden some apps from magisk but magisk hide is a problem. I think this is a bug from v20.4. please u try one of these app (BNI) playstore

**Comment by BlacksoftEvolution** [comment]
I've enabled magisk hide in settings and have hidden some apps from magisk but magisk hide is not working properly. I think this is a bug from v20.4. please u try one of these app (BNI) playstore

**Comment by Didgeridoohan** [comment]
If you mean this app, Magisk has no issues hiding from it (I tested and can open it without issue with the app on the Hide list and the Manager repackaged with a random name):
https://play.google.com/store/apps/details?id=src.com.bni

If there's a bug to have to show what it is, because everything seems to be working here...
