### ISSUE TITLE
Pixel 3XL A10 OTA issue: must uninstall Magisk even before scanning

### ISSUE THREAD

**Issue by djechelon** [topjohnwu/Magisk#2797]
I have been experiencing this since February 2020, now it looks like the workaround is stable

Before February 2020:
When an OTA was available on 5th day of the month, Android made it available but stopped because it detected the system was inconsistent.
After uninstalling Magisk, the system would update itself.
Following instructions at official [page](https://topjohnwu.github.io/Magisk/ota.html) helped

After February 2020:
Searching for OTA when Magisk is installed busts the ability to find that update, probably for good. Only way is to flash OTA via ADB and repatch boot image.
I have to uninstall Magisk by the day I _think_ there might be a system update, then go to System and check.

When I just remember this trick, I will apply future updates till today. Just wanted to report for sake of sharing.

**Comment by osm0sis** [comment]
I think this was noted once before. Try adding Settings or any updater app the Pixel ROM has to MagiskHide's list and see if it resolves it.

For reference, similarly on OnePlus OxygenOS the updater app detects root and forces downloading a Full OTA instead of incremental. Adding their updater to MagiskHide's list gets it offering incremental again. Though you wouldn't want that anyway, it shows something like this could work for your issue.
