### ISSUE TITLE
[Feature Request] recovery kernel patching for modules on A-only SAR Xiaomi devices

### ISSUE THREAD

**Issue by KhushrajRathod** [topjohnwu/Magisk#2827]
Magisk doesn't seem to be able to patch ramdisk on aonly system-as-root devices, I assume that's why the recovery option is there. However recovery kernels can't load modules on Xiaomi devices. A patcher by @YaAlex3 [here](https://patcher.yaalex.tk) seems to be able to fix the issue (it works on Redmi 7A, tested). Is it possible to implement this directly in magisk? Thanks

**Comment by LCCR193** [comment]
Just wait @topjohnwu is busy at the moment working on android 11......

**Comment by zgfg** [comment]
Xiaomi Mi 9T/Redmi K20
MIUI 11, also A-only SAR

To install Magisk I (and others) patch boot.img, but without that Recovery option (since it is boot, not recovery image). Then flash the patched image, again to boot

That way I have Magisk and everything works perfectly, root, modules (Systemless hosts, ADB and Fastboot for Android NDK, BusyBox, AML, Viper4Android, Mi  9T Bitrate increase, SQL Lite3 and GPay SQL Lite Fix)

Since Magisk is patched to Boot, I have TWRP (actually OrangeFox) in Recovery - that way I have both Magisk and custom Recovery

When I flashed Hasty kernel I temporarily lost Magisk. However, I made a TWRP (OrangeFox, doesn't matter) backup of my boot image (with Hasty kernel flashed), patched Magisk to the boot.emmc.win backup and flashed again now that new magisk_patched.img (directly from OrangeFox)

Upon that, I have Hasty kernel and Magisk (and OrangeFox) and everything is fully operational: root, modules, governors in kernel...

Sorry if I missed your point, just wanted to say that I don't see (with my modules) any problem with Magisk and custom Kernel on the Xiaomi A-only SAR phone

**Comment by KhushrajRathod** [comment]
You're saying you "patched" the boot image - Do you mean patched using magisk manager / magisk flashable zip, or do you mean patched using a tool like for e.g. patcher.yaalex.tk

**Comment by KhushrajRathod** [comment]
@zgfg

**Comment by KhushrajRathod** [comment]
Also @osm0sis I believe you've changed the title away from my initial request - I'm not making a feature request to patch the recovery kernel - that's only the problem faced **if** using the recovery method. patcher.yaalex.tk manages to patch the boot image, so then it is possible to use the boot method of magisk manager even on a a-only SAR device, which the wiki claims not possible. However if it's not possible to implement boot patching in magisk, then recovery kernel patching for modules is also a good solution

**Comment by YaAlex3** [comment]
> Xiaomi Mi 9T/Redmi K20
> MIUI 11, also A-only SAR
> 
> To install Magisk I (and others) patch boot.img, but without that Recovery option (since it is boot, not recovery image). Then flash the patched image, again to boot
> 
> That way I have Magisk and everything works perfectly, root, modules (Systemless hosts, ADB and Fastboot for Android NDK, BusyBox, AML, Viper4Android, Mi  9T Bitrate increase, SQL Lite3 and GPay SQL Lite Fix)
> 
> Since Magisk is patched to Boot, I have TWRP (actually OrangeFox) in Recovery - that way I have both Magisk and custom Recovery
> 
> When I flashed Hasty kernel I temporarily lost Magisk. However, I made a TWRP (OrangeFox, doesn't matter) backup of my boot image (with Hasty kernel flashed), patched Magisk to the boot.emmc.win backup and flashed again now that new magisk_patched.img (directly from OrangeFox)
> 
> Upon that, I have Hasty kernel and Magisk (and OrangeFox) and everything is fully operational: root, modules, governors in kernel...
> 
> Sorry if I missed your point, just wanted to say that I don't see (with my modules) any problem with Magisk and custom Kernel on the Xiaomi A-only SAR phone
> 
> 

The whole point of the issue is, redmi 7a is arm32_binder64 with 32bit kernel. Magisk successfully patches 64bit kernel to not skip initramfs on boot, however, arm32 sfx kernels won't work. Here was an issue about it already, where recovery mode came as a fix. However, referring to first post, on given device hardware modules not being able to load with the recovery kernel.

**Comment by zgfg** [comment]
> You're saying you "patched" the boot image - Do you mean patched using magisk manager / magisk flashable zip, or do you mean patched using a tool like for e.g. patcher.yaalex.tk


Patching always from Magisk Manager. You can get boot image (to patch) from ZIP firmware or by backing boot from TWRP/, OrangeFox.
Patch by unchecking Recovery option!
Flash from Fastboot or from TWRP/OrangeFox
