### ISSUE TITLE
Magisk breaks baseband in OnePlus OxygenOS 10.3.3

### ISSUE THREAD

**Issue by tallnatt** [topjohnwu/Magisk#2875]
After upgrading to OOS 10.3.3.GM21AA (using OnePlus 7 Pro) the baseband is no longer detected causing SIM cards not to be seen by the system. I am not sure what further output or information you will need but I can provide anything that can help isolate the trouble (please be patient this is the first time I have submitted a bug). I have included a screenshot showing the issue with an activated and functioning SIM card inserted in the phone, (the S/N is blanked out by me but the rest of the image is as it appears on the phone) which clears after uninstalling Magisk.

Cell Model: GM1917 (OnePlus 7 Pro US Unlocked)
OS: Stock OnePlus OxygenOS 10.3.3.GM21AA (US/Global variant)
Additional ROMs: None
Magisk Version: 20.4 (20400)
Magisk Manager: 7.5.1 (267)

![Screenshot_20200611-132913~2](https://user-images.githubusercontent.com/63612447/84482188-4525c900-ac65-11ea-9e4d-f81122cc9c74.jpg)

**Comment by LCCR193** [comment]
I would recommend you to flash the stock rom, update the stock rom and then check if it is actually magisk causing the issues or the a buggy software update from oneplus and '(idk why this issue ocurs because I am pretty new to magisk I installed magisk for the first time on march 22nd and the next day magisk 20.04 was out so updated it and everything was fine after that I experimented with modules and today I created my github account)' so after updating your phone if everthing is working go ahead and install magisk once again and see if you get the issue you are facing and then post your outcomes.

**Comment by osm0sis** [comment]
#2872

**Comment by tallnatt** [comment]
It is the stock ROM that is flashed as I mentioned in the OP. I have updated to the most recent version of the stock ROM. It boots and works without Magisk. Installing Magisk again gives the issues I am seeing.

**Comment by osm0sis** [comment]
Reports that aren't using the latest Canary are immediately closed.

**Comment by tallnatt** [comment]
> Reports that aren't using the latest Canary are immediately closed. Try again and report back.


Thanks for this info. The new interface with the debug logs helped me isolate the cause. As I mentioned before this is the first time I have reported a bug so I am definitely a noob. In case anyone has the same issue for me it was the OOS Native Call Recording Magisk mod that was causing a crash and not allowing the rest of the services to load properly.
