### ISSUE TITLE
Phone and apps lag after installing magisk

### ISSUE THREAD

**Issue by superislam** [topjohnwu/Magisk#2879]
Xiaomi Redmi note 7 Lavender
Xiaomi.eu 11.6.20 beta miui 12 Android 10
Magisk modules: systemless host,busy box, energized
Problem: since the last 2 or 3 updates phone started to be laggy apps became slow some apps are not responding (ANR) so i waited for today update i flashed it without magisk and i found the problem fixed so i install magisk but the phone lags again

**Comment by superislam** [comment]
Why closing?

**Comment by HerendraTJ** [comment]
After figuring out , I think we should or someone else create a magisk module to fix this issue:
The lag is cause due to insufficient RAM in your phone, and I don't know why it's happened. 

1. First of all download this patch
https://github.com/fawazahmed0/Magisk-lagfix-realme3/releases/latest/download/magisklagfix.sh
2.
Download any termux / terminal console on playstore (Authorize root perms)
3. Type this in command
su
mkdir -p /data/adb/service.d && cp /sdcard/magisklagfix.sh /data/adb/service.d/ && chmod +x /data/adb/service.d/magisklagfix.sh


It says it's only for realme device but surprisingly works also with Mi A2.

**Comment by DanGLES3** [comment]
Simple, without logs Topjohnwu can't do anything, saying you have an issue without providing proper information isn't useful in fixing the issue
