### ISSUE TITLE
MagiskHide app list preferences is not saved (290)

### ISSUE THREAD

**Issue by Displax** [topjohnwu/Magisk#2992]
Not sure, if it`s visual bug or it is not working at all. Different behavior in different situations.

Logs here:
[log.txt](https://github.com/topjohnwu/Magisk/files/4933976/log.txt)
[magisk.log](https://github.com/topjohnwu/Magisk/files/4933993/magisk.log)

**Comment by Displax** [comment]
Reference to https://github.com/topjohnwu/Magisk/issues/2987

**Comment by osm0sis** [comment]
Visual bug, I believe, since downgrading to 289 shows the intact list.

**Comment by etofi** [comment]
How can I downgrade to 289?

**Comment by No-WaY-SA** [comment]
hello,
I have a problem with canary version on S10+ g975f and S8 g9550
the last working manager is version 282 after ward I got dtbo patched with magisk manager with each reboot so i have to flash fw again and got the problem again.
with veriosn 290 i cannot got update to be loaded so i cannot make magisk hide because it cannot load the apk and got error
and i think if it fixed i will get DTBO patched error again!!
any solution for that?

**Comment by No-WaY-SA** [comment]
so my issue closed , I wished to get some help

with regards

**Comment by fsevenm** [comment]
In my side, Magisk app/package checklist is persisted, but MagiskHide option is disabled (again) after reboot. Need to manually hit the switch in Settings for it to be enabled. Any clues?
