### ISSUE TITLE
SafetyNet fails even with only core enabled in magisk 13.3

### ISSUE THREAD

**Issue by gundopanth** [topjohnwu/Magisk#302]
Snet didn't pass in 13.1/2/3.Last time it passed was in 12.0
Try to disable and enable magiskhide through terminal.Help!!

Device:Redmi Note 3 kenzo
Rom:MIUI 8.5.2.0
Stock boot image: http://s000.tinyupload.com/index.php?file_id=36529834505206556451

**Comment by Ante0** [comment]
Same issue here, it stops after init ns
https://github.com/topjohnwu/Magisk/issues/298

**Comment by Ante0** [comment]
Can you try this in a terminal
su
ps | grep zygote

**Comment by gundopanth** [comment]
u0_a183@kenzo:/ $ su
root@kenzo:/ # ps | grep zygote
root      499   1     6532   588   __skb_recv 7fa49677ac S zygote
root      784   1     2140492 29508 poll_sched 7f82e99d74 S zygote64
root      785   1     1568928 14052 poll_sched 00f70afe64 S zygote
root      3041  785   36088  476   futex_wait 00f708390c S xposed_zygote_service
root@kenzo:/ #

**Comment by Ante0** [comment]
Hmm. Is xposed the new one for Nougat released yesterday?

**Comment by coderobe** [comment]
xposed is probably gonna trip safetynet even in core only mode.

**Comment by JpegXguy** [comment]
same here on my P8 Lite. basicintegrity passes, but not cts profile. Core only enabled. I don't mind though as i don't use Safetynet apps. I chooce magisk as my root solution because it's open source and maintained

**Comment by gundopanth** [comment]
SafetyNet fails with only core enabled even when there is no magisk module like xposed installed

**Comment by coderobe** [comment]
@gundopanth xposed_zygote_service hints at an xposed install outside of magisk, if you're in core-only mode like you said - confirm you don't have xposed installed on the device (not just as magisk module)

**Comment by gundopanth** [comment]
I have no xposed installed

**Comment by bielik01** [comment]
I have the same problem
![screenshot_20170720-090903](https://user-images.githubusercontent.com/920950/28455529-a5b59478-6dff-11e7-8e7d-9b26b3096ced.png)

u0_a139@lux:/ $ su
root@lux:/ # ps | grep zygote
root      421   1     1249676 11812 poll_sched b6d270d4 S zygote
root@lux:/ #

Device: Moto X Play XT1562
Android version: 6.0.1
Baseband version: M8936_2020632.44.03.21.57R LUX_EMEA_CUST
Kernel version: 3.10.49-gf0dab7f
System version: 24.61.52.lux_reteu.en.EN reteu
Build number: MPD24.107-52

**Comment by Ante0** [comment]
@bielik01 is it stock kernel? If so that might be the problem. Hide needs kernel 3.8+ in most cases. My OnePlus One has kernel 3.4 but the things needed by hide was backported. If you can try switching out for a custom kernel (my opo uses fransico kernel so that might work if it exists for your device).

**Comment by bielik01** [comment]
Yes, it is stock. I don't have any problems with Magisk Hide (Andoid Pay works perfectly).
It's only the red crosses that annoy me (with SafetyNet Check Success).
It didn't look like this on previous version of Magisk Manager (5.0.6)

**Comment by Ante0** [comment]
Hmm. So red crosses might not mean it failed? I guess you could change out the red cross icons for the green ones, then rebuild xD

**Comment by bielik01** [comment]
I don't know what it could mean. I just installed apk topjohnwu provided.

**Comment by coderobe** [comment]
@bielik01 update magisk, you're running an old version

**Comment by bielik01** [comment]
ah, there's another problem
![screenshot_20170720-090015](https://user-images.githubusercontent.com/920950/28479209-b71d1590-6e5b-11e7-8580-8824fb040873.png)

**Comment by Ante0** [comment]
Write, in a terminal:
getprop ro.build.version.sdk

**Comment by bielik01** [comment]
23

**Comment by Ante0** [comment]
Try flashing in TWRP

**Comment by bielik01** [comment]
Will try that.

**Comment by bielik01** [comment]
Yeah, works like a charm. ;)

**Comment by gundopanth** [comment]
For me Safetynet fails no android pay no pokemon go nothing

**Comment by gundopanth** [comment]
It last worked on magisk v12

**Comment by whiteShadoww5** [comment]
Same here, Redmi 4 (india) or 4X (global), clean flashed the stock rom with mi flash and flashed Magisk 13.3 through TWRP 3.1.1 official, and yet my safetynet fails, and my bank app doesn't work because the it sees the phone is rooted. Funny thing is, it doesn't even ask me for root permission before detecting root.

**Comment by DJilaniE-070** [comment]
Someone found a fix? Even universal fix for safety net module doesn't work with magisk 13.3.
I am on mate 9

**Comment by gundopanth** [comment]
Nope no fix for safetynet

**Comment by Ante0** [comment]
@DJilaniE-070 check if you can get it to pass by enabling USB debugging then disable and enable hide. For me it does that now, it used to work just fine. Also if you're on a recent build SafetyNet might not pass anyway, as the build might not be approved by Google yet.

**Comment by gundopanth** [comment]
Nope im on a proper stable Safetynet build because on removing magisk safetynet passes and even usb debugging switching doesn't help

**Comment by Ante0** [comment]
@gundopanth it was not directed at you. I asked @DJilaniE-070 because I too have a Mate 9 with maybe similar problems.

I did some testing, C432B190 for my phone worked fine. Flashed C4342B193, had to enable USB debugging after each reboot to get safetynet working. Flashed back B190, problem persists. Flashed B194, problem fixed itself until yesterday. I think something is up with Emui not keeping usb debugging enabled. I even have to go to dev options each time to use adb as I have to manually enable usb debugging.
