### ISSUE TITLE
Can magisk no longer need unlock bootloader?

### ISSUE THREAD

**Issue by gfzhy** [topjohnwu/Magisk#3029]
my phone can not unlock  bootloader,but I want to use magisk very much,so   I hope  one day magisk  no longger need unlock bootloader. MY Phone: Smartisan  Nut Pro3.

**Comment by gfzhy** [comment]
Then   anyone  can use magisk

**Comment by Didgeridoohan** [comment]
The unlocked bootloader is generally necessary to be able to modify your device, in whatever way. It's not a specific Magisk requirement, and not something that can be "fixed" by Magisk.

There are devices that can do modifications without unlocking the bootloader, but it usually need exploits that can be quite rare.

If there's a community for your device somewhere, that's where you need to take this query; how to unlock the bootloader or flash a modified boot image with the bootloader still locked.

As stated: not a Magisk issue. Please close so that John or Chris doesn't have to.
