### ISSUE TITLE
Canary Manager: Magisk not installed? Somewhat ...

### ISSUE THREAD

**Issue by SgtSeppel** [topjohnwu/Magisk#3158]
Hi there, 

after updating my Google Pixel 3XL to Android 11 today, I tried installing the latest magisk canary, as this is supposed to support Android 11 already. 
I downloaded the stock image, copied over the boot.img, patched it, copied it back to the PC, flashed it and soft-bricked my device. 
No idea what went wrong but even flashing back the stock boot.img to both slots did not resolve the issue. 

I flash-all.bat'ed the whole phone and wanted to try a clean system. 
Did the patching again, flashed the magisk_patched.img to both slots and the phone boots fine.

Magisk manager does not show the install button anymore but does not show an installed version. Also the toolbar on the bootom shows "No connection availalbe" and the logs are empty.
Tried again several times, always the same outcome.

![Screenshot_20200909-145856](https://user-images.githubusercontent.com/10022598/92601691-6cfceb00-f2ad-11ea-9de2-bec0caa599bd.png)

As mentioned, I can not provide any logs.

**Comment by scottismyname** [comment]
Same issue here.  Instead of:
fastboot flash boot magisk_patched.img

I tried fastboot boot magisk_patched.img

This enables the system to boot, but as you stated it shows that magisk is not installed.  Perhaps google changed something in the final release that needs to be fixed.

**Comment by scottismyname** [comment]
Ok I think I figured it out.

Here are my steps:
1) Make sure all versions of magisk are uninstalled.  I believe my problem is that I had the stable version installed (and hidden).  Then when I installed the canary version, it installed seperately since the package names are different.
2) Install latest canary version
3) Patch boot.img file as normal.  
4) Download patched boot file to your computer
5) Reboot to bootloader
6) **Boot** patched boot image (flashing resulted in a bootloop for me):
fastboot boot magisk_patched.img
7) Once booted up, go to magisk manager and verify it's installed. 
8) Install magisk again (direct install method).  This is necessary since this actually modifies the boot.img file.  When you fastboot boot you are not changing the boot image.
9) Reboot.

You should still have magisk installed.

**Comment by ammmze** [comment]
I do recall running into a similar issue last year with android 10. Having multiple magisk managers installed makes things go wonky.

**Comment by ammmze** [comment]
I haven't made the jump to A11 yet...does safety net pass now that you've got magisk installed?

**Comment by scottismyname** [comment]
Yes, safetynet is passing

**Comment by SkeleBones** [comment]
> Ok I think I figured it out.
> 
> Here are my steps:
> 
> 1. Make sure all versions of magisk are uninstalled.  I believe my problem is that I had the stable version installed (and hidden).  Then when I installed the canary version, it installed seperately since the package names are different.
> 2. Install latest canary version
> 3. Patch boot.img file as normal.
> 4. Download patched boot file to your computer
> 5. Reboot to bootloader
> 6. **Boot** patched boot image (flashing resulted in a bootloop for me):
>    fastboot boot magisk_patched.img
> 7. Once booted up, go to magisk manager and verify it's installed.
> 8. Install magisk again (direct install method).  This is necessary since this actually modifies the boot.img file.  When you fastboot boot you are not changing the boot image.
> 9. Reboot.
> 
> You should still have magisk installed.

This just leads to me getting stuck booting up

**Comment by topjohnwu** [comment]
Latest Magisk canary is working on Android 11 on Pixel 3 XL, this is an user error

**Comment by SgtSeppel** [comment]
I did again a fresh install of Android 11. 
Following the same steps it's working now. 
No idea what went wrong the previous tries ...
