### ISSUE TITLE
Magisk Manager: "Select and patch file" leads to UI loop in low memory situations

### ISSUE THREAD

**Issue by d4rken** [topjohnwu/Magisk#3215]
Tested with current master (https://github.com/topjohnwu/Magisk/commit/ee4db431363002df2160c64bd4a0282d5cf6a59a)

When we open the file picker here:
https://github.com/topjohnwu/Magisk/blob/master/app/src/main/java/com/topjohnwu/magisk/ui/install/InstallFragment.kt

our activity is moved to the background and on low memory devices (or if you enable "Don't keep activities" in the dev settings), it may be removed from memory.

Upon returning to Magisk Manager (after selecting something in the file picker), the radio button for "Select and patch file" is no longer selected and we can't continue, pressing radio button again, opens the system's file picker again.

We could either persist the UI state via `savedInstanceState` or possibly just set the radio button again when we return [`onActivityResult`](https://github.com/topjohnwu/Magisk/blob/master/app/src/main/java/com/topjohnwu/magisk/ui/install/InstallFragment.kt#L20), AFAICT it would have been the only way to return there, so just checking the radio button again would be an okay workaround.

**Comment by d4rken** [comment]
If you want, I can submit a PR for either approach, let me know.

**Comment by topjohnwu** [comment]
@d4rken this is actually tricky, because we need to also preserve the user selection in options. How would you overcome this?

**Comment by d4rken** [comment]
Not sure what you mean by "options", can you link the relevant code parts?

As far as I understood it, we just need to know the radio button position until the end of the "install flow", possible even less, after pressing "continue" and it starts patching the `boot.img`, the radio selection is irrelevant, isn't it?

Edit:
There actually two issues going on. The radio buttons themselves are already persisting their checked state and it's automatically restored, but this restoration triggers the `onCheckedChanged` callback again, which triggers the FilePicker again (`RequestFileEvent().publish()`), and then the UI state is lost.

So I think the best fix here is to prevent the programmatic restoration of `android:checkedButton` from triggering the `onCheckedChange` logic again.

**Comment by d4rken** [comment]
The above PR (#3216) restores the state and prevents the automatic restoration from triggering the onChangedListener from automatically firing and causing the loop.

**Comment by topjohnwu** [comment]
@d4rken thanks for the PR. By option I mean the advanced option section (the user selection will be stored in `Config.recovery/Config.keepVerity/Config.keepEnc`, which is an Kotlin object that lives with the process lifetime).

You might not see this in your case because on modern devices all options will be skipped to protect the user from messing up their own device

**Comment by d4rken** [comment]
I've just tested it a bit (edited layout to show the options on my device) and the config options were not affected by the original issue, and my solution also does not affect them.

**Comment by zgfg** [comment]
Not sure if it is related to but since the latest Canary 301/20427, it patches the image to the full size, padding zeroes to the end.

E.g., for my device (Xiaomi Mi 9T, MIUI 12/Android 10) it means that the new patched images are full 128 MB size, while with older Magisk versions they were only 16 MB.
For some, that change may trigger the Low memory situation (more often then before)
