### ISSUE TITLE
Not working for me! OTA Update from 10 to 11. Pixel 4 XL

### ISSUE THREAD

**Issue by Zandersig** [topjohnwu/Magisk#3219]
When I try to install the Magisk I keep getting this error...

- Device platform: arm64-v8a
- Copying image to cache
2026+0 records in
2026+0 records out
2074624 bytes (1.9 M) copied, 0.003952 s, 501 M/s
1381+1 records in
1381+1 records out
1415016 bytes (1.3 M) copied, 0.003195 s, 422 M/s
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
- Unpacking boot image
! Unsupported/Unknown image format
! Installation failed

I got the Manager installed (version d6dbab53) but it will not install the Magisk (the top installation in Magisk app (version 

I've noticed that when I go to install the file that Magisk downloaded it's a zip file but Magisk is asking me to select a img file or a tar file! Why is Magisk app downloading a . zip file? No wonder it's failing to install. Where do I get that .img file from since Magisk app is not downloading it? Magisk us downloading this file for some reason.... "Magisk-d6dbab53(20427).zip"!

**Comment by Didgeridoohan** [comment]
That zip file is for installation through TWRP. If you are not already rooted, and there is no TWRP for your device, you need to use the "Patch file" option. There you need to use your device's boot image that you extract from the factory image, not the Magisk installation zip.

It doesn't sound like you've read them, so I'll link you the installation instructions:
https://topjohnwu.github.io/Magisk/install.html

Please close this so that John or Chris doesn't have to. Github issues aren't for general support... Go to XDA for that kind of stuff.
