### ISSUE TITLE
MM cannot open after repacking [ 308 (12)]

### ISSUE THREAD

**Issue by Displax** [topjohnwu/Magisk#3297]
Reported in log:
```
10-08 14:10:51.874  2021 11329 E A       : 
10-08 14:10:51.874  2021 11329 E A       : java.io.FileNotFoundException: https://raw.githubusercontent.com/topjohnwu/magisk_files/canary/release.json
10-08 14:10:51.874  2021 11329 E A       : 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
10-08 14:10:51.874  2021 11329 E A       : 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
10-08 14:10:51.874  2021 11329 E A       : 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
10-08 14:10:51.874  2021 11329 E A       : 	at uR.O(:2)
10-08 14:10:51.874  2021 11329 E A       : 	at uR.y(:1)
10-08 14:10:51.874  2021 11329 E A       : 	at l.k(Unknown Source:2)
10-08 14:10:51.874  2021 11329 E A       : 	at uR.g(Unknown Source:0)
10-08 14:10:51.874  2021 11329 E A       : 	at S.run(Unknown Source:6)
10-08 14:10:51.874  2021 11329 E A       : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-08 14:10:51.874  2021 11329 E A       : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-08 14:10:51.874  2021 11329 E A       : 	at java.lang.Thread.run(Thread.java:919)
```

Full log here: [log.txt](https://github.com/topjohnwu/Magisk/files/5347445/log.txt)

**Comment by zgfg** [comment]
If on Xiaomi, have you enabled Developer Option/Install over USB - needed for pm install as used for repackaging

**Comment by zgfg** [comment]
Indeed, with Canary Magisk Manager 308, I cannot hide/repackage Magisk Manager no matter how I enable/didable Install over USB and/or Verify apps over USB.
Also, enabling Install from unknown source for the Manager and later stub, does not help

It only installs the stub, showing its icon on the Home screen.
Stub (under the renamed Magisk Manager's name) can be only opened with black window in the background - cannot be brought to foreground, as on the screenshot

Logcat shows:
[Hide]
10-08 18:51:50.143 D/WindowProcessUtils(1734): remove task: TaskRecord{4b6c1fd #149 A=dng.oanaz U=0 StackId=-1 sz=0}

10-08 18:51:50.144 I/ProcessManager(1734): SwipeUpClean: kill dng.oanaz Adj=900 State=19

10-08 18:51:50.145 I/ActivityManager(1734): Killing 31230:dng.oanaz/u0a307 (adj 900): SwipeUpClean

10-08 18:51:50.149 E/TaskPersister(1734): File error accessing recents directory (directory doesn't exist?).

10-08 18:51:50.189 I/libprocessgroup(1734): Successfully killed process cgroup uid 10307 pid 31230 in 38ms

10-08 18:51:50.190 I/Zygote  (1023): Process 31230 exited due to signal 9 (Killed)

10-08 18:51:50.193 W/ActivityManager(1734): setHasOverlayUi called on unknown pid: 31230
[/Hide]
![Screenshot_2020-10-08-18-46-45-109_com miui home](https://user-images.githubusercontent.com/51943147/95494304-021efc80-099e-11eb-84ea-71a4ee2d7f1d.jpg)

**Comment by zgfg** [comment]
Follow-up:

1) Canary Magisk Manager 308, with Canary Magisk 21002, but with Update channel set to Stable, can be hidden/repackaged (I had: Play Protect On, Install via USB On).

As a result, hidden Manager dropped to 307 Beta, but it was repackaged!!!

Ofc, upon repackaging, Magisk remains 21002 and I can change Update channel to Beta

2) Similarly, Magisk Manager 307 Beta, with Update channel set to Stable, can be repacksged/hidden

3) Magisk Manager 307 Beta with Update channel set to Beta cannot be repackaged/hidden (similarly as Canary, with Update channel set to Canary)

---

Obviously, problem for repackaging e.g. Canary (with Update channel set to Canary) is in typo,  it looks for **unexisting Canary release.json** (log from @Displax as above):
https://raw.githubusercontent.com/topjohnwu/magisk_files/canary/release.json

Instead, it should look for Canary debug.json
https://raw.githubusercontent.com/topjohnwu/magisk_files/canary/debug.json

**Comment by Displax** [comment]
@zgfg 
> Obviously, problem for e.g. repackaging Canary (with Update channel set to Canary) is in typo, it looks for unexisting Canary release.json

Exactly. Actually, corresponding pull request was generated immediately.
https://github.com/topjohnwu/Magisk/pull/3298

**Comment by topjohnwu** [comment]
66cad101c00f722468d89c7aaa08c6b0123a6d34
