### ISSUE TITLE
Question about UI

### ISSUE THREAD

**Issue by RikkaW** [topjohnwu/Magisk#3358]
https://github.com/topjohnwu/Magisk/blob/7e133b0cf4522f2acadb722b653a975d8dfb6fb7/app/src/main/res/values-v21/styles_md2.xml#L4-L5

@diareuse Are there some special reason to use 4.4-style transparent system bars on 5.0+?

In my opinion, this looks weird and super ugly. And on some 💩 systems like MIUI, the 4.4 overlay color is changed to transparent, results in white status bar and white icons.

**Comment by diareuse** [comment]
No special reason really. Main point was to create edge-to-edge experience all the way down to 5.0.

I agree that some moronic developers of some Android forks don't really adhere to the principals and docs that Google clearly states, and that's certainly annoying.
It needs to be tinkered with in runtime to fix the visibility issues - notably MIUI can be easily fixed by setting the dark mode to always on so the status bar is _at least_ visible. Dunno if it still works though.

You can pm me with these questions on tg so we don't spam issues with questions 🙂
✌️

**Comment by RikkaW** [comment]
In fact, I personally don't care about MIUI at all. The main problem is 4.4-style transparent is SUPER UGLY, why we need to hurt the eye of 99.999% of users for the "edge-to-edge experience"?

**Comment by diareuse** [comment]
That's down to personal preference, I guess. I find filled bars super ugly and the translucent bars are just a bit better.

**Comment by vvb2060** [comment]
You think this is a spam issues?  Are you sure you want 99% of users to endure 4.4-style? Just because you personally like the translucent status bar?

**Comment by Howard20181** [comment]
> That's down to personal preference, I guess. I find filled bars super ugly and the translucent bars are just a bit better.

Can we use the 4.4-style transparent when the system version is lower than Android 5 , and a new way in 5.0+ to ensure the highest compatibility?

**Comment by diareuse** [comment]
First of all @vvb2060 clearly misunderstood the intention to move these kinds of conversations to PMs. And this is exactly the reason why I suggested it in the first place. I don't have the mental capacity to deal with outright offense like this, I'm inclined to make changes based on rational feedback.

Secondly, I have no idea where did you get these qualified numbers like "99% of users". Magisk as far as I know doesn't collect any statistics, so I have no way of knowing the user base. I would really love to have the insight you have, please do share. 🙂 

---

> Can we use the 4.4-style transparent when the system version is lower than Android 5 , and a new way in 5.0+ to ensure the highest compatibility?
Translucency is not used on pre-5.0 since the API to handle those changes is not available until 5.0. There's no "new way" until Android 10 iirc.

**Comment by vvb2060** [comment]
![Android 4.4](https://user-images.githubusercontent.com/26996262/96288559-2f128580-1016-11eb-8af2-c01e97f37b94.PNG)

**Comment by RikkaW** [comment]
No one says the opposite of 4.4-style is "filled". I actually agree that translucent bars are good, but for me, the 4.4 overlay color is a little dark. With the 5.0+ method, you can do anything you want, of course including translucent. Plus, for gesture navigation from Android 10, everyone should agree that the navigation bar must be transparent. It's really not necessary to keep visual the same across all versions.

> There's no "new way" until Android 10 iirc.

Can you tell what is the "new way" from Android 10?

**Comment by diareuse** [comment]
I can agree with you on that.

"new way" is full support for edge-to-edge.

**Comment by RikkaW** [comment]
5.0 (21):
statusBarColor
navigationBarColor

6.0 (23):
windowLightStatusBar

7.0 (24):
windowLightNavigationBar

8.1 (27):
navigationBarDividerColor

10 (29):
enforceStatusBarContrast
enforceNavigationBarContrast

7.0 is enough for "modern visuals".
