### ISSUE TITLE
magisk 13.3 not work with termux!

### ISSUE THREAD

**Issue by C4droid** [topjohnwu/Magisk#347]
In Termux, I use 'tsu' to get root, but there is not any effect.
I do it with aospExtended and RR ROM ,both bad result.

**Comment by jenslody** [comment]
I would say it's a termux issue, because "su" itself works fine.
And it definitely works with the "su" from termux not any other probably in path (dircetly called with "/data/data/com.termux/files/usr/bin/su".
But "tsu" searches for "su" only in two hardcoded paths ("/system/xbin/su" and "/su/bin/su") instead using its own su, which searches in "/system/xbin/su", "/system/bin/su", "/su/bin/su", "/sbin/su" and "/magisk/.core/bin/su".
