### ISSUE TITLE
Patched img don't work (bootloop) on Lenovo M10 Plus TB-X606F

### ISSUE THREAD

**Issue by mccoy88f** [topjohnwu/Magisk#3506]
Hi and thanks for this great job.
On previous version (Android 9 it works) now after updating to latest version (Android 10) it put my device in bootloop.
I use beta and stable version of Magisk but doesn't work.
This is original firmware: TB-X606F_S300007_200923_BMP.zip
Link: https://mirrors.lolinet.com/firmware/lenovo/Tab_M10_FHD_Plus_2nd_Gen/TB-X606F/
Thanks a lot
Waiting for your answer

**Comment by fredrik1102** [comment]
It's not Magisk fault, all you have to do is flash vbmeta.img from your TB_X606F_S300007_200923_BMP.zip
with this command:
fastboot --disable-verification flash vbmeta vbmeta.img
And your device will boot again with Magisk patched boot.img and you'll be rooted.
You need to use Magisk 20.4, for some reason 21.0 and 21.1 doesn't work with TB_X606F_S300007_200923_BMP.zip

**Comment by mccoy88f** [comment]
Thanks a lot It works
Flash First patched boot image
And the vbmeta from official zip image

**Comment by theking8713** [comment]
yes the vbmeta.img did the trick for me as well and i also used the newest magisk i know i did because i update the apk from the app before i patched the stock boot.img...now i just haf to remember this little extra step for when i inevitably haf to do this again 50 times down the road after going back to stock a dozen times lol
