### ISSUE TITLE
bank app detects root

### ISSUE THREAD

**Issue by eraser989** [topjohnwu/Magisk#3556]
Hi there
I am on LOS17, my bank app forced me to update, then it started detecting root
it was hidden through magisk, the safteynet is passed
deleted twrp folder
uninstalled - reinstalled
used island
no luck

if someone can check the app please
https://play.google.com/store/apps/details?id=com.ducont.muscatbank&hl=en&gl=US

**Comment by sebkap** [comment]
Did you rename magisk manager package in Magisk?

**Comment by eraser989** [comment]
> Did you rename magisk manager package in Magisk?

Yes, long waybefore 
No solution helped

**Comment by techIndia-hacker** [comment]
It's working fine. Apply hide policies properly. I went till the login signup page

**Comment by zgfg** [comment]
There is the whole chapter with various possible tips to tty (not just hiding MM) in Wiki pages (limk also here from Github)

IMO, this is not the topic for opening a ticket here Some apos may e.g.conclude that phone is rooted because they find Titanium installed, or TWRP folder, or Xposed - Magisk has nothing with that

**Comment by techIndia-hacker** [comment]
Close it
