### ISSUE TITLE
Magisk 14 installer, what changed?

### ISSUE THREAD

**Issue by DimitriDokuchaev** [topjohnwu/Magisk#358]
Afternoon guys.

So I am reporting a bug regarding the Magisk and its compatibility with dualbootpatcher, while I don't expect @topjohnwu to actually fix this, I would love to have some insights on what changed from magisk 13.3 to 14 regarding the installer.

Don't know if you are familiar with how dualbootpatcher works but basically it modifies zip files to install themselves on a chroot environment of your choosing.
You can install pretty much everything like this and magisk until 13.3 worked wonders.

Now with magisk 14 i just get an error that it cant mount system.

Here are the twrp logs for magisk 14: 
https://gist.github.com/anonymous/30f523ebda4803bf9c9b31d0f6fa0df4

and here are the twrp logs for magisk 13.3:
https://gist.github.com/anonymous/84122cc62bccc2309b8406637181d6ee

While i do not expect you to fix this, a explanation of what changed in the way it installs would be helpful to see if i could modify it, or if you could point me in the right direction.

I am just starting with android development, hopefully you could give me a hand on this.

**Comment by Zackptg5** [comment]
Odd. Nothing has changed in this regard between magisk 13.3 and 14. The error your getting only happens when system/build.prop is not found. The lines for this and the system mounting is identical between 13.3 and 14. The only difference is that 13.3 uses update-binary while 14 uses updater-script. You could try comparing the two and switching stuff back to update-binary to see if it changes anything. You'll probably have to make some syntax changes though
