### ISSUE TITLE
步步高家教机刷21+版本卡第一屏

### ISSUE THREAD

**Issue by skaozk** [topjohnwu/Magisk#3607]
我目前使用的设备是步步高家教机S5，系统版本为1.3.0，安卓版本为9.0
在从20.4更新到21+版本后均出现了卡第一屏的情况(经排查确定是21006后才出现这一问题)，直观表现为屏幕上不断闪过步步高logo，进rec刷回20.4版本即可正常开机
附上
[启动日志](https://github.com/topjohnwu/Magisk/files/5743098/liveboot.log)，望大佬们能修复这一问题

**Comment by Hickoo** [comment]
哪里不会点哪里

**Comment by skaozk** [comment]
> 哪里不会点哪里

~~确实~~

**Comment by topjohnwu** [comment]
Please try again on the latest canary build. If the issue persists, please open a new issue, following the new instructions in the issue template.

**Comment by kistonw** [comment]
> 我目前使用的设备是步步高家教机S5，系统版本为1.3.0，安卓版本为9.0 在从20.4更新到21+版本后均出现了卡第一屏的情况(经排查确定是21006后才出现这一问题)，直观表现为屏幕上不断闪过步步高logo，进rec刷回20.4版本即可正常开机 附上 [启动日志](https://github.com/topjohnwu/Magisk/files/5743098/liveboot.log)，望大佬们能修复这一问题

大佬 你的s5有刷机包吗

**Comment by mishi1927** [comment]
no i can'tSent from Android device2025年2月16日 14:43，王增虎 ***@***.***>写道：
  
我目前使用的设备是步步高家教机S5，系统版本为1.3.0，安卓版本为9.0 在从20.4更新到21+版本后均出现了卡第一屏的情况(经排查确定是21006后才出现这一问题)，直观表现为屏幕上不断闪过步步高logo，进rec刷回20.4版本即可正常开机 附上 启动日志，望大佬们能修复这一问题

大佬 你的s5有刷机包吗—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>



kistonw left a comment (topjohnwu/Magisk#3607)

我目前使用的设备是步步高家教机S5，系统版本为1.3.0，安卓版本为9.0 在从20.4更新到21+版本后均出现了卡第一屏的情况(经排查确定是21006后才出现这一问题)，直观表现为屏幕上不断闪过步步高logo，进rec刷回20.4版本即可正常开机 附上 启动日志，望大佬们能修复这一问题

大佬 你的s5有刷机包吗
