### ISSUE TITLE
Magisk Hide Reset Check Marks and Won't Hold them Now

### ISSUE THREAD

**Issue by slidingbilly** [topjohnwu/Magisk#3695]
I took 21202 Magisk and 4814 Manager on my 3XL.  All hide checks were cleared, and now they won't hold after rechecking and backing out of the app/re-entering hide.

**Comment by topjohnwu** [comment]
Logs or nothing will happen

**Comment by lss4** [comment]
OS: [Nusantara GSI v2.5.1 (Android 11)](https://sourceforge.net/projects/amber-gsi/files/Nusantara-11/)

NOTE: Android 11 GSI users need to follow the instructions mentioned in #3593 for proper installation, although details vary among different GSI builds and may or may not work.

Can confirm this is happening on 21202 Canary and Manager version 4814.

After configuring Magisk Hide, when going back, the following can happen with varying chances:
1. Everything I've checked before appears checked as intended. (low chance)
2. Some entries I've checked becomes unchecked. Some unchecked entries are random while others not. (common case)
3. All entries I've checked becomes unchecked. (low chance)

However, I'm suspecting this might be purely an UI issue, as Magisk Hide itself appear to work as intended. An app that would usually give me a toast to warn me the device being rooted did not warn me after checking it in Magisk Hide, despite it now appears unchecked most of the times.

Also, the checkbox's behavior is a bit incorrect. I need to expand the app before toggling the main checkbox to ensure everything about that app would be checked. Otherwise, it'll only check the first entry. Also, when not expanded, the app's main checkbox would appear "fully checked" [v] regardless of whether everything about the app has been checked or not. For some apps (microG DroidGuard Helper as an example), the behavior is a bit different: The main checkbox would remain unchecked even when some or all of the underlying toggles have been switched on.

I'm getting very few logs in logcat, and my Magisk log is empty. This happens in logcat from time to time.

```
01-15 09:58:10.997   951 23538 E Magisk  : write failed with 32: Broken pipe
01-15 09:58:11.003   951 23538 I chatty  : uid=0(root) magiskd identical 280 lines
01-15 09:58:11.003   951 23538 E Magisk  : write failed with 32: Broken pipe
```

Other than these, I noticed this line which I suspect it might be related as superuserFragment is probably where I can enter the Magisk Hide screen.

```
01-15 09:58:46.543 11227 11227 I NavController: Ignoring popBackStack to destination com.topjohnwu.magisk:id/superuserFragment as it was not found on the current back stack
```

Other than that I found nothing helpful. Is there anything needed in order to get log outputs when using Android 11?
