### ISSUE TITLE
Modules are not loading in PhoenixOS PC

### ISSUE THREAD

**Issue by HemanthJabalpuri** [topjohnwu/Magisk#3760]
@topjohnwu
I have installed 21.4 in Phoenix OS 3.6.1 official for PC x86_64 with the help of https://github.com/shakalaca/MagiskOnEmulator.
Root is working fine, but modules are not loading.

Magisk log and bootlog are attached.

[magisk_log_2021-01-24T21:06:48Z.log](https://github.com/topjohnwu/Magisk/files/5899234/magisk_log_2021-01-24T21.06.48Z.log)
[bootlog.log](https://github.com/topjohnwu/Magisk/files/5899235/bootlog.log)

Logs with 22001
[magisk_log_2021-02-27T19:28:03Z.log](https://github.com/topjohnwu/Magisk/files/6054428/magisk_log_2021-02-27T19.28.03Z.log)
[magisk_log_2021-02-27T19:16:51Z.log](https://github.com/topjohnwu/Magisk/files/6054429/magisk_log_2021-02-27T19.16.51Z.log)

**Comment by JonyWinner** [comment]
Maybe try to flash older version

**Comment by HemanthJabalpuri** [comment]
Also sometimes I get 'Not a Magisk module error', even it is a working one in 21.4. In 21405 Canary it shows 'Unzip error'.

**Comment by HunterInMyZone** [comment]
Use bliss os instead

**Comment by HemanthJabalpuri** [comment]
> Use bliss os instead

But PhoenixOS is newbie(like me) friendly. It does not have to partition for installation, pain with uninstalling etc., It is like Wubi for Ubuntu. So many choose PhoenixOS among others.

Thanks

**Comment by hmtheboy154** [comment]
you may wanna try this

**Comment by etmatrix** [comment]
have you tried the patch "Install Magisk On Android x86 Project on VirtualBox"? I had the same issue, with patch scripts developed by shakalaca for Android x86, it's works.

**Comment by HemanthJabalpuri** [comment]
> have you tried the patch "Install Magisk On Android x86 Project on VirtualBox"? I had the same issue, with patch scripts developed by shakalaca for Android x86, it's works.

Since I have directly installed PhoenixOS to harddisk instead in VirtualBox, I have to do some process manually.

I think PhoenixOS is somewhat different than Android-x86 even though it is based on it.

Thanks

**Comment by etmatrix** [comment]
The UI is different but the core is equal.
Virtualbox or PC are the same. Take inirt.img and ramdisk.img execute patch scrits on android and you got new and patched inirt.img and ramdisk.img so you can replace it.

**Comment by HemanthJabalpuri** [comment]
> The UI is different but the core is equal.
Virtualbox or PC are the same. Take inirt.img and ramdisk.img execute patch scrits on android and you got new and patched inirt.img and ramdisk.img so you can replace it.

That is what I did!

**Comment by etmatrix** [comment]
I tried to install PhoenixOS 3.6.1 from exe on Windows 10 (VirtualBox). I tested Magisk 21.4 last with zip and I used my instructions [here](https://github.com/topjohnwu/Magisk/issues/2551#issuecomment-608998420) as reported by shakalaca.
Module loading works. I installed riru core and after reboot rirud start and I can see in the list of magisk modules.
Xposed doesn't work because doesn't support x86_64, EdXposed doesn't work because support from android 8.0 and we have an android 7.1.1.
I installed MagiskFrida and works, I can debg applications from my client.

**Comment by etmatrix** [comment]
My PC (virtual) has only one disk of 30GB. Windows 10 standard installation. Disk of Phoenix are in images system.img etc...
Could you post you patched ramdisk.img and initrd.img so I compare with mine?
In your logs I can't see errors.

**Comment by HemanthJabalpuri** [comment]
> Could you post you patched ramdisk.img and initrd.img

Will be available later today.

Thanks

**Comment by HemanthJabalpuri** [comment]
@etmatrix

Now I installed Magisk 22001. Installed Busybox, Terminal Mods, Energised modules. None of them loaded after boot.

Here are the patched images.

**Comment by etmatrix** [comment]
No diff in patching, there are some differences in binary because you use magisk 22 and my is 21.4.
In your log there is this part. Seem the modules are loaded.

```
02-27 19:24:48.376  1291  1292 D : bind_mnt: /sbin/.magisk/modules <- /sbin/.magisk/mirror/data/adb/modules
02-27 19:24:48.416  1291  1292 I : * Running module post-fs-data scripts
02-27 19:24:48.417  1291  1292 I : * Loading modules
02-27 19:24:48.417  1291  1292 I : energizedprotection: loading mount files
02-27 19:24:48.417  1291  1292 I : terminalmods: loading mount files
02-27 19:24:48.417  1291  1292 I : busybox-ndk: loading mount files

```

**Comment by HemanthJabalpuri** [comment]
> In your log there is this part. Seem the modules are loaded.

It seems loaded but not actually. I ran `busybox`, `ep`, `cdn` to test those.

I think this is where is actual issue comes
```
02-25 01:26:54.358  1285  1286 E : mount /sbin/.magisk/block/system->/sbin/.magisk/mirror/system failed with 16: Device or resource busy
```

Thanks

**Comment by etmatrix** [comment]
Also in my logs I have 

`E : mount /sbin/.magisk/block/system->/sbin/.magisk/mirror/system failed with 16: Device or resource busy`

**Comment by HemanthJabalpuri** [comment]
> Also in my logs I have

Then I have to wait for @topjohnwu to see my logs.

**Comment by justneedhelp** [comment]
I don't know about PhoenixOS, but I use Android x86_64 8.1.0 on top of VirtualBox and I can confirm that `Error 16: Device or resource busy` is present here. I don't know how to fix it. Tried installing Android x86 with both `/system` read-write and read-only.
All versions of Magisk started from 20.4 to 22.0 have these Errors in log:
![MagiskError](https://user-images.githubusercontent.com/79741381/109419612-a564c280-79ce-11eb-84af-b87988bd041e.png)

And moreover... it seems I found the reason of this problem (assuming I use Android x86 8.1.0 VirtualBox):
Output `cat /proc/mounts` shows me the following output:
![bug](https://user-images.githubusercontent.com/79741381/109425558-12855180-79e9-11eb-8065-8c29a847592c.png)
So, the devices are becoming busy after Android has booted so Magisk cannot remount them. I think we should somehow avoid `/dev/loop0` (system.sfs image) and `/dev/block/sda1` from mounting as Magisk mirrors in order to allow Magisk to mount mirrors from `/sbin/.magisk/block/`. I don't think topjohnwu is going to solve our issue because he thinks this is a Android x86 architecture issue, not Magisk itself. But somehow we need to find a way to solve this issue. Either modifying Magisk init script or Android x86 init ramdisk?

**Comment by HemanthJabalpuri** [comment]
> I can confirm that Error 16: Device or resource busy is present here.

Ok, what about modules? Are they loading?

I saw you issue in shakalaca's tool. I also have v22 not detecting root problem.

Thanks

**Comment by justneedhelp** [comment]
> Ok, what about modules? Are they loading?
No, they are not installing and loading at all. I tried to install MagiskHide Conf Props and when I tried to flash it I got an Error: Please install Magisk 20.4+ although I already installed it.

**Comment by HemanthJabalpuri** [comment]
> Error: Please install Magisk 20.4+ although I already installed it.

It may be because of Internet issue(?) Or **Additional Setup** problem(?).

I also have these issue before in Phoenix, I don't what I did to fix. But they are fixed😅

Thanks

**Comment by justneedhelp** [comment]
> Or **Additional Setup** problem(?).

Yes, I have this issue. Once I installed Android 8.1.0 I just taped 'Yes' and everything set up. But all other times, after reinstalling Android x86 on VirtualBox, I tap 'Yes' on Additional setup dialog and it reboots and appears again and again. Any way to fix it?

**Comment by HemanthJabalpuri** [comment]
> Any way to fix it?

I have this issue when I used rusty-magisk which is not resolved. See https://github.com/AXIM0S/rusty-magisk/issues/1

Thanks

**Comment by justneedhelp** [comment]
Whoa! I installed last canary version of Magisk and somehow modules worked! Tested on MagiskHide Props Config module.
Steps I did:

0. Assuming I use Android x86_64 (AOSP) 8.1.0 on top of VirtualBox. Installed a system from ISO with /system read-write
1. Enabled ADB debugging through developer options (5 tap click on build number in Android Settings)
2. Established ADB connection with PC via `adb connect Android-x86 IP address`
3. Download latest canary Magisk build from https://github.com/topjohnwu/magisk_files/tree/canary (app-debug.apk)
3. Git clone shakalaca scripts https://github.com/shakalaca/MagiskOnEmulator and follow steps described in https://github.com/shakalaca/MagiskOnEmulator#install-magisk-on-android-x86-project-on-virtualbox (don't forget to rename `app-debug.apk` to `magisk.zip`)
4. If you have previously Magisk version installed, then after installation Magisk Canary with steps described in 3. when you open Magisk app after reboot you will see this error:
![abnormal](https://user-images.githubusercontent.com/79741381/109541297-f30f2700-7ac3-11eb-8acf-2c0cd4494de9.png)
But don't worry! You can always use Command Line Interface instead of GUI, just open Terminal Emulator or `adb shell` and type `su` and then check that magisk was successfully installed by typing `# magisk -c`
5. Then, install module ZIP by typing `# magisk --install-module /path/to/your-module.zip`
6. Reboot.

Notice: first time I installed ZIP module through CLI, I didn't see any output and module was not installed. But after second reboot somehow I repeated the operation and now module (for example: MagiskHide Props Config) worked well!
You can start module just by typing `props` from Terminal Emulator or find it in `/data/adb/modules/MagiskHidePropsConf/system/(x)bin` folder. I don't guarantee this solution will work on your Android x86 distribution but this is the only solution I found after weeks of nightmare!

**Comment by etmatrix** [comment]
For me installation and loading of modules always worked after the work of shakalaca on MagiskOnEmulator for Android 8.1 X86. I tried many modules riru core, xposed, magisk hide prop config and others. Today I tried also LSPosed for a test and I installed from gui without issue. It's work with R4 and R5.
The error "Device or resource busy" is irrilevant for me.

**Comment by topjohnwu** [comment]
Running Magisk through an emulator is not officially supported, but PRs are welcome!
