### ISSUE TITLE
Magisk not handling DISALLOW_SAFE_BOOT flag

### ISSUE THREAD

**Issue by mat-io** [topjohnwu/Magisk#3776]
I have a feature request or need help with adding additional functionality to Magisk. On my phone I have enabled [DISALLOW_SAFE_BOOT](https://developer.android.com/reference/android/os/UserManager#DISALLOW_SAFE_BOOT) flag. Currently Magisk does not respect it. Even if the user is not allowed to safe boot, he can disable all the modules on magisk, which is the behavior that I want to prevent. It is because of `check_key_combo()` call in https://github.com/topjohnwu/Magisk/blob/master/native/jni/core/bootstages.cpp#L303

I think that developers for the sake of safety won't be interested in adding that to the code base. I've checked out the code and removed the  `|| check_key_combo()` from the if statement, which is simple way of disabling it permanenty. I don't know how to make it dependent on said DISALLOW_SAFE_BOOT flag, but maybe this will do.  I've successfully build the app. But the documentation doesn't say anything about how to prepare a flashable zip file. Could you provide me with instructions on how to prepare it? Or maybe you know how to read said DISALLOW_SAFE_BOOT flag and are interested in making Magisk support it?

**Comment by vvb2060** [comment]
I think this is meaningless. You should lock the bootloader and use [device attestation](https://developer.android.com/reference/android/app/admin/DevicePolicyManager#generateKeyPair(android.content.ComponentName,%20java.lang.String,%20android.security.keystore.KeyGenParameterSpec,%20int)) to verify the integrity of the devices managed by the organization. **Do not** allow employees to unlock the bootloader, which means they can do anything.

**Comment by mateuszbartosiak** [comment]
I agree, if one would use such policies on the device, it should not have unlocked bootloader. And yet, the device with unlocked bootloader can be set up in a way that disallows changes to the device before the system starts, or with using password protected recovery. And also there are ways of disabling access to administrative apps on the device once the system loads. I need exactly this setup. Let's imagine the scenario, when one phone is used by two people. They both need to know keyguard password to use it. But there are specific apps that can be accessed by only one of them. This can be solved by using for example with custom applocker like [MaxLock](https://github.com/Maxr1998/MaxLock). Magisk not respecting safe boot flag is the only way I can think of that the setup I've described can be bypassed. I understand that this requirement may seem rare or pointless. That's why I asked if you can help me with preparing flashable zip, so I can use that.

**Comment by vvb2060** [comment]
https://github.com/topjohnwu/Magisk#building-and-development
https://github.com/topjohnwu/magisk_files/blob/canary/notes.md

**Comment by mateuszbartosiak** [comment]
Github Actions, good to know! I've made a described change and now it works like a charm. Thank you for your help. Consider maybe adding a 2nd link and this Github Actions information to readme. As you've pointed out, handling this flag is probably not a feature anybody would use. I personally would be glad if this was an option on official release, but it's your call. Feel free to close the issue.

**Comment by ShashaankHari** [comment]
Can u share the file?

**Comment by mateuszbartosiak** [comment]
So maybe I am not the only one interested in this feature? The file is here: https://github.com/mateuszbartosiak/Magisk/releases

**Comment by osm0sis** [comment]
I think the entire idea is allowing users to get out of bootloops due to modules by providing a key combo to disable them all, and it wouldn't be smart to allow anyone to disable that.
