### ISSUE TITLE
OnePlus3T takes very long powering off with Magisk installed

### ISSUE THREAD

**Issue by cbdreinulldrei** [topjohnwu/Magisk#39]
My OnePlus3T running 6.0.1 (OOS 3.5.4) takes extremely long to power off. It's easy to show when I attach the charger - the blue charging light comes on. When I press the power button, I answer the popups. Then a circle starts spinning. When the circle vanishes, only the blue light stays lit. But it does not turn off for another 90 seconds. Even when I remove the charger. During this time, the phone technically is still on. So "turning on" does not work, I have to press the power button for more than 8 secs to turn it off, then turn it on again.

I must assume that some process hangs when the phone is turned off.

This does not happen when rebooting. Also the phone is fine when stock image only is installed.

**Comment by topjohnwu** [comment]
I experienced it on my device, but only when replacing the framework folder.
The issue seems to be that native reboot calls a series of function in the framework.
However during the process, /data is unmounted, so the boot down process is borked.
If it's the same issue I mentioned, I'm not sure if there is any possible fix

**Comment by cbdreinulldrei** [comment]
Seems to be "fixed" on Nougat...
