### ISSUE TITLE
EdXposed framework not properly installed after updating magisk to latest version

### ISSUE THREAD

**Issue by mindfreak0** [topjohnwu/Magisk#3904]
Version name: 22
Version code: 22
After updating Magisk, i got error msg on EdXposed manager : "EdXposed Framework is not properly installed" although i installed latest Riru and EdXposed master zip. Tried many earlier versions of framework but yet working.

**Comment by maxweisspoker** [comment]
It might be worth while to look at the Magisk logs in the app and see if it mentions a busybox failure, [like I had](https://github.com/topjohnwu/Magisk/issues/3898). The culript ended up being a script stuck in an infinite loop. See my last comment in that link for instructions on fixing it.

**Comment by techIndia-hacker** [comment]
Reflash riru reboot reflash edxposed reboot

**Comment by mindfreak0** [comment]
> It might be worth while to look at the Magisk logs in the app and see if it mentions a busybox failure, [like I had](https://github.com/topjohnwu/Magisk/issues/3898). The culript ended up being a script stuck in an infinite loop. See my last comment in that link for instructions on fixing it.

Thank you bro, the problem has been solved after i followed your solution.
I really appreciate your help.

**Comment by techIndia-hacker** [comment]
Close this if solved

**Comment by ruinetto** [comment]
> It might be worth while to look at the Magisk logs in the app and see if it mentions a busybox failure, [like I had](https://github.com/topjohnwu/Magisk/issues/3898). The culript ended up being a script stuck in an infinite loop. See my last comment in that link for instructions on fixing it.

After a long period in search of a solution for this, I finally got here! For a moment, I even thought I'd never get it on this new Android 11 because of the critical changes Google has implemented in its code. I would like to confirm that the fix presented by the brilliant @maxweisspoker worked **perfectly** on my device. I am extremely grateful for your discovery... Go for it!

![Screenshot_20210725-163108_EdXposed Manager](https://user-images.githubusercontent.com/54946608/126911244-5236bc21-d233-46b6-861d-8ffeae9dea3b.jpg)
