### ISSUE TITLE
Data wiped after Magisk 22.0

### ISSUE THREAD

**Issue by Polar-Zero** [topjohnwu/Magisk#3911]
Magisk 22.0 Auto-update FAILED and
After Reboot, My ALL of data wiped up & downloading.. screen appeared

Phone model: Galaxy Note 9

**Comment by techIndia-hacker** [comment]
🤣 all noobs. Whats ur os

**Comment by Polar-Zero** [comment]
maybe Android 10

**Comment by rokahaal** [comment]
> Magisk 22.0 Auto-update FAILED and
> After Reboot, My ALL of data wiped up & downloading.. screen appeared
> 
> Phone model: Galaxy Note 9

Same problem here. Oneplus 7 pro, crdroid v6 (Android 10), magisk v21.4; also magisk update failed, after reboot only boot to bootloader possible; no OS and no recovery installed, all wiped

**Comment by techIndia-hacker** [comment]
"Maybe"😂. Can u use Odin? Flash stock firmware. Extract boot.img from AP. Patch that using magisk app. Flash modified boot.img in boot.tar container

**Comment by rokahaal** [comment]
You can laugh as mutch as you want, but fact is I did nothing wrong. This Crap totally wiped my phone.

**Comment by Jon8RFC** [comment]
I'm pretty quick to update and risk problems, and I resolve them eventually. But last time, I had a hell of a time updating to either 21408 or 21409 on my sister's phone and getting hers back to normal afterward, because downgrading didn't work. I had to do a different version of incredibly helpful instructions I found by didgeridoohan. The instructions didn't work, but gave me ideas. I'm sorry for your losses, but that last near-disaster was a healthy warning for me to check bug reports this time. I wish I had an identical test phone handy, or knew specifics of these a/b partitions to make mirror copies and test.
