### ISSUE TITLE
Install failed after lastest update

### ISSUE THREAD

**Issue by thaript** [topjohnwu/Magisk#3923]
Install failed
Verification error

Samsung galaxy j max tab sm-t285yd

We need a flashable zip because we cant find the boot.img and we cant use direct install because of this error

**Comment by ipdev99** [comment]
I normally run the canary build. Since [Magisk (0646f48e) (21407)](https://github.com/topjohnwu/magisk_files/blob/9026f2ba50b3aa5389468a1837c6f001d4a6e2cb/notes.md#how-to-use-the-apk-for-recoveries), I have been renaming the apk file to zip and then flashing it in TWRP on older devices.

The installation guide was updated with the same instructions.
https://topjohnwu.github.io/Magisk/install.html#custom-recovery

If renaming the Magisk apk file to zip and then flashing, you will need to include logs.

**Comment by thaript** [comment]
Yes sir i tried installing process is done perfectly but magisk app is not
detecting the installed magisk version still its says use direct install or
boot img patching 😐
