### ISSUE TITLE
Magisk repo fails to load

### ISSUE THREAD

**Issue by arknote** [topjohnwu/Magisk#3932]
After upgrading Magisk and app to v22 on oneplus 7 pro, the app fails to communicate with the repository and fails to refresh online modules list. It also fails to download the changelog of installed modules.

**Comment by Didgeridoohan** [comment]
Can't reproduce... Check and make sure that you do not have anything that can block internet connections for the app (firewall app, custom hosts list, etc).

**Comment by PurpleVsGreen** [comment]
Had the same thing, it was due to not having certain root certificates enabled in the device security settings. Failing that, update them by rebooting into TWRP recovery, mounting /system, removing the .0 files in /system/etc/security/cacerts, and adb pushing new ones from [here](https://android.googlesource.com/platform/system/ca-certificates/+archive/master/files.tar.gz) (e.g. `adb push cacerts /system/etc/security` where `cacerts` is the directory on your pc that has the new .0 files). Of course this shouldn't be necessary as Android automatically does this in the background
