### ISSUE TITLE
looking for specific magisk canary build (20307, 72f6770d)

### ISSUE THREAD

**Issue by soft391** [topjohnwu/Magisk#3965]
@topjohnwu I'm looking for the specific release above because shakalaca's code has a blob in it from that release. This is a security question, not a technical support question. A device with sensitive data in our lab was flashed mistakenly before reading code thoroughly. 
Do you still have the canary build (20307) anywhere: I only see the main one? Any help here would be strongly appreciated and met with a small donation. shakalaca/MagiskOnEmulator#22

**Comment by sebkap** [comment]
You can build it yourself. 72f6770d is commit id. Pretty sure it is this one https://github.com/topjohnwu/Magisk/tree/72f6770d610bd47ff7f744c2b7dc7e4b0f49d6f1

**Comment by shakalaca** [comment]
1. I believe this is not Magisk related issue ;-)
2. No one will store sensitive data on official android emulator, unless you're playing game with 3rd party android emulator

you can always use your own busybox binary and replacing it should not be that hard since my script is way more simple than Magisk :)

**Comment by soft391** [comment]
Hey, @vvb2060 @shakalaca  why close this issue so rapidly. Obviously no one is throwing vm escapes around like candy, but why not just wait a second and give @topjohnwu at least a chance to throw this build our way: we have a policy not to execute blobs in this way and a junior guy made a mistake.
