### ISSUE TITLE
TWRP needs password

### ISSUE THREAD

**Issue by p6002** [topjohnwu/Magisk#4053]
TWRP needs password after updating to v22. My phone is bricked now.
Miui 12, Android 10, Xiaomi Mix 3.
Phone stop working after updating via Magisk app. How i can fix it fast? 
And don't delete my posts please.

**Comment by p6002** [comment]
fuck you

**Comment by Didgeridoohan** [comment]
GitHub issues is not for "fixing your phone". For that kind of stuff you have places like XDA where you've got tons of resources and information at your disposal.

**Comment by p6002** [comment]
Next time, test the application before you announce "big update".
I'll never use your crap app again. Just because of that.

**Comment by Didgeridoohan** [comment]
Of course it's been tested, but bugs happen.

Tone down the entitlement.

**Comment by Brazilhehe** [comment]
> Next time, test the application before you announce "big update".
> I'll never use your crap app again. Just because of that.

Hahaha You are stupid, you are the famous ball owner, if you don't play, nobody can play, the owner of the magisk works at Apple and he works on the magisk sometimes when he has some time left, he doesn't have the time to finish everything, that's why the magisk has bugs, also the magisk doesn't work with some APIs
Magisk works with a lot of APIs (so you can imagine how difficult it must be),
Also each phone has a different processor, stock rom, camera app etc, if the magisk was a regular app it wouldn't have all these problems, but since it is an app that modifies the Android system these bugs happen, but you can easily solve this by installing the magisk canary, where you get first updates that can solve bugs or bring more bugs,
So it's your choice.
I used a translator (translation can be wrong)
