### ISSUE TITLE
Bluetooth issue - Watch Active 2 stuck with finishing pairing screen

### ISSUE THREAD

**Issue by rxk-code** [topjohnwu/Magisk#4067]
Device: Galaxy S21 Ultra
Firmware: PDA (G998BXXS2AUBB) Product Code (VAU) CSC (G998BOXM2AUBB)
Android version: Android 11
Magisk version name: f152b4c
Magisk version code: 22005

[logcat_Canary f152b4c2(22005)(19).txt](https://github.com/topjohnwu/Magisk/files/6174924/logcat_Canary.f152b4c2.22005.19.txt)
[logcat_Stock_NoRoot.txt](https://github.com/topjohnwu/Magisk/files/6174925/logcat_Stock_NoRoot.txt)
[logcat_MagiskV22_stable.txt](https://github.com/topjohnwu/Magisk/files/6174926/logcat_MagiskV22_stable.txt)

Background:
1.  Stock firmware installed - pairing successful with my Watch Active 2
2.  Rooted using Magisk Canary Version - Watch Active 2 stuck on Finalizing Pairing Screen. (I noticed during pairing process, the Bluetooth and Samsung Accessory icon briefly appears on the top of the screen and then disappear. Tried manually connect via Settings>Connections>Bluetooth, briefly connected for few seconds then disconnect.

Hoping that you can help me resolve this issue.

Thank you so much.

**Comment by pndwal** [comment]
If you are using Universal SafetyNet Fix module, you could try latest test module (Shim the keystore service instead of replacing it).
https://forum.xda-developers.com/t/magisk-general-support-discussion.3432382/post-84693353

**Comment by shikarukitake** [comment]
Hi there. Have same provlem... But on rooted samsung galaxy s10 with magisk.

**Comment by Didgeridoohan** [comment]
Isn't this just a result of Samsung detecting root, rather than it being a Bluetooth issue?

**Comment by rxk-code** [comment]
Not really sure. I hide magisk app and added all related apps for my galaxy watch as well. 
During the pairing process, the bluetooth and samsung accesories icon briefly showing on the notification bar, then disappear.

**Comment by Didgeridoohan** [comment]
The reason I'm thinking it's an issue with Samsung root detection is threads like this:
https://forum.xda-developers.com/t/root-detection-removed-samsung-health-monitor-1-1-0-183-country-device-restriction-removed-14th-march-2021.4202685/

**Comment by shikarukitake** [comment]
@rxk-code I found solution of this problem. Solution is to install "watch" apps intended for other phones. Watch this [video](https://www.youtube.com/watch?v=1Do7tkqeqrM&t=604s) . The video on russian language, but in description u can find links with apps or turn on the subtitles and translate on english. 
Solution:
1. Turn off a web connection
2. Delete all apps related to watches (Watch Active Plugin, Galaxy Wearable, Samsung Accessory Service.)
3. Install Galaxy Wearable from Google Play Market, but **don't run it**!
4. Install apps from this [link](https://mega.nz/folder/IhwgUIqT#6y7oSnK84ec4HM-UdMuuIA). There are two Watch Active Plugins. Gear for Galaxy Active and Gear2 for Galaxy active 2. Install that u need
5. Install [AFWall+](https://4pda.ru/forum/index.php?showtopic=392249)
6. Restrict web connections for Watch Active Plugin, Galaxy Wearable, Samsung Accessory Service, because apps can automatically update yourself
7. Connect to watches

**Comment by rxk-code** [comment]
Thank you sir. I finally paired my Galaxy Watch Active 2 to my Galaxy S21 Ultra.How to update when new version is available? Do we need to uninstall and install a new patched plugin and samsung accessories app? Regards,Rxk--Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 25/3/21, 6:02 pm Shikarukitake ***@***.***> wrote:

   
  @rxk-code I found solution of this problem. Solution is to install "watch" apps intended for other phones. Watch this video . The video on russian language, but in description u can find links with apps or turn on the subtitles and translate on english. Solution: 
   
   Turn off a web connection 
   Delete all apps related to watches (Watch Active Plugin, Galaxy Wearable, Samsung Accessory Service.) 
   Install Galaxy Wearable from Google Play Market, but don't run it! 
   Install apps from this link. There are two Watch Active Plugins. Gear for Galaxy Active and Gear2 for Galaxy active 2. Install that u need 
   Install AFWall+ 
   Restrict web connections for Watch Active Plugin, Galaxy Wearable, Samsung Accessory Service, because apps can automatically update yourself 
   Connect to watches

**Comment by Didgeridoohan** [comment]
In other words, this is not an issue with Magisk and Bluetooth but root detection. I guess this can be closed then...
