### ISSUE TITLE
Brick after update (RAZER PHONE 1)

### ISSUE THREAD

**Issue by PrzemoVi** [topjohnwu/Magisk#4079]
Device: RAZER PHONE 1
Android version: 8.0
Magisk version name: V22.0
Magisk version code: 22005

I had many troubles while installing magisk on this device because of Slot A&B policy, everything was working property until last update - I clicked "begin" as always with same settings and nothing happened. I tried three times.
I thought it was network problem so I closed magisk and left it for later.
When by battery ran out and my device shut down and I was unable to boot it on slot A or B. I was stuck on first razer logo.
My boot image was bricked, I was unable to enter recovery or fastboot.
After an hour I finally managed to enter fastboot and flashed stock boot.img and now my phone is working property.

New instalation procedure is overcomplicated. It's not an option to people with TWRP&CWM.

I just want you to fix updater - I bricked my device while I was 500km from my home, app was not responding, there was no progress-bar or anything indicating that an update was in progress.

Thanks.

**Comment by Didgeridoohan** [comment]
The update bug you experienced, where several installation sequences where running at once has been fixed upstream, so you shouldn't experience that again. And the issue where the flashing started, but I'm the background so that it seemed like nothing happened when you pressed "Let's go" is under investigation.

Now that you've got things up and running again you need to install Magisk as if it was the first time (and the method for that is the same as it's been for a long time), either by patching the boot image (which is the recommended method) or by renaming the .apk to .zip and installing from a custom recovery.

Not quite the topic for an issue ticket though, so you should probably close this and if you need further assistance move over to XDA (or your forum of choice).

**Comment by PrzemoVi** [comment]
Okay, i'll close this. I just wanted you to know about this "Let's go" bug.

Thanks.
