### ISSUE TITLE
Unzip error when trying to install any module

### ISSUE THREAD

**Issue by Displax** [topjohnwu/Magisk#4090]
Device: Nexus 7 2012 WiFi
Android version: 4.4.4
Magisk version name: 66e30a77
Magisk version code: 22006

Log: [magisk_install_log_2021-03-25T123813Z.log](https://github.com/topjohnwu/Magisk/files/6204070/magisk_install_log_2021-03-25T123813Z.log)

This happens only on old android versions, I think. But nothing useful and related in logcat.
On device with Android 10 it`s working.

**Comment by Displax** [comment]
Via magisk --install-module modules installation works.

**Comment by dhruvkrishnavaid** [comment]
Hey @Displax
Are you sure that the zip was not corrupted?
By the way, this might be a problem with the commands used for unzip...
`unzip: can't open /storage/emulated/0/Download/Busybox_for_Android_NDK-1.31.1(13122).zip[.zip]`
The file extension is repeated within brackets.
This doesn't happen with me.

**Comment by replete** [comment]
I had this same problem. The GUI showed 'unzip error' (really helpful) but the CLI command 'magisk --install-module module.zip worked successfully

**Comment by yujincheng08** [comment]
@replete send the zip

**Comment by replete** [comment]
[custom-hosts.zip](https://github.com/user-attachments/files/16247768/custom-hosts.zip)

Not sure why it didn't work in in the GUI, I tried created the zip files with all kinds of CLI and GUI approaches. Thought I'd try the CLI in case there was some weird permission thing given I'm rooting an emulator:

The use case scenario is rooting an android emulator gplay build for testing websites in order to access https://localhost websites on the host from within the VM. I rooted using this repository: https://gitlab.com/newbit/rootAVD

**Comment by yujincheng08** [comment]
```
module.zip
│
├── META-INF
│   └── com
│       └── google
│           └── android
│               ├── update-binary      <--- The module_installer.sh you downloaded
│               └── updater-script     <--- Should only contain the string "#MAGISK"
```

this module lacks these files.

**Comment by replete** [comment]
Argh, apologies I had clearly had bad information on creating a magisk module.
