### ISSUE TITLE
Superuser policy list for apps is not refreshing when resuming the app

### ISSUE THREAD

**Issue by d4rken** [topjohnwu/Magisk#414]
Currently when the policy list is changed, i.e. a new app has request root, we have to exit the app screen and reenter it.

We could just refresh it on resuming.

My usecase:
When debugging root apps I frequently revoke permissions and have to enter/exit the screen after switching to it from the recent-apps list.

**Comment by d4rken** [comment]
@topjohnwu I'd also like to make it fresh automatically, even while the screen is open, e.g. when using Magisk in split-screen mode. I'd love to implement that using RxJava. I think I could also improve a few other parts with. Would you be interested in that?

What do you think about adding RxJava as dependency?

**Comment by topjohnwu** [comment]
@d4rken I do plan to fully rewrite most parts of the UI after v17.0 is released, don't want to do changes other than bug fixes before a stable is released.
You might want to hold on until that point :)

**Comment by d4rken** [comment]
#415 is a bug fix though which should probably be merged for stable, shouldn't it?

Regarding v17+ how much rewriting are you planing? I'd love to work on some architecture changes (dagger+mvp) if you are open to that, something like this https://github.com/d4rken/android-kotlin-starter

We could get some automatic testing going  and setup travis on this repo for automated tests of all pull requests.

The initial PR to change to dependency injection might be a bit bigger but after that we could gradually introduce to different parts.

**Comment by topjohnwu** [comment]
Yes, a **full** architectural change! Before Magisk Manager, I have 0 experience in Android app development so this whole app is pretty much "hacked together". Currently the app provides tons of features at this point and is actually pretty complicated (well at least IMO lol). Just recently I split out the root shell part into `libsu`, and with the introduction of 2.0.0 I think at least that part is going pretty well.

There are tons of new features in planning but I kept them down because I can't handle the UI part. The initial UI base is contributed from other members, so frankly speaking I don't really fully understand how the current theme/UI components work..... LOL

What I plan to do is to rewrite UI/UX from scratch, using full support library components (my plan is to support down to Android 4.1) so I can learn from the process. Using dagger + mvp is also appreciated, I do have decent React.js knowledge so I think I can handle it pretty well.

**Comment by d4rken** [comment]
> I have 0 experience in Android app development so this whole app is pretty much "hacked together".

Looks pretty good for 0 previous Android experience, but I'd bet that you have some solid knowledge in other languages 😁 .

> Just recently I split out the root shell part into libsu, and with the introduction of 2.0.0 I think at least that part is going pretty well.

Yeah it always get's complicated, and then a huge refactoring will make everything easy again :)

I think the structure could be refactored from `package by layer` to `package by feature` which makes it easier for new contributors to understand specific features (because all relevant files are close).

> Just recently I split out the root shell part into libsu, and with the introduction of 2.0.0 I think at least that part is going pretty well.

I've been following that, I think the approach is okay, similar to what `libsuperuser` from Chainfire did (which sadly isn't really maintained anymore). I'm not a fan of static access to `Shell.getShell()` etc.,  makes it hard to test and modularize (made [RxShell](https://github.com/d4rken/RxShell) als alternative but depending how familiar one is with RxJava it's a bit more difficult).
I think [`ShellFileIO`](https://github.com/topjohnwu/libsu/blob/master/superuser/src/main/java/com/topjohnwu/superuser/internal/ShellFileIO.java) is awesome.
> What I plan to do is to rewrite UI/UX from scratch, using full support library components (my plan is to support down to Android 4.1) so I can learn from the process. Using dagger + mvp is also appreciated, I do have decent React.js knowledge so I think I can handle it pretty well.

I would really like to help you with that, because I currently have a lot of extra time and I think Magisk is an awesome project, but I know big contributions are always difficult 😄.

I could send a big PR (against a new branch you create) initiating a new architecture if you'd like, just let me know how I can best help, it's your project. Keep up the good work 👍 .
