### ISSUE TITLE
[Discussion] Why reporting issues is only possible using canary build ?

### ISSUE THREAD

**Issue by cl-ement05** [topjohnwu/Magisk#4168]
Device: Xiaomi Mi 8
Android version: 11
Magisk version name:  9c0e189 
Magisk version code: 22101

Why is it necessary, when filling a bug report, to use the canary build. This seems kind of strange to me since for example I just noticed a bug on the just released V22.1. And I don't want to install a canary build on my daily-use my phone since canary is obviously unstable and can cause problems. So I simply won't be able to fill my bug report.

I think this some other people are in my case (#4165 ?) and it would make sense to accept issues from Magisk Stable channel. VSCode, Microsoft Terminal, python modules etc do not have this rule. So why does Magisk use it ?

**Comment by Didgeridoohan** [comment]
Simply because bugs present in the stable release might already have been fixed upstream and it's therefore no use reporting about it...

Currently we are in a very short window where the stable (22100) and Canary (22101) releases are basically identical, but as soon as new commits are added the stable release becomes "outdated" when it comes to bugs and troubleshooting.

Canary logs are also more verbose...

**Comment by cl-ement05** [comment]
Oh, ok I see 

Thank you for your answer
