### ISSUE TITLE
Magisk v22.1 latest version safety Net api error.

### ISSUE THREAD

**Issue by akramraza2** [topjohnwu/Magisk#4183]
Device: One Plus 7T
Android version: Android 10
Magisk version name: Magisk v22.1
Magisk version code:  22102

Safety net check fails and keeps saying API Error. Instead of fixing the issue why my report is being closed continuously. If you don't have fix maybe you should not release so many buggy updates so frequently.

**Comment by Didgeridoohan** [comment]
@akramraza2 No issues testing SafetyNet here (on 22102). You might have something else going on, especially since you have the API error. That usually means that the app doesn't have a proper internet connection. Make sure internet is on and that nothing is blocking the Magisk app. You could also try clearing data for the app, to force a redownload of the snet files.
