### ISSUE TITLE
disable auto-install trigger when interacting with push notification

### ISSUE THREAD

**Issue by kretesh** [topjohnwu/Magisk#4189]
On my Device (a Samsung G-955F), when i got the push notification for an available update, and i click on it, Magisk started to Ninja-download-and-install the update, left me no choice to first unhide the old renamed App.

This then messed up something with my update not for the first time, but because it is so intuitive to click on the update-notification, this happened to me almost everytime.

While with previous versions of Magisk this left me with multiple and/or unresponsive App, from 22.0 to 22.1 the App did not open and was not interactable at all.

The solution was to go to the App-info -> Storage -> Clear Data, to finish the installation of the update.

Maybe it is a good idea to implement some sort of confirmation-box to really update Magisk NOW, or implement a notification that the old App is hidden/renamed and prevent the update until this is fixed by the user.

thanks for the uncountable hours of work you put into this great project

**Comment by kretesh** [comment]
issue template form provided

**Comment by QkiZMR** [comment]
I had the same problem but I didn't clear data but delete only the downloaded apk file and run the app again. It's frustrating because like you this happened a second time. So I decided to turn off notifications about the new version. Information about updates on the main screen of Magisk is good enough.
