### ISSUE TITLE
After installing on magisk 22.0 or 22.1 i can't access magisk logs/root permission manage tab also modules.

### ISSUE THREAD

**Issue by thaript** [topjohnwu/Magisk#4264]
After installing on magisk 22.0 or 22.1 i can't access magisk logs/root permission manage tab also modules.
And i can't install magisk through boot image flash method or direct install method but it's working with my recovery
Still i can give root access to apps but i cant manage them after given access because i cant goto superuser/logs/modules tab because those options aren't showing up
When i install magisk 22.1 zip and magisk manager 8.0.7 i can goto these tabs but everything isnt shows atleast log

Here is my boot img please help me to fix it.
[Boot img](https://www.mediafire.com/file/rveoxy9bnvrnkhn/boot.img/file) 
Magisk 21.4 is working perfectly

Device: samsung j max tab (sm-t285yd)
Android version:22(lollipop 5.1)
Magisk version name: 22.1
Magisk version code: 22104

**Comment by zgfg** [comment]
Maybe you are just not familiar with the new design.
Scroll to the bottom and use floating bar:
![IMG_20210423_073045](https://user-images.githubusercontent.com/51943147/115823122-0bd1f400-a406-11eb-9ccf-b46ced447866.jpg)

**Comment by dwdjanika** [comment]
- [x]

**Comment by dwdjanika** [comment]
🙉

**Comment by dwdjanika** [comment]
@zgfg

**Comment by kohmy2036** [comment]
I have the same issue with my A7 2015 (SM-A700FD) on stock 6.0.1 ROM, I flashed Magisk 22.1 zip through TWRP, root checker said my phone is rooted but Magisk 22100 app shows "Installed: N/A", and I couldn't access other pages in the app except the home page, the floating bar won't show.
Currently using Magisk 21.4 w/ manager 8.0.7 and everything works fine, I can install modules and check the logs without any issue.

**Comment by zgfg** [comment]
Not familiar with Sansung but what you described is a common case (and not sure is it the "same" as originally described here) when user has two Magisk Manager/App apos installed. Then only the old one recognizes Magisk (and root and everything works), while the new Mgisk app claims that Magisk is not installed

You must make sure to manually uninstall the old Magisk Manager (with the new Magisk, it will be replaced with Magisk app).
Hence go to Settings, Apos, find Magisk Manager (or maybe under a dofferent name if you did hide your old Magisk Manager)

Btw, instructions suggest to patch and flash method instead of TWRP but you should better know which method to install Magisk better applies to your device

Anyway, you must remove the old Magisk Manager to let the new Magisk app to take its place. Thenn, pay attention that new Magisk app has a new design and that probably Modules tab is different than in the old Manager.

**Comment by artamudo** [comment]
> Not familiar with Sansung but what you described is a common case (and not sure is it the "same" as original problem described above) when user has two Magisk Manager/App apps installed. Then only the old one recognizes Magisk (and root and everything works), while the new Magisk app claims that Magisk is not installed
> 
> If it happened to you (probably baceause of hiding the old Magisk Manager, maybe also related to installing Magisk through TWRP since TWRP then also installs Magisk Mngr/App), make sure to manually uninstall the old Magisk Manager (with the new Magisk, it will be replaced by Magisk App).
> Hence go to Settings, Apps, find Magisk Manager (maybe under a different name if you did hide your old Magisk Manager) and Uninstall that app
> 
> Btw, instructions suggest to use patch and flash image method (and then to manually install Magisk app) instead of the old way of flashing Magisk through TWRP but you should better know which method for installing Magisk better applies to your device
> 
> Anyway, you must remove the old Magisk Manager to let the new Magisk app to take its place. Then, pay attention that new Magisk app has a new design and that probably Modules tab is different than in the old Manager, you will need to get familiar with (but first, new Magisk App must correctly recognize that Magisk is installed, to let it use the Magisk db and to show the modules, etc)

I have same issue on fresh Magisk installation. It's Magisk problem. Yesterday I've been flashed through TWRP.

Samsung Galaxy Tab 4

**Comment by leppit** [comment]
Please check issue #4174 for similarities.
