### ISSUE TITLE
No Magisk log after global clearing cache

### ISSUE THREAD

**Issue by bege10** [topjohnwu/Magisk#4308]
Device: Fairphone 3
Android version: 10
Magisk version name: fb8000b5
Magisk version code: 22104

It took quite a while until I found out why the log in the Manager UI is empty.
Because several apps litter the cache, while booting I regularly clear the cache globally with a 3C Toolbox task. But also NanoDroid scripts can do that task. And Magisk writes the log in `/cache`.
Couldn't Magisk write the log in `/data/adb`?

**Comment by DanGLES3** [comment]
From my knowledge it's stored in /cache because Magisk needs to write/read to the earliest mounting partitions (and cache just so happens to be the safest to store things on), so in case of an error that would prevent booting to a later stage (where data is mounted) the logs would be there already

Not to mention any module that requires sepolicy patching (like Viper or Xposed for example) have their sepolicies stored and loaded from there

**Comment by bege10** [comment]
Thank you for your answer. This issue seems to be more tricky than I thought.

**Comment by DanGLES3** [comment]
> Thank you for your answer. This issue seems to be more tricky than I thought.

Honestly wondering, what app of yours could possibly even be filling the cache partition? And it's filling it with what exactly?

**Comment by bege10** [comment]
Your question makes me wonder, too. Actually it seems not to be the cache partition but a cache folder in app data of these apps. And that this data is cleared must be the result of a different task. So maybe the task that clears the cache partition is just useless. 😳
Looks like an unexpected solution. I will test this the next days.
