### ISSUE TITLE
Error verifying vbmetadata HASH MISMATCH

### ISSUE THREAD

**Issue by mariushilleke** [topjohnwu/Magisk#4395]
Device: Samsung Galaxy A51
Android version: 11
Magisk version name: Magisk v23.0
Magisk version code: 23001

Following along the installation-tutorial I experienced the same message from issue #3259.

I was using [samfirm.js](https://github.com/jesec/samfirm.js) with `samfirm -m SM-A515F -r DBT` and got the respective tars.

```bash
28/05/2021  13:13     5,752,688,830 AP_A515FXXU4EUD7_CL21582303_QB39761917_REV00_user_low_ship_meta_OS11.tar.md5
28/05/2021  13:00         2,427,057 BL_A515FXXU4EUD7_CL21582303_QB39761917_REV00_user_low_ship.tar.md5
28/05/2021  13:14        26,542,269 CP_A515FXXU4EUD7_CP19011510_CL21582303_QB39761917_REV00_user_low_ship.tar.md5
28/05/2021  13:20       605,020,348 CSC_OMC_OXM_A515FOXM4EUD7_CL21582303_QB39761917_REV00_user_low_ship.tar.md5
28/05/2021  13:17       604,979,393 HOME_CSC_OMC_OXM_A515FOXM4EUD7_CL21582303_QB39761917_REV00_user_low_ship.tar.md5
```

Since my device had boot ramdisk I did not check for Recovery Mode.

I used Magisk to patch the firmware-file and got `magisk_patched-23000_ZnHmH.tar`.

But using this with Odin to flash it as `AP` with the other components as `BL`, `CP` and `CSC` (NOT HOME_CSC) delivered the screen from the above mentioned issue with a message saying hash mismatch and error verifying vb_metadata.

Do I have to extract something from the AP-file that only has to be patched and used as AP with Odin for flashing?

Or did I mistakenly used the wrong firmware, I got the information about model and region from the settings?

This is an update of issue #4387

**Comment by d5sword** [comment]
I had the same error while rooting my Samsung Galaxy Xcover Pro (SM-G715FN), but I found a workaround that I described here:
https://forum.xda-developers.com/t/is-possible-to-root-xcover-pro.4290087/post-85317391

Maybe it will also work for you.

**Comment by osm0sis** [comment]
Did this ever work with an older version of Magisk?

**Comment by osm0sis** [comment]
I googled "Samsung A51 Magisk" and immediately found instructions using a TWRP build to flash the APK, so I'm thinking we're good here.

**Comment by ankit-droidshift** [comment]
**fix for error verifying vbmeta image hash mismatch (3) 
Verification disable bit is set**

![WhatsApp Image 2022-12-29 at 12 05 45 PM](https://user-images.githubusercontent.com/15340528/209913552-75e304c2-98b7-403c-9c9e-2f1403c07d02.jpeg)

**I am facing same issue in my Samsung M31 with Android OS 12 and samsung UI Version 4.1 
i am using magisk  25.2( 25200)** 
![Screenshot_20221229-120013](https://u
![Screenshot_20221229-120013](https://user-images.githubusercontent.com/15340528/209913514-b0ed03f3-6b10-4124-83b2-17fad8bf7a96.jpg)
![Screenshot_20221229-120033_Settings](https://user-images.githubusercontent.com/15340528/209913529-a6440556-3b58-481e-8161-c0f30b58bc83.jpg)
ser-images.githubusercontent.com/15340528/209913459-cbff63de-5342-4f6d-a174-13a8c6cb7742.jpg)
![Screenshot_20221229-120033_Settings](https://user-images.githubusercontent.com/15340528/209913475-4dddcf36-5b98-4d78-85b0-aff4f2b2749b.jpg)

**Comment by ted123yes** [comment]
I got an error verifying vbmeta image: HASH_MISMATCH(3). And now my phone is stacked. Anyone could support me?
![image](https://user-images.githubusercontent.com/96662582/218561375-106a4836-d036-4e4f-9727-da2550565ac3.png)

**Comment by timakro** [comment]
After flashing patched AP along with original BL, CP and CSC I got the same HASH MISMATCH error. Entering download mode again and this time only flashing original BL fixed it for me. Source and partial explanation: https://github.com/topjohnwu/Magisk/pull/7181#issuecomment-1676066478

**Comment by Madaraxa** [comment]
Hey. By googling a lot i found out that (in my and many other cases) you only have to reflash the original BL file again to get rid of this error. So after you flashed BL, AP, CSC, etc. and get this error you can try and reset Odin and then only flash "BL".
This fixed the error in my case (A51)

**Comment by Andrew482c** [comment]
You wanna say Only installed BL original All fixed??

**Comment by bughunter2** [comment]
**Solution with full details, from beginning to end:**

I had a normal (bootloader locked and stock firmware) Samsung phone. Then I unlocked the bootloader (by toggling 'OEM unlocking' and booting into Download Mode, then following the on-screen instructions). Then I installed the Magisk app and used it to create a patched firmware image. Then flashed the patched firmware using Odin, as described in the Magisk documentation. Then, I got to the state where the phone had a boot loop and kept showing HASH_MISMATCH.

Then, I tried using Odin to flash just the bootloader from the original firmware (using the proper .tar.md5 format that is required, see below if you need to know how to make a .tar.md5 file). Then, the phone had a boot loop and kept showing "invalid magic". Then, I used Odin to flash the Magisk-patched bootloader again (just the bootloader, nothing else, using a self-made .tar.md5 file, as explained below). Then, the phone went back to the HASH_MISMATCH boot loop problem.

**Let's fix the HASH_MISMATCH boot loop problem:**

We flash the original firmware, and then we flash **just** the Magisk-patched bootloader, nothing else. Then, when powering on the phone, it shows the "this bootloader is unlocked" (or similar) warning, as expected. But this time, the phone boots into a very **limited** variant of the Recovery Mode, where we could only choose to perform a "Factory data reset" (or view logs). So, we perform a "Factory data reset". Then, the phone still showed the "this bootloader is unlocked" warning (as expected), but now it boots into the Android initial wizard (setup wizard) and we are able to initialize the phone normally.

But, we are **not** done yet. Of course, since we did some manual steps, we haven't yet completed a full Magisk installation. While, yes, the bootloader was now indeed patched, the Android system itself was **not** yet patched. And indeed, when installing the Magisk app, the Magisk app noticed this when we opened it. When starting the Magisk app, it showed the message "**Requires Additional Setup**" and "Your device needs additional setup for Magisk to work properly. Do you want to proceed and reboot?". I proceeded to let Magisk complete the setup. The device rebooted. Now when I opened the Magisk app, I didn't see any warning at all. But there was still an Install button, but I'm guessing that Magisk always shows that button, since it can be used to select and patch image files as well.

So, now I wondered, are we done yet? Can we become root? So, I installed a terminal app called "TermOne Plus" (known as "Terminal Emulator" on F-Droid.org; its app ID is "com.termoneplus"). Then I launched this terminal app, and entered '**su**'. And indeed, now Magisk shows a "**Superuser Request**" prompt asking us whether we want to grant the terminal app full access to our device. Upon granting the permission, I typed '**whoami**' to print the effective user name. It showed '**root**'.

Done. The device is now rooted and you can grant root privileges to apps that request them.

How to make a **.tar.md5** file for Odin:
```shell
# The .tar archive can contain multiple images, such as recovery.img, vbmeta.img, and so on.
# In this example, we will make one that contains just boot.img, nothing else.
tar -H ustar -c -f boot.tar boot.img
md5sum -t boot.tar >> boot.tar
mv boot.tar boot.tar.md5
```

**Comment by Valnomien** [comment]
> **Solution with full details, from beginning to end:**

Thank you bruh that worked so glad I have full system wide persistent Magisk.
