### ISSUE TITLE
Magisk Manager Rename Function Missing from 23.X

### ISSUE THREAD

**Issue by noahbliss** [topjohnwu/Magisk#4441]
Device: Mi 9t Pro (not relevant)
Android version: MIUI 12 (doesn't matter for this bug_
Magisk version name: Heck if I know
Magisk version code: 23.X (Magisk manager)

Ability to hide the Magisk Manager app using a randomized/custom app name seems missing from 23.X. This was necessary to getting around Google for Work device policy enforcement. Any reason this was removed?

**Comment by noahbliss** [comment]
friggin

**Comment by licaon-kter** [comment]
@noahbliss canary build 23001 f822ca5b fixed it for me, same device but on AOSP

**Comment by DanielRieken** [comment]
Most likely you disabled wifi/internet-connection or blocked internet-access with a firewall on your device.
When Magisk has not internet-connection the "Hide the Magisk App" is not visible or greyed out.

Double check this option must not say "N/A", otherwise "Hide the Magisk App" is not available":
![magisk](https://user-images.githubusercontent.com/68472253/132424504-bc7df31d-6e77-4d31-b93c-f866649745f2.png)

**Comment by licaon-kter** [comment]
@DanielRieken that was not it, in my case, it had full access...

**Comment by Sage222** [comment]
Superstar! this was driving me crazy. was no Internet Access.  A toast message or something similar would be a great addition in future releases!.

**Comment by noahbliss** [comment]
_Why_ does it need internet to do this though? When I turn internet on before doing the app hide process, it gives the other apps a chance to narc on me. Pretty poor design in my opinion.

**Comment by licaon-kter** [comment]
Yeah, it's the internet.

Given this feature is gone, I doubt we'd ever get an answer, let alone a fix...

**Comment by riccardo1991** [comment]
I have updated to Magisk 24.1, but the LG app is now detecting the root with the new zygote method. Came back to 23.0, tried to rename the package, but it's not working.
I have the impression there is an internet check of the installed version is the last
