### ISSUE TITLE
FEATURE REQUEST : automatically delete old module ZIP when updated

### ISSUE THREAD

**Issue by cl-ement05** [topjohnwu/Magisk#4481]
Device: Mi 8
Android version: 11
Magisk version name: f822ca5b
Magisk version code: 23001

It would be great if Magisk could delete the old module ZIP file when the module is updated. This would avoid having tons of useless files with very long names. Of course, some people might still want to keep their files so there could be an option in settings that lets the user choose what he wants.

Maybe this could be implemented by saving the ZIP filename of a module when it is installed.

Same logic could be implemented when a module is removed -> the zip can be deleted (if enabled in settings)

**Comment by zgfg** [comment]
Magisk downloads the module zip file to Downllads folder when you install from Repo - you can delete it right after the installation of the module is finished since Magisk does not need that file anymore

However, by using "Install from storage" you can ibstall the module from any folder on your Internal memory or OTG.
Again, after the module is installed, you can delete the zip file because Magisk does not need it and Magisk would not remember where from you installed the module zip file

When module is installed, Magisk creates the folder on /data/adb/modules and that is the only folder Magisk needs for the module - hence again, you can manually delete the downloaded zip file from Download folder or any other folder you downloaded the module zip file

**Comment by androidacy** [comment]
This is not really feasible using publicly available (ie user facing) storage. What if you rename it? What if it's deleted?

**Comment by zgfg** [comment]
I'm just user as you. Consult the Magisk documentation

But again, it is just temporary to download the zip file - like if you download some apk file from somewhere

Once the module is installed, everything that Magisk needs for the module is on /data/adb/modules - and that is accessible only with root

If you delete Download folder, Amdroid will recreate it (at lest on reboot) - it is one of the folders Android takes care to exist.
Probably also if you delete Download folder and try to download something from browser or to download the module from Magisk, folder will be also recreated

Hence don't care about such unimportant things

Real module's folder (once installed) is on /data/adb/modules and Magisk takes care how to use it for activating the module on reboot, or to disable/enable/remove the module

If you want to learn, study the documentation

**Comment by cl-ement05** [comment]
> What if you rename it? What if it's deleted?

Well just ignore the situation. 


@zgfg 
> If the zip files bother you, manually delete them right upon the modules are installed

Of course I can delete it manually but it is boring lol it's like temp folders on computers, you could delete them manually but the OS does it for you because it is boring. 

> And you can delete the module's zip file (like you can delete the apk file once you install the application)

The problem here is that you usually download a single APK file and, unless you care about updates which is not my case because Google Play does it for me, you do not download an APK for the same app anymore. But modules are very different since they actually get updates so if you do not delete unused zip files and use Magisk for some years you will get a really messy folder with a lot of modules.

> Hence don't care about such unimportant things

Of course this clearly not a key feature, but it would be a *bonus*-feature since you don't have to care anymore about deleting useless ZIP files

**Comment by vvb2060** [comment]
No permission to delete old zip

**Comment by cl-ement05** [comment]
> No permission to delete old zip


Won't write_external_storage do the job ?

**Comment by vvb2060** [comment]
Download is a public directory, it is not a private directory of Magisk. When Magisk adds a file to it, the file will belong to the user and not to Magisk.

**Comment by osm0sis** [comment]
It only has permission to access its own files. You can test this by downloading the same module multiple times; when Magisk app has created the file it overwrites, and when you hide the Magisk app giving it a different package name then it doesn't recognize they belong to it anymore and will download with -1 suffix.

Anyway, I think the idea is you have previous versions for rolling back if there's an issue, since these can be hard to get otherwise. So I think it's intended behavior.
