### ISSUE TITLE
Keytrade bank app 5.4.9 detect root

### ISSUE THREAD

**Issue by pietpims13** [topjohnwu/Magisk#4493]
After update, the lastet app version of Keytrade Bank detect now root.
Before, with the command "su -c chmod 000 /proc/net/unox" was enough to bypass the detection.

**Comment by Jon8RFC** [comment]
Works fine on my device when I do the following things.
Do this for any app detecting Magisk or root, not just yours:

1. Force stop the problematic app and delete all data
2. Magisk App needs to be hidden
3. MagiskHide needs to be enabled
4. Select the problematic app to be hidden in MagiskHide and checkmark all boxes
5. Install the latest safetynet-fix to your magisk modules, because some apps (now and future updates of apps) check safetynet: 
 https://github.com/kdrag0n/safetynet-fix/releases/latest
6. Reboot
7. Use the problematic app

Other modules you've installed via Magisk, or other system software you've installed, could be causing things to be detected--riru, xposed, edxposed, are/were often the type which caused problems.  You can only tinker so much before things don't work as desired.

Here's a quick video:
https://youtu.be/UaWh9BOdMdI

**Comment by pietpims13** [comment]
Hi,


Thank you for you answer ! :)
Unfortunately, the app still doesn't work...
And I'm not the only one :
*https://forum.xda-developers.com/t/keytrade-bank-app-5-1-0-is-now-detecting-magisk-19-3.3941095/page-2
<https://forum.xda-developers.com/t/keytrade-bank-app-5-1-0-is-now-detecting-magisk-19-3.3941095/page-2>*

If you want some information or have some questions, don't hesitate to come
back to me ! :)


Cheers,

PietPims13.
