### ISSUE TITLE
Safety net fix please
We need this


### ISSUE THREAD

**Issue by Abuzarar** [topjohnwu/Magisk#4640]
Device: 
Android version:
Magisk version name: 
Magisk version code:

**Comment by Abuzarar** [comment]
Then y cts profile is showing failure

**Comment by Didgeridoohan** [comment]
@Abuzarar Because Google have updated things on their side. It's being discussed all over XDA, take a look there.

Also: #1152

**Comment by Abuzarar** [comment]
We root because we need access to all the things which we need to but if some detect me i t is over for me

**Comment by Abuzarar** [comment]
Why are u not updates your magisk and improve codes of it and give safety net

**Comment by cl-ement05** [comment]
> Why are u not updates your magisk and improve codes of it and give safety net

Lol stop spamming. This is not Magisk's fault so improving the code won't do anything. This issue is coming from Google. I understand your situation since just like you I have many apps which don't work when they detect root. Just follow this workaround and everything will be back to normal : https://github.com/kdrag0n/safetynet-fix/issues/78#issuecomment-912054082

**Comment by Abuzarar** [comment]
I have done this process but it is not working

**Comment by cl-ement05** [comment]
> 
> 
> I have done this process but it is not working

Well, then you did something wrong since this method works very good
