### ISSUE TITLE
Google Pixel / Pixel XL Support

### ISSUE THREAD

**Issue by GabrielTK** [topjohnwu/Magisk#47]
Hi,
I just tried to flash Magisk on my Pixel XL, but I got an error about Mounting System. I think its because of the different partition scheme.
**IDEA: WHAT IF WE STOPPED THE SCRIPT FROM MOUNTING SYSTEM AND MANUALLY MOUNTED IT THROUGHT TWRP UI??**

**Comment by Didgeridoohan** [comment]
Pixel support is a work in progress and it's known that it does not currently work. See "Currently Known Issues" in the [Official announcement thread](https://forum.xda-developers.com/apps/magisk/official-magisk-v7-universal-systemless-t3473445).

**Comment by GabrielTK** [comment]
I already read it, but... Is there anyway we can help to add support to it?

On Jan 15, 2017 1:49 PM, "Didgeridoohan" <notifications@github.com<mailto:notifications@github.com>> wrote:

Pixel support is a work in progress and it's known that it does not currently work. See "Currently Known Issues" in the Official announcement thread<https://forum.xda-developers.com/apps/magisk/official-magisk-v7-universal-systemless-t3473445>.

**Comment by GabrielTK** [comment]
What if I successfully flash magisk. Will it work??
**NOTE:It Seems that Latest SuperSU for pixel mounts /system.**

**Comment by GabrielTK** [comment]
Any updatee??

**Comment by ChrisM-Rogers** [comment]
Has anyone tried flashing Magisk on their Pixel? If so could they provide a log? I'll take a look in my spare time to see what I can achieve. 

I would flash it to my Pixel, but I don't know what state it would leave my phone in. Since it's my daily driver, I need it to be working lol. Though I might be able to do a bit more at the weekends where I have more time to recover it back to a working state.

**Comment by mitchelhaan** [comment]
What I've gathered so far:
- flash_script.sh performs a number of operations using `/system` (reading build.prop, using shared libraries, and potentially removing existing system su installation)
- In TWRP 3.1.0-0RC2 on Marlin, `/dev/block/bootdevice/by-name/system_[a or b]` is mounted on `/system`
    - BUT: that device isn't exactly `/system`, it's a rootfs of its own, with its own `/system` directory.
    - The paths that the script is looking for in `/system` are actually in `/system/system`

I don't know what to do with that information though. One possibility could be to change the `/system` references to a variable and set it based on the presence of `/system/build.prop` or `/system/system/build.prop`

**Comment by ChrisM-Rogers** [comment]
@mitchelhaan any idea if data written to the mounted `/dev/block/bootdevice/by-name/system_[a or b]` fs is written to both partitions? Or just the mounted one?

**Comment by mitchelhaan** [comment]
@ChrisM-Rogers just the mounted one (an assumption on my part, but writing to both automatically could be problematic). TWRP has an option to change boot slots in the reboot menu, but it only mounts the current one.

**Comment by ChrisM-Rogers** [comment]
@mitchelhaan Theoretically, I'd have thought it would be possible to mount both via a shell script, it is just another partition really, I mean if the OS can write to partitions on the other slot during an OTA, we should be able to at recovery level.

I guess at a testing stage it could be feasible to get it to write only to one slot only so that you can switch should anything break. I'm not entirely sure how Magisk works, as in interrupting the boot process to run it's scripts, but (assuming there's only one `/data` partition, I'm not entirely sure) it maybe possible to test on say slot A and I could still use slot B as my daily driver which would be perfect.

**Comment by mitchelhaan** [comment]
@ChrisM-Rogers yeah, mounting both should be easy enough. There may not be anything usable in the alternate slot though.
I like the idea of using one slot for testing and one for daily use. I haven't tried it but theoretically it should work, as long as both systems are compatible. There are a handful of common partitions according to FlashFire, one of which is Data.

**Comment by ChrisM-Rogers** [comment]
@mitchelhaan I've made a nandroid back and tried to flash Magisk v11.6 but it failed (as expected) with an error, so it appears my device is in a useable state which is good to know. 

This means I can probably try a few things out. So far the path you told me is correct, I've managed to mount both `system_a` and `system_b` in ADB root shell. If I change my slot to A, my phone also won't boot, this appears to be because nothing has been flashed to slot A yet. It looks quite promising to be fair. I should head off to bed now, but I keep looking tomorrow when I have time! :simple_smile:

**Comment by mitchelhaan** [comment]
I made some attempts at this last night. Changing `flash_script.sh` to detect the `/system` directory properly was a start. The next problem is that the utility binaries (like magiskboot) are not statically linked and are trying to use `/system/bin/linker64`. Mounting `/system` rw and creating a symlink for `/system/bin/linker64 -> /system/system/bin/linker64` allowed it to run, but is not an ideal solution. It appeared to install successfully once I did that, but I haven't been able to verify. The MagiskManager app also needs updates to support the A/B setup.

**Comment by mitchelhaan** [comment]
@ChrisM-Rogers I stumbled across this... [Working Magisk solution for Pixel / XL](https://www.reddit.com/r/GooglePixel/comments/61n9af/working_magisk_solution_for_pixel_xl/)
It is working for me so far, although after installing, the I/O scheduler selection doesn't show up in ElementalX. The scheduler selection still shows up properly when I check it through ADB.

**Comment by ChrisM-Rogers** [comment]
@mitchelhaan thanks for the link, I'm tempted to give it a go, though I do still want to pursue helping to obtain support on here, I'd like to eventually have a viable stock ROM solution.

Just a thought on `linker64`, is that not discoverable use the `which` command? As in `which linker64`, that should return the correct path if it exists.

**Comment by GabrielTK** [comment]
"Edit: The creator of this zip pushed his changes up to the Magisk dev so hopefully the official Magisk dev will update so the Pixel is officially supported. Until then there is no dedicated support outside of people nice enough to help in the threads."

**Comment by ChrisM-Rogers** [comment]
Sorry, yes that completely swept past my eye. I'm going to check out his PR and give it a run! :+1:

**Comment by GabrielTK** [comment]
Ok... So we have PR #145, but how about [topjohnwu/MagiskManager](https://github.com/topjohnwu/MagiskManager)?? Does it also needs a PR??

**Comment by ChrisM-Rogers** [comment]
It likely will I'd have thought, at least to write new updates anyway (but I'm not sure how the updates are implemented, the app probably on downloads the updated zip and flashes it on reboot in recovery maybe, then it wouldn't matter).

Though I guess it also depends on how @topjohnwu wants to implement support for A/B devices, since some may want to have 2 ROMs running, if Magisk was to write to both slots then that could potentially cause unwanted behaviour on the other slot/ROM.

**Comment by ChrisM-Rogers** [comment]
@mitchelhaan Is your ROM stock with only the kernel changed to ElementalX? I've just built from the source provided in https://github.com/topjohnwu/Magisk/pull/145 but I get an error while trying to unpack the boot image.

**Comment by mitchelhaan** [comment]
@ChrisM-Rogers I am running PureNexus + ElementalX, no other modifications.
Make sure you're using TWRP 3.1.0-0RC2... the .zip that goodwin_c made won't work on 3.0.2.

MagiskManager also needs a small modification to detect the proper boot image location. I re-built it with the value hard-coded but there is also an apk referenced in that XDA thread. I'm not actually sure if that's necessary to use it, or if it's only needed for updating.

**Comment by GabrielTK** [comment]
Ok... So, are we able to build and flash this PR or it's better to wait??

**Comment by ChrisM-Rogers** [comment]
@GabrielTK It won't flash on a stock ROM. But I'm having great success right now! I've a got a few more things to do, then I'll push my changes.

**Comment by ChrisM-Rogers** [comment]
I can't get the Magisk Manager app to build on my laptop, so I'll have to wait till I get home to do anymore work. I seem to have Magisk installed though, but Magisk hide won't work yet and thus fails Safty Net.

**Comment by ChrisM-Rogers** [comment]
I think I've given up now. @mitchelhaan  how did you get Magisk Manager to detect the boot image? I've been messing with the shell script for 2 days and nothing is working 👎

**Comment by mitchelhaan** [comment]
@ChrisM-Rogers I had originally done it by hard-coding the partition name in MagiskManager's search list. I've made an effort to clean that up, see https://github.com/topjohnwu/MagiskManager/pull/139

**Comment by ChrisM-Rogers** [comment]
Hum, doesn't appear to be working on mine with a stock image. No error, so I'd have to add in some debug lines to find out why. 

I can only assume its because of having a stock image...

**Comment by GabrielTK** [comment]
Any updates??

**Comment by crivchri** [comment]
What's new with installation on fully stock Google Pixel? Does it already works? Or does it need a custom Kernel?

**Comment by ChrisM-Rogers** [comment]
So far it's only been found to be working on custom ROMs i.e. Lineage, though I am attempting to help @goodwin in [this PR](https://github.com/goodwin/Magisk/pull/1).

**Comment by GabrielTK** [comment]
Any updates??

**Comment by goodwin** [comment]
I have prepared bunch of workaround for upcoming v13 release, but still i want to make them not so dirty and be sure that i'll not break compatibility with other devices. So it will consume some more time

**Comment by GabrielTK** [comment]
@goodwin Are they [on the v13 beta?](https://forum.xda-developers.com/apps/magisk/beta-magisk-v13-0-0980cb6-t3618589)

**Comment by byronaltice** [comment]
Greatly appreciate your work on this. As you can see in #295 i am having specific issues to the mounting of /system.

Let me know if there is any info I can provide to you to help you resolve this (Pixel XL).
