### ISSUE TITLE
Magisk/tips doc inconsistency/question

### ISSUE THREAD

**Issue by Naklarsuper** [topjohnwu/Magisk#477]
Referring to:  https://github.com/topjohnwu/Magisk/blob/master/docs/tips.md 
In OTA installation tips, for all methods it is recommended to bring back recovery to stock. 

It remains unclear, however, if for Devices with A/B Partitions also stock recovery is required. 

So my questions are: 
- Does the A/B OTA Update method with Magisk require TWRP to be removed? 
- Will it work with TWRP installed? 
- Will it leaveTWRP intact? 

Thanks - would be good to know before messing up the device. 
Best regards, keep up the great work!

**Comment by Didgeridoohan** [comment]
The documentation is unforunately not accurate at the moment, especially that specific part. There's been a lot of changes regarding OTA updates on A/B devices and I'm sure @topjohnwu will update the text once the next stable release is out.

**Comment by DenyDarko** [comment]
Best thing about A/B is that twrp is not required.

**Comment by Naklarsuper** [comment]
@Didgeridoohan: thanks for coming back. So the documentation is not accurate in the sense that OTA updating would not work, neither with nor without TWRP?
@DenyDarko: agree, can be a good thing to some. My question was regarding those who for whatever reason have TWRP installed

**Comment by Didgeridoohan** [comment]
For some A/B devices the given instructions still work. Pixel devices (and likely others), not so much...

As far as I understand it, stock recovery is not required for updating with OTA on an A/B device (I don't have one, so I'm just going by what I've read and heard). But, (again: as far as I understand it) since the custom recovery is in the boot image, it will be replaced when flashing Magisk. This is also something that is being worked on and might change with a future update.

**Comment by Tjololo12** [comment]
I'm using an x4 and followed the guide, but the OTA failed to pass verification. I suppose something broke somewhere, but I'm not sure what/where/how.

**Comment by topjohnwu** [comment]
Documents updated with latest instructions.

**Comment by Naklarsuper** [comment]
Thanks! Will this also work with TWRP installed (on A/B device)?
