### ISSUE TITLE
A/B partition support for Oneplus 6

### ISSUE THREAD

**Issue by lijun0326** [topjohnwu/Magisk#479]
Oneplus 6 does have A/B partition, but there is no "install to next slot" option when installing in magisk manager.

**Comment by Displax** [comment]
This will be added (returned) to the next release: https://github.com/topjohnwu/Magisk/commit/07140d33a76f66cdc9a9f5c4d757b0afa52d6eef

**Comment by lijun0326** [comment]
@Displax Why RETURNED? Was it removed for some reason?

**Comment by Displax** [comment]
@lijun0326 yep, it was temporary removed because it stopped working due to some changes in GMS.
Commit: https://github.com/topjohnwu/Magisk/commit/831112abd2d7fd3df0b1680d1c73c458512e7745
https://twitter.com/topjohnwu/status/1014282945505267712
https://twitter.com/topjohnwu/status/1020060637911605249
https://twitter.com/topjohnwu/status/1020305846234853377
