### ISSUE TITLE
Samsung S21 Ultra not working

### ISSUE THREAD

**Issue by maxGerards** [topjohnwu/Magisk#4949]
On November 15, 2021, Samsung released the update for the S21 Ultra for Android 12.
The patching of the image worked and so did the boot after flashing the boot.img. After the start, however, root was not available.

Device:
Android version: 12
Magisk version name: canary
Magisk version code: 23014

**Comment by yujincheng08** [comment]
No log, no fix.

**Comment by MohammadAG** [comment]
I've also encountered this on an S21 Ultra and have been trying to figure out where the issue is. It seems like magiskd is dying/being killed without any mention of it anywhere.

I added a few logs to Magisk (master) and built a kernel to help me debug this, but I still can't figure it out.
[magisk.log](https://github.com/topjohnwu/Magisk/files/7580639/magisk.log)
[magiskinit.log](https://github.com/topjohnwu/Magisk/files/7580642/magiskinit.log)

`130|p3q:/ $ ps -A | grep magisk
u0_a298      12086  1003 16869492 137372 0                  0 S com.topjohnwu.magisk
p3q:/ $`

**Comment by yujincheng08** [comment]
@MohammadAG maybe you can try `magisk --daemon` to manually launch a daemon. And if it dies somehow, you can try to attach a debugger to see when and why it dies.

**Comment by vvb2060** [comment]
upload /system/etc/cgroups.json

**Comment by MohammadAG** [comment]
Renamed for Github
[cgroups.txt](https://github.com/topjohnwu/Magisk/files/7581029/cgroups.txt)

**Comment by vvb2060** [comment]
>  Magisk 1eb83ad8(23001) daemon started

？？？

**Comment by vvb2060** [comment]
You should use the latest canary magisk and upload all kmsg(no grep), otherwise, this issue will be closed.

**Comment by MohammadAG** [comment]
Welp, I missed the part where it wasn't actually the latest version. I'd pulled from master but magiskboot wasn't being built correctly so I was actually using an older one. That seems to have fixed the issue.

I'm not OP though, so I'm not sure if the issue should be closed or not, I'm assuming they have a different issue.

Sorry about the confusion.

**Comment by vvb2060** [comment]
Your devices are the same, I believe 2e299b38 has fixed this issue.

**Comment by vvb2060** [comment]
@maxGerards If you are having problems with the latest canary magisk, please open a new issue and upload the full kernel log.

**Comment by yujincheng08** [comment]
@MohammadAG you should ALWAYS seeks help by using the latest official canary rather than the one built by yourself.

**Comment by MohammadAG** [comment]
> @MohammadAG you should ALWAYS seeks help by using the latest official canary rather than the one built by yourself.

I would, but it's a Qualcomm device and there's an issue that causes a bootloop due to some weird behavior with fstab on these devices (there's both an fstab in the filesystem and one in the device tree). Unfortunately the fix I have is probably not suitable for other devices so I never opened an issue about it, and Samsung devices with a Qualcomm chip are usually bootloader locked from what I can tell.
