### ISSUE TITLE
Sign boot image with verity key

### ISSUE THREAD

**Issue by xingrz** [topjohnwu/Magisk#511]
Boot images of some devices (such as Smartisan M1, Nubia Z11) were signed with [verity key](https://android.googlesource.com/platform/build/+/master/target/product/security/verity.pk8). The bootloader of these devices refused to boot images signed with any other keys.

Currently, Magisk signs boot images with testkey if AVB is detected. Is it possible to detect which key a image was signed with, then sign it with the proper key?

P. S. images can be verified to determine if it was signed with a given key, with `boot_signer` from AOSP:

```
$ boot_signer -verify boot.img -certificate build/make/target/product/security/verity.x509.pem
NOTE: verifying using public key from build/make/target/product/security/verity.x509.pem
Signature is VALID

$ boot_signer -verify boot.img -certificate build/make/target/product/security/testkey.x509.pem
NOTE: verifying using public key from build/make/target/product/security/testkey.x509.pem
Signature is INVALID
```

**Comment by topjohnwu** [comment]
The tool within Magisk can also verify against a certificate; it also supports using external keys/signature pair (check `com.topjohnwu.magisk.utils.BootSigner`).
An unlocked bootloader in theory **should** support all signatures. It is quite weird for an OEM to sign images with globally accessible keys like AOSP verity and enforce against that.

I'll close this issue for now since it is not a priority for me, but adding support for other keys is trivial. There might be tons of other keys out there, and I don't think adding more keys would be a general solution. I will (and only) add all AOSP keys into the mix if I would want to add more keys.

**Comment by xingrz** [comment]
😂 Actually these OEMs didn't provide BL unlock but they forgot to change their keys.
