### ISSUE TITLE
Request: make it even more easier for others to build and debug

### ISSUE THREAD

**Issue by aapo** [topjohnwu/Magisk#525]
You have already done much for _outsiders_ to build Magisk (Documentation, build.py, FrankeNDK and so on). I have suggestion for README.MD: 

    git clone https://github.com/topjohnwu/Magisk
    cd Magisk
    git submodule update --init --recursive

Last step is not trivial to everybody (e.g. https://forum.xda-developers.com/apps/magisk/git-clone-building-magisk-failing-t3707221)

Another thing: How I'm supposed to feed just compiled magisk-debug.zip to the Magiskmanager in the phone (without building own Update Channel)?

**Comment by DenyDarko** [comment]
Well I found the solution myself anyway back then xD

**Comment by 11lb8oz** [comment]
I dont know about easier.  Being called an outsider. Everything I do has
always been in the dark and alone.  Sometimes I hate exploring,  trying, or
having what I think is fun or interesting...and pissing someone off or
ruining another day. I apologize for intruding and for my lack of formal
education, self or otherwise.

If that is, what's being referred to here. My playing with "legos without
instructions.

Jim 0801 😜

All respect to John and the participants who fight the good fight.  Make it
useful.

**Comment by TugaPowerROM** [comment]
first you can use:

`git clone -b master --recursive https://github.com/topjohnwu/Magisk.git`

About second you can just copy file to phone and use the option to flash like a regular module

**Comment by shoeper** [comment]
When being familiar with docker it can be the easiest to utilize it, especially as installing the sdk and ndk is time consuming. E.g. (attention with this command the container and its data will be removed on stop)
```
docker run --rm -it runmymind/docker-android-sdk:ubuntu-standalone bash
apt-get update && apt-get install -y python3
git clone -b master --recursive https://github.com/topjohnwu/Magisk.git
cd Magisk
# set configurations in config.prop and continue as follows ...
./build.py -h
./build.py all
```
