### ISSUE TITLE
Android12 GSI boot fix fail.

### ISSUE THREAD

**Issue by easternDay** [topjohnwu/Magisk#5269]
Device: HUAWEI Honor10 
Android version:Android 12(GSI for AOSP)
Magisk version name: Canary
Magisk version code: 23018

I flash AOSP GSI into my Honor10。
But when I use magisk to fix boot, it will not take effect after restart. 
Patched according to the method provided by [treble_experiment#How to magisk root AOSP Android 11 GSI ?](https://github.com/phhusson/treble_experimentations/wiki/Frequently-Asked-Questions-%28FAQ%29#how-to-magisk-root-aosp-android-11-gsi-), still not effective.

**Comment by TheInterestingSoul** [comment]
1. Shutdown your device.
2. Press VolUP & Power Button and then hold them, until you see the screen light up and saying `Your device is booting now...`. through this way we come into `erecovery`.
3. Select `Factory Reset`, type `yes`.
4. This operation **won't** actually clear your data. The reset program in `erecovery` will automatically jump to `recovery`, which has been patched already. And every time you boot your device, the system will find that "reset process didn't go well", and try to launch `recovery` endlessly.
5. Since then, no matter how many times you restart your device, it will absolutely boot with the patched `recovery`, and Magisk would take effect.

You may follow the instruction provided by the tool below:
```
麒麟盘古工具箱：链接: https://pan.baidu.com/s/1sW2loFLYQnjH8uSjv5Wrxw 提取码: minr 复制这段内容后打开百度网盘手机App，操作更方便哦
```
