### ISSUE TITLE
Security Concern

### ISSUE THREAD

**Issue by ShellCode33** [topjohnwu/Magisk#527]
Hi, recently a new type of vulnerability has been disclosed (it's called [Man In The Disk](https://www.kaspersky.com/blog/man-in-the-disk/23622/)) and I think Magisk suffers from that too.
I'm not really familiar with your code so may have misunderstood a few things, but I've found [here](https://github.com/topjohnwu/Magisk/blob/aa383e219035b7f14cc4b916b27f5e8facbcb24a/app/src/full/java/com/topjohnwu/magisk/asyncs/InstallMagisk.java#L245) that during the installation process, you are writing the new image to `Download.EXTERNAL_PATH` which is the user's Downloads folder.
A malicious app could take leverage of that by replacing the file while Magisk is updating, leading to the installation of a corrupted boot image. Basically, an unprivileged app can become root without even asking the permission to the user.
I also noticed that [a checksum was involved](https://github.com/topjohnwu/Magisk/blob/aa383e219035b7f14cc4b916b27f5e8facbcb24a/app/src/full/java/com/topjohnwu/magisk/asyncs/InstallMagisk.java#L136), maybe I've missed something here, but I thing it's a typical case of race condition, the file just has to be replaced after the MD5 checksum (which by the way should be changed, it's quite easy to create MD5 collisions).
So let me know what you think ! Am I right to think our security is at risk ?

**Comment by topjohnwu** [comment]
I'm aware of this issue but it requires me to write new UI, so it isn't included in the current release

**Comment by ShellCode33** [comment]
Why is it needed to change the UI ? Can't you just use the app's internal storage instead of the external one ?

**Comment by shoeper** [comment]
Agree with @ShellCode33 

Also think it would be good to get rid of the Magisk folder on the sdcard. It is very easy for an app to check against it an no "normal" user ever has a Magisk folder on its sdcard.

**Comment by SuperSandro2000** [comment]
> Also think it would be good to get rid of the Magisk folder on the sdcard

would solve one problem with Fortnite and I need to agree with @ShellCode33

**Comment by topjohnwu** [comment]
@ShellCode33 you know why? Because Android's platform `DownloadManager` cannot download to an app's internal data. I'll have to manually write a notification for download progress. It is totally acceptable for me to just download silently in the background and suddenly pop up APK install request out of nowhere right (/sarcasm)?

@shoeper @SuperSandro2000 you might want to check the latest Magisk Manager...... `/sdcard/MagiskManager` is no longer used anywhere. You will have to manually delete the folder previously created if you want to prevent detection, I don't delete files on user's internal storage because it is not responsible for a developer to remove data from a user.

**Comment by mentalisttraceur** [comment]
@topjohnwu Can't you just *copy*/*move* the downloaded file to a privileged location *before* the checksum comparison?

Wouldn't that let you still use the normal download to the normal location using the normal download dialog while still safely aborting if anything modified or overwrote the updated file before actually using it?

**Comment by topjohnwu** [comment]
Fixed in latest changes
