### ISSUE TITLE
Login to Magisk Manager by fingerprint or pin

### ISSUE THREAD

**Issue by THEb0nny** [topjohnwu/Magisk#533]
It is necessary to protect the login to the Manager with a password or an imprint, because if not protect, then you can simply switch (give rights and off right).

**Comment by rdvogp93201** [comment]
And lock the root file manager? All applications with root privileges can modify SU db.
If you need security, revert to stock, lock the bootloader and encrypt your phone.

**Comment by SuperSandro2000** [comment]
@THEb0nny Use AppLock

**Comment by SuperSandro2000** [comment]
> @SuperSandro2000 AppLock can be easily turned off.

As easily as clearing data on magisk manager.

**Comment by THEb0nny** [comment]
@SuperSandro2000 nothing prevents the manager from writing down the settings in the encrypted file to a hidden place.

**Comment by THEb0nny** [comment]
Settings accordingly load, if necessary.

**Comment by topjohnwu** [comment]
@THEb0nny you should protect your whole device with a strong lock screen password, have your data encrypted, and disable USB debugging. There is very little an app can do to protect itself since it is an application after all, it does not have the power to enforce any sense of security once your device is unlocked (implies data encryption decrypted) and exposed to others.

All "applock" stuffs are actually false security (although it is possible to block naive attackers e.g. your average Joe friend or your kid). I would consider adding this feature to Magisk Manager but not on my priority.

**Comment by jyscao** [comment]
@topjohnwu so it looks like you eventually did end up implementing this feature in Magisk Manager. And I must have turned it on a while back just to try out, but eventually came to the same conclusion that it didn't actually provide any real security, so now I'm trying to turn this off. However I can't seem to find how to do this in the Manager's settings now. Am I missing something obvious here?

**Comment by unixandria-xda** [comment]
> @topjohnwu so it looks like you eventually did end up implementing this feature in Magisk Manager. And I must have turned it on a while back just to try out, but eventually came to the same conclusion that it didn't actually provide any real security, so now I'm trying to turn this off. However I can't seem to find how to do this in the Manager's settings now. Am I missing something obvious here?

The only fingerprint protection provided is for su requests

**Comment by jyscao** [comment]
@unixandria-xda I'm getting this whenever I open Magisk Manager, though I forgot how I turned this on.

![photo_2020-09-27_21-35-14](https://user-images.githubusercontent.com/12605746/94382108-80131600-0109-11eb-9430-704d2ad83b85.jpg)

**Comment by unixandria-xda** [comment]
> @unixandria-xda I'm getting this whenever I open Magisk Manager, though I forgot how I turned this on.
> 

That's launcher setting not magisk manager

**Comment by jyscao** [comment]
Maybe you're right. But I'm not convinced that's the case yet as I do recall having turned some feature on through the manager at some point.

**Comment by OmarAwjy** [comment]
> And lock the root file manager? All applications with root privileges can modify SU db. If you need security, revert to stock, lock the bootloader and encrypt your phone.

Sorry for the delay, No.

You can do what i do and just give superuser access for (10 mins) instead of (Forever) , and it is compatible and effective, even if you're using Adaway, Firewall, Shizuku, etc all these requires just a little seconds of superuser access and then it goes without requiring re authentication (except if it needed superuser again to modify a specific thing or access a specific thing),

So no, the root file manager u just give it 10 mins of superuser access and do whatever u want in the file manager, while using "User Authentication" as well to protect the access, and it is necessary to protect the login to the Manager with a password or an imprint because of the "Automatic Response" option conflicts with the "User Authentication" option ; - https://github.com/topjohnwu/Magisk/issues/8635
