### ISSUE TITLE
Issues with module installation

### ISSUE THREAD

**Issue by nazar-pc** [topjohnwu/Magisk#5383]
Device: OnePlus 7 Pro
Android version: 11
Magisk version name: 24.1
Magisk version code: 24101

I just did fresh LineageOS 18.1 installation with latest Magisk. Since repos were removed I had to install modules manually and found that there seems to be some issues:

* [ ] Modules downloaded from GitHub typically have one folder inside of them where all the files are located. This confuses Magisk and results in this:
  ```
  - Copying zip to temp directory
  ! Unzip error
  ```
  This should be easy to fix by checking if there is a lonely directory in the root of the archive. For reproduction I was downloading SSH module using https://github.com/Magisk-Modules-Repo/ssh/archive/refs/heads/master.zip
* [ ] Once I moved files in above archive to the root, installation fails without useful error like this:
  ```
  - Copying zip to temp directory
  - Installing archive.zip
  ! Installation failed
  ```
  It looks like similar error was already reported (can't find it anymore, sorry) and I was able to install module successfully under adb root shell with `magisk --install-module /sdcard/archive.zip`, but would be much more convenient if GUI worked too.

**Comment by topjohnwu** [comment]
Magisk-Modules-Repo is no longer supported. You have to package the zip properly yourself instead of directly downloading the full "source" from GitHub

**Comment by nazar-pc** [comment]
I know that repo is not supported, this is why I went into installing it manually in the first place.

But issues are still valid:
* when you download release from someone's repo or git revision (like above module recommends) people will get into this issue
* even if you download a proper release it doesn' install except through shell

Also I noticed that removal button does nothing, so I can disable modules, but not uninstall :disappointed:

**Comment by nazar-pc** [comment]
Please consider reopening. If there are issues with manual module installation (which is the only way to install modules now), people will come with more and more reports about this.

**Comment by aaronouthier** [comment]
@nazar-pc You're not the only one to have this issue, nor is yours the only issue opened on this topic. I spent 2 hours today alone trying to install some local modules downloaded direct from github.

After some research, it seems the issue is 2-fold:

1) There needs to not be all files inside of a single folder inside of the .zip file. Github by default puts the contents of, for example, modulexyz into a folder called modulexyz-master/ and then zip that up. This won't work. The main files and folders need to be at the root of the zip.

2) The zip file needs to be created with a zip program that doesn't support zip64 extensions. This is the kicker here. There are almost no modern products that meet this criteria. I discovered that Mac computers running High Sierra (10.13) and below work for this purpose. I wish this were not a requirement, as it will trip up many people.

**Comment by nazar-pc** [comment]
Yeah, with such important change as discontinuation of repos (which I can understand)  it would be really beneficial to handle these edge cases during installation from zip archives, both for users and for Magisk maintainers themselves to get less bug reports.

**Comment by aaronouthier** [comment]
https://github.com/Fox2Code/FoxMagiskModuleManager
@nazar-pc
