### ISSUE TITLE
bootloop on shamu after upgrade from 16.0 to 17.1

### ISSUE THREAD

**Issue by adept** [topjohnwu/Magisk#548]
shamu, with latest stock ROM. I tried:
- flashing 17.1 with twrp 3.2.3 over 16.0 -> bootloop
- flashing stock boot image,rebooting, flashing 17.1 with twrp 3.2.3 -> bootloop
- flashing latest uninstaller on top of 16.0, then flashing 17.1 immediately without reboot -> bootloop
- flashing latest uninstaller on top of 16.0, rebooting, then flashing 17.1 -> bootloop

The only option I did not try was patching stock boot image with magisk manager.

"bootloop" here means that phone boots, asks for my pattern, then after ~10-15 seconds (while boot animation is still played) phone reboots and goes to pattern prompt again. I tried looping 5-6 times just in case, but it never proceeds any further.

I dont know how to collect useful logs as I can't get adb shell at any point during bootloop.

For now I downgraded to 16 and things are back to normat

**Comment by djechelon** [comment]
I have been able to reproduce the issue after _ticking_ a number of applications into Magisk Hide. Did not count the actual number, but my goal was to hide all applications from Magisk except a few root-enabled.

Since I had all the ckecboxes ticked before upgrade, the upgrade caused the boot loop directly. After restoring.

When I restored Magisk with all its settings reset, I started to tick the checkboxes again. The boot loop logo appeared after _a number of ticks_. At least 20 I guess but did not count exact number yet. Hope this can be useful to track the issue down

**Temporary Resolution**
Uninstall and reinstall Magisk using the zip file

> fastboot boot twrp.img
> Flash Magisk uninstaller, good time to wipe cache
> Reboot bootloader
> adb flash boot patched_boot.img

**Comment by topjohnwu** [comment]
@adept check @djechelon's solution, I don't think this is a wide spread issue.

@djechelon you definitely should **NOT** hide too many apps, or else your device will get unstable due to the way Magisk currently works.

**Comment by adept** [comment]
@topjohnwu I think this is the third item in my list of things i already tried: i did
```
fastboot boot twrp.img
flash uninstaller
flash magisk 17.1
reboot
```

I even tried re-flashing stock rom completely, rebooting, then booting twrp and installing 17.1 essentially from scratch, without any luck :(

I have (and had before the upgrade) no applications hidden at all, so to me it sounds like me and @djechelon potentially had different issues 

If I flash 16 after 17.1 and reboot, will there be any useful logs left anywhere that I can attach here?
