### ISSUE TITLE
Failed to install a new firmware on Samsung with odin

### ISSUE THREAD

**Issue by GabrielBellard** [topjohnwu/Magisk#5562]
I tried to install a new firmware on my S21 Ultra with Odin 3.14 but the installation is stuck on `<ID:0/008> userdata.img`

![image](https://user-images.githubusercontent.com/5527338/156943549-baffa95d-b95e-4778-88a7-5150466f3098.png)

Firmware used : https://samfw.com/firmware/SM-G998B/BOG/G998BXXU4BVB1

I installed the previous firmware without any issue last month. I don't know where to find more logs to help you.

Device: Samsung S21 ULTRA
Android version: 12
Magisk version name: v24.2 (but same result on v24.1)
Magisk version code: 24201

**Comment by d0td0tslash** [comment]
I'm in the same situation but with a S10+
@GabrielBellard closed this issue - Any additional information here?

**Comment by GabrielBellard** [comment]
Hi,

It was due to a bad transfer between my phone and my PC. The patched file was not completely transfered

**Comment by d0td0tslash** [comment]
Ok, so that was not a Magisk problem in patching the AP

I'm still unable to flash any other software due to "KG State: Prenormal" - Would be curios to understand what you did and to have a chat with you outside of here to avoid adding unrelated content to this issue.
havoc1988 <at> protonmail <dot> com

Thanks in advance

**Comment by TimucinPusat** [comment]
Samsung Galaxy Note 10 Plus (sm-n975f) stuck in Odin USERDATA>userdata.img

Yesterday evening, after downloading the official firmware from sammobile.com, installing the samsung driver, activating OEM Unlocking and USB Debugging mode, I started to flash the firmware with the latest version Odin. It gave md5 error while loading the AP file on Odin. When I searched on the net, it was said to just delete the md5 extension of this file and try again. So I did that and the firmware started to load normally. When the green line was near the end, it stayed there for about 10 minutes. I was in a hurry too. I disconnected the phone from the PC so I could reinstall it at home. 

But the phone gave the warning "An erorr has occured while updating the device software". Neither download nor recovery mode was available. 

Smart Switch did not see the phone. When I tried to reinstall with Odin, the green line under the Odin USERDATA text got stuck towards the end, although there was no line or movement on the phone. No movement for 15-20 minutes. What should I do and what is the outcome of this situation? I would appreciate it if experienced, expert people share information. Thank you in advance. I am waiting. 

![oo](https://user-images.githubusercontent.com/78643996/205241825-438389a6-585b-40ad-96a0-1b4eaae1c1d5.jpg)

**Comment by SiL3NC3** [comment]
> I'm in the same situation but with a S10+ @GabrielBellard closed this issue - Any additional information here?

Same to me

**Comment by meckwarrior** [comment]
I was having the same issue. 
After using the Magisk v30, the step of userdata was skipped.

But I had another Odin stops in the modem.bin ... :(

Finally, I figured out that I didn't unlocked the bootloader correctly.
I write back the original imagem in my S10+, then I properly unlocked the bootader and Starting doing all process, add Magisk patch the AP file and so on.
And the Odin worked well and finish the transfer properly.

I followed thsi video to unlock bootload (it dosen't show, but after its unlock successful. the Developer option Unlock OEM become gray):
https://www.youtube.com/watch?v=_nwmcMgZSbc

And based on this to root (because my screen is broken and I only can see the screen with OTG display):
https://www.youtube.com/watch?v=e3iiIwCGwVA
