### ISSUE TITLE
Lost Root and Magisk won't detect patched Recovery

### ISSUE THREAD

**Issue by shivagnihotri** [topjohnwu/Magisk#5693]
Device: [SHIFT6mq](https://shop.shiftphones.com/shift6mq.html)
Android version: 11
Magisk version name: v24.3
Magisk version code: 24305

Good evening dear Magisk developers and supporters!

This is my updated Issue #5692. I am always running the latest and greatest [LineageOS on my beloved SHIFT6mq](https://download.lineageos.org/axolotl), enjoyed the previous versions of Magisk on it as well. With the the newest transition to Magisk v24.3 I suddenly lost Root and as it appears, Magisk does not detect the patched [recovery image for my device](https://mirrorbits.lineageos.org/recovery/axolotl/20220406/lineage-18.1-20220406-recovery-axolotl.img). Here is the [logfile generated with canary Magisk.](https://github.com/topjohnwu/Magisk/files/8442638/magisk_log_2022-04-07T14_09_51.log)

**Comment by NULL0B** [comment]
It may be related to but is not the same issue, mine is failing to update:
https://github.com/topjohnwu/Magisk/issues/5673

When I moved to magisk 24 i did  to canary 24304 because stable was giving me vmbeta errors.

So i guess that install in recovery functionality was broken in te transition from 23 to 24

**Comment by yujincheng08** [comment]
maybe the same ad #5681 
further investigation requires adb logcat
