### ISSUE TITLE
Magisk cannot patch my boot.img

### ISSUE THREAD

**Issue by StupidRepo** [topjohnwu/Magisk#5724]
Device: Acer Iconia Tab 10 A3-A30
Android version: 5.0
Magisk version name: ?
Magisk version code: 24306

So, I've gotten a boot.img from Acer's website after extracting [the ZIP file](https://global-download.acer.com/GDFiles/OS/OS/OS_Acer_AV0L0.A3-A30.RV14RC02.WW.CUS1_A50L_A.zip?acerid=635896462111370401&Step1=TABLET&Step2=ICONIA%20TAB%2010&Step3=A3-A30&OS=ALL&LC=en&BC=ACER&SC=PA_6) but it seems that when I put it on my tablet and opened it up in Magisk, it said "Installation Failed". Could this be a bug or is it some sort of unsupported .img?

Edit: It also says Process Error under Installation Failed

**Comment by yujincheng08** [comment]
Tested magiskboot can deal with this boot.img.

**Comment by canyie** [comment]
The issue seems to be internel with the magisk app

https://github.com/topjohnwu/Magisk/blob/71e37345b4d48febe5478dfd79287bbfc7042373/app/src/main/java/com/topjohnwu/magisk/core/tasks/MagiskInstaller.kt#L284-L291

Also found the issue has been reported in #3234 but closed without fix 😢 If you still encounter the issue, please upload the installation log

**Comment by StupidRepo** [comment]
Where is the install log located?

**Comment by canyie** [comment]
Click the two "save" buttons after failed to patch boot image
![IMG_20220419_132711_610](https://user-images.githubusercontent.com/31466456/163926167-c7ded82f-812c-494c-96c6-1c983cb599a2.jpg)
![IMG_20220419_132712_473](https://user-images.githubusercontent.com/31466456/163926186-f2e808fe-e222-4d81-ab64-dee1a6884330.jpg)
