### ISSUE TITLE
Magisk cannot show root access confirmation dialogue

### ISSUE THREAD

**Issue by eparla774** [topjohnwu/Magisk#5785]
Device: Meizu Pro 6
Android version: Flyme 8.0.5.0A (Android 7.1.1)
Magisk version name: 63a89d9f
Magisk version code: 24306

For some reason magisk cannot show root access confirmation dialogue when some app calls su command and all requests are blocked because of timeout

If you need any logs or img files or other things, i will upload it

**Comment by zputnyq** [comment]
I believe a logcat is needed for it, it might be an error/s there
I have a little bit similar issue regarding the confirmation dialogue & its timeout as well but on my device it just freeze for milliseconds compared to magisk stable v23 & before (variants of Magisk without zygisk). However I couldn't take a log for it due to it wouldn't show an error on my device.

**Comment by vvb2060** [comment]
I think this should be fixed by #5709, but since you don't provide loggs or a way to reproduce it, close this issue.

**Comment by parvezyaser** [comment]
5709

**Comment by eparla774** [comment]
I can try to compile https://github.com/vvb2060/Magisk/tree/su_request , flash it and say to you if it works

**Comment by drygdryg** [comment]
Have the same issue on FlymeOS 8.0.5.0A (Android 7.0) with Magisk v30.7
