### ISSUE TITLE
Android TV support: Magisk App cannot be fully controlled by remote controller or D-PAD

### ISSUE THREAD

**Issue by tsynik** [topjohnwu/Magisk#5916]
- [x] Items of the module list are focusable but without highlight
- [ ] The log fragment are not scrollable
- [ ] Other accessibility improvement

**Comment by tsynik** [comment]
If you want to leave current behavior when only switches and buttons can be clickable, CardView must be set as focusable="false" (as was done before for some Manager XML layouts on Home) and nextFocusRight="@id/module_indicator" must be removed.

**Comment by xxroot** [comment]
# Environment
Device: oppo reno6 5g
Android version:12
Magisk version name:app-debug.apk
Magisk version code:25001

# inaccessible or not found
OP4ED5:/ $ echo $PATH
/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
OP4ED5:/ $ ls
acct        cache   data_mirror    init                   metadata    my_company      my_preload  my_version  postinstall  second_stage_resources  system
apex        config  debug_ramdisk  init.environ.rc        mnt         my_engineering  my_product  odm         proc         special_preload         system_ext
bin         d       dev            init.environ.rc.patch  my_bigball  my_heytap       my_region   odm_dlkm    product      storage                 vendor
bugreports  data    etc            linkerconfig           my_carrier  my_manifest     my_stock    oem         sdcard       sys                     vendor_dlkm
OP4ED5:/ $ su
OP4ED5:/ # ls
/system/bin/sh: ls: inaccessible or not found
127|OP4ED5:/ # export PATH="/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin"
OP4ED5:/ # ls
acct        cache   data_mirror    init                   metadata    my_company      my_preload  my_version  postinstall  second_stage_resources  system
apex        config  debug_ramdisk  init.environ.rc        mnt         my_engineering  my_product  odm         proc         special_preload         system_ext
bin         d       dev            init.environ.rc.patch  my_bigball  my_heytap       my_region   odm_dlkm    product      storage                 vendor
bugreports  data    etc            linkerconfig           my_carrier  my_manifest     my_stock    oem         sdcard       sys                     vendor_dlkm
OP4ED5:/ #

# 
The problem is that basic commands like ls logcat are available when I am not su, and once I am SU, all basic commands are prompted /system/bin/sh: ls: Inaccessible or not found .
When I reworked export PATH, all the basic commands worked
