### ISSUE TITLE
Canary json entry bug

### ISSUE THREAD

**Issue by DenyDarko** [topjohnwu/Magisk#609]
Hey @topjohnwu :) 

Canary Json file currently gives out a version which does not corresponding to the latest Canary build provided by the update link.

That causes MM to continuous asking for update.

Taking the opportunity, I would like to propose a suggestion.
Make it possible to (re)install Magisk (At least the after OTA) without being required to update MagiskManager first. 

I'm asking for that as I had a small situation with the combination of the issue and the OTA I just got from OnePlus.

**Comment by topjohnwu** [comment]
Sorry for the inconvenience, I fixed the canary channel.

Magisk Manager is intentionally updated first because the app is always designed to be backwards compatible, however Magisk sometimes requires a certain Magisk Manager version and it is not possible to be backwards compatible with old managers
