### ISSUE TITLE
ZipInputStream has issues with certain zip utils in version 25.1

### ISSUE THREAD

**Issue by monochromec** [topjohnwu/Magisk#6103]
Device: FairPhone4
Android version: 11
Magisk version name: Magisk
Magisk version code: 25101

Using ZipInputStream in [ZipUtils.kt](https://github.com/topjohnwu/Magisk/blob/master/app/src/main/java/com/topjohnwu/magisk/core/utils/ZipUtils.kt) proved to be incompatible with certain zip utilities (for an in-depth analysis, please refer to this https://github.com/stylemessiah/SQLite3UniversalBinaries/issues/1).

Perhaps using an alternative zip implementation like jazzlib, etc. may be an option.

**Comment by vvb2060** [comment]
Report to Google or Oracle

**Comment by stylemessiah** [comment]
> Report to Google or Oracle

With respect thats not a great answer/reply given the lengths the submitter went to personally to confirm and locate the referenced file in magisk

The issue seems to be the way extra bytes (created by WinRAR) are handled, as i conformed when zip with 7-zip that the filesize had changed.  WinRAR is a common compression utility after all.

This behaviour with java unzip implementation is also noted in multiple forums, such as:

https://stackoverflow.com/questions/13788373/unzip-error-in-java

Perhaps rethink looking into mitigating it or using an alternate implementation, or perhaps at least warn people in doc that WinRAR compressed modules *may* fail in edge cases ?

For the meantime i have recompressed all my modules in 7-zip to mitigate any further issues

**Comment by vvb2060** [comment]
> warning : 84 extra bytes at beginning or within zipfile. The naive way of skipping the empty bytes is to keep reading till the 'PK' signature is encountered.

Do you really think it's a zip file? We do not support self-extracting archive. I recommend you to update WinRAR to latest(6.11).

**Comment by stylemessiah** [comment]
> > warning : 84 extra bytes at beginning or within zipfile. The naive way of skipping the empty bytes is to keep reading till the 'PK' signature is encountered.
> 
> Do you really think it's a zip file? We do not support self-extracting archive. I recommend you to update WinRAR to latest(6.11).

None of the files were compressed in any other format than zip, certainly NOT self extracting (im not new at creating magisk modules), and they were created using WinRAR 6.11. As noted this seems to be an egde case not widely seen. We're just reporting an issue here...
