### ISSUE TITLE
Bootloop on Samsung Galaxy A13 4G (SM-A137F)

### ISSUE THREAD

**Issue by Exynos-nibba** [topjohnwu/Magisk#6136]
Device: Samsung Galaxy A13 4G(SM-A137F)
Android version: 12 (OneUI Core 4.1)
Magisk version name:  [e463568](https://github.com/topjohnwu/Magisk/commit/e4635684e99e02957b3b75155c73f25f3431b579)
Magisk version code: 25201
extra: SAR, A-only device

My Samsung Galaxy A13 running Android 12 fails to boot on the latest beta, stable and canary releases. I couldn't fetch any logs as the device is currently unrooted, has no custom recovery and shows an adb unauthorized post (ig its bc it isnt a debug build?), the only way i could view any of the logs was through the stock recovery, opened up the last_kmsg and its a bunch of unreadable terminal garbage and couldnt print it to a textfile.

The only visible error that it kept on printing was:
`unable to set property ro.boottime.init.mount.cache, count 1`
`unable to set property ro.boottime.init.mount.cache, count 2`
`unable to set property ro.boottime.init.mount.cache, count 3`

If there is any way in being able to pull meaninful logs out of this device through this current situation, please advise.

Might be unrelated but i have a feeling that [this pull request](https://github.com/topjohnwu/Magisk/pull/4307) might have something to do with this device too, as both of the devices are almost similar except the chipsets, the A13 has an MTK G80. (just a cavemans guess pls dont go off at me xd)

Attached here is the stock boot.img and also the boot.img after its patched by Magisk
[magisk_boot.zip](https://github.com/topjohnwu/Magisk/files/9189088/magisk_boot.zip)
[stock_boot.zip](https://github.com/topjohnwu/Magisk/files/9189085/stock_boot.zip)

Any help would be greatly appreciated.

**Comment by papacharly22** [comment]
Found a video description for the bootloop trouble. Its for the S10 series but sounds interresting. Heres the link. https://youtu.be/TSfQmC4OTZo
Will give it a try tomorrow and report based on my sm-n970f

**Comment by nettnikl** [comment]
> remove the avb flags from the fstab

Hi @Exynos-nibba, could you explain how you did that, and if this is possible without a data wipe? I restarted my phone (without upgrading it or anything) and now i'm also getting this messages. I have no recent backup, because, I didn't change the OS or anything, so I like to recover without a reset (and then do a better backup strategy).

**Comment by ipaqmaster** [comment]
Unzipping each of the reporter's attachments and hastily ripping out the cpio initramfs archive from each with `binwalk -e`, decompressing each ramdisk file with `gzip -d` and piping that output to `cpio -iv` to decompress and unarchive the initramfs files - The only difference between the original and "patched" images is that both `fstab.mt6769t` and `fstab.mt6768` have been modified to omit the `fileencryption=aes-256-xts:aes-256-cts:v2` mount options for the `/cache` mount defined in both fstab files.

This past week I've been working with a bricked Samsung Galaxy S21 5G from a past employee which is OEM-locked and boot looping. No amount of tar.md5 image extraction and flashing with `heimdall-grimler-git`, the odin4 ELF or otherwise seems to be able to revive it.

I noticed in the recovery logs that it's also experiencing this same problem trying to mount /cache over and over again despite flashing it and many other partitions with various attempts for the correct carrier to no avail. Leaving me wondering if this phone might be having the same problem described in this thread.

Google has the mkbootimg project for modifying android boot image files. It can be installed as part of android-tools package on some distros or cloned directly from git with: `git clone https://android.googlesource.com/platform/system/tools/mkbootimg`.

It provides some scripts such as `unpack_bootimg.py` and `repack_bootimg.py` which can be used to safely unpack, modify and repack your device's intended boot.img though I must admit I spent some time on this tonight and had to throw in the towel trying to repack them with the repack_bootimg command and didn't like the results trying to use `mkbootimg --help`

Because I'm out of ideas with this brick I have to consider this avenue as well given the same mount failure logs appear on this phone too. It's OEM-locked so it rejects some of the most important images and I've tried every idea under the sun other than opening it up.

Below is a short and messy script I strung together for unpacking both images for this phone and removing all traces of  `fileencryption=aes-256-xts:aes-256-cts:v2,` from the fstab files which appears to be the only variation used for the `fileencryption` mount option. In my case, /cache was **not** being mounted with this option - so it might be that my issue isn't actually the exact same problem the poster of this issue had experienced. But the option is present for other mountpoints in the fstab files such as `/keyrefuge` and `/data` and t hey did say they "had to remove the avb flags from the fstab to make it properly boot" even if their only partition using the flags was /cache. Still doubtful for relevance however.

```
#!/bin/bash
# Takes all .img files in the same directory as this script and unpacks them, unpacks their initramfs cpio archives and patches their fstab files to remove all traces of the `fileencryption` mount option before repacking the cpio archive. That's as far as I got before needing to tend to other tasks this evening.

_scriptRoot="$(dirname $(realpath $0))"
set -e # Exit on any error
set -o pipefail # Error on pipe errors.

pushd ${_scriptRoot}

# Remove encryption from the fstab files for images in the same directory as the script.
for bootImage in *boot.img
do
  unpack_bootimg --boot_img ${bootImage} --out ${bootImage//.*/}
  bootImageBasename=${bootImage//.*/}
  ramdiskFile=(${bootImageBasename}/*ramdisk) # Array for globbing
  ramdiskExtractDir=${bootImageBasename}/cpio
  mkdir -p ${ramdiskExtractDir}
  bsdtar -xf ${ramdiskFile} -C ${ramdiskExtractDir}

  #cat "${ramdiskFile}" | gzip -d | fakeroot cpio -iv --make-directories -D $(dirname ${ramdiskFile})/cpio || exit 1
  find . -name '*fstab*' -not -name *recovery* -exec sh -c "echo Patching: {} ; sed -i 's/fileencryption=aes-256-xts:aes-256-cts:v2,//g' {}" \;
  pushd ${ramdiskExtractDir}
  find . | cpio -o -c -R root:root | gzip -9 > ../$(basename ${ramdiskFile}).patched
  popd

done
```

I hope this comment can provide useful context to others. I've noticed many threads online regarding this /cache mount problem and many of the results point back to this unanswered thread with no good leads in the other issues either. I may come back to this problem later if free time comes up. This could just be a red herring with a generic error relevant for other boot problems as many of those threads find their own unique and unexpected solutions to this problem as well.f
