### ISSUE TITLE
Magisk does not seem to be installed but root is working

### ISSUE THREAD

**Issue by chickennugget** [topjohnwu/Magisk#6424]
Device:
Android version: 9.0
Magisk version name: 25.2
Magisk version code: 25205

I flashed Magisk ZIP from TWRP into a standard firmware. The device functions properly and the root permits are correctly granted to apps (for example, root checker works properly).

However, after flashing Magisk I install Magisk Manager and in the app it shows the App correctly, while Magisk has installed status N/D, Zygisk No and Ramdisk No (Even if it was set as yes prior to rooting).

In the events history tab, I can see that I granted root access to apps.

Edit: the device is a SM-N950F

**Comment by Nitroandaccounts** [comment]
So super user works? Can you direct install magisk?

**Comment by Nitroandaccounts** [comment]
Also, the TWRP magisk method is depreciated and maintained at a minimum.

**Comment by chickennugget** [comment]
> So super user works? Can you direct install magisk?

Yes, super user works. I cannot install directly magisk as it shows me the error:

"Unable to detect target image
Installation failed"

**Comment by Nitroandaccounts** [comment]
Can you install modules? Do logs shows anything? Logcats show anything?

**Comment by pndwal** [comment]
Guessing you likely had Magisk previously installed with App hidden... Or manager hidden if a very old version... (Nb. Manager has been DEAD since 22.0!
https://topjohnwu.github.io/Magisk/releases/22000.html )

Magisk commonly fails to recognise and remove older hidden apps... In this event simply locate your old hidden app, which is competing for control of core Magisk, and uninstall it... If you can't find it in launcher, search list in Device settings, Apps for whatever custom name you assigned...
