### ISSUE TITLE
Root loss using Magisk 17.2 and "Hide Magisk Manager" option

### ISSUE THREAD

**Issue by White-Rabbit89** [topjohnwu/Magisk#674]
Hi to all,
this morning I've experienced a root loss. I tried to use an app that requires root access (i.e. SD Maid), and I found that root pop-up was not popped up; instead, a toast notification appared to me, saying to me to reboot because root service was not responsive.

I tried to reboot, but I didn't have any success in recover root functionalities. I tried to re-install Magisk 17.2 from TWRP, but nor this try was successfull. I returned to previous version of Magisk (v. 17.1) in order to recover.

I remember that I tried to set "Hide Magisk Manager" three days ago, in order to have root obfuscation using Sky Go app (and the obfuscation worked as expected), but I didn't try to check that after that step I still have my root functionalities, so I don't know if two actions are connected or not.

I use an **Asus Zenfone 2 (ASUS_Z00AD)** with **Android stock build 6.0.1**,, on which I have Magisk installed, and **Xposed v.89.3**.

**Comment by tcmaps** [comment]
Same on Zenfone Zoom (Z00X)

**Comment by ezxpro** [comment]
I suspect this is not related to MagiskHide. Another issue has been created here right after magisk 17.0 and it was related to Magisk disappearing  on reboot. People reported having that issue on 16.7, 17.0 and 17.1 and I experienced that bug in all these versions.
This bug of losing only root access has already happened to me, especially on these latest versions. I also regularly experience a bug where all my modules just disappear, and when that happen soon after (after a few reboots) magisk will disappear. 
I won't even try to debug it, since it seems to happen every time, in every ROM I tried, even stock and because it seems I need to install a canary build to capture the logs.

The solution ( I thought) was to stick to 16.0 and it worked great until I decided to update to magisk 17.1 via magisk manager. After the first reboot all modules disappeared, after the second magisk was gone. I'm gonna open an issue about that and ditch magisk altogether.

**Comment by topjohnwu** [comment]
Fixed

**Comment by yuqiyich** [comment]
I agree u,This bug of losing only root access has already happened to me,and I repeat run ' fastboot boot .\magisk_patched.img',root come out again,and my magisk moudle also exits. 
I  use magisk  version 25.3,and my phone is oneplus 5t with android 10, who can help me
