### ISSUE TITLE
CST and Basic Integrity failure.

### ISSUE THREAD

**Issue by JasonIbarrondo** [topjohnwu/Magisk#683]
Im having a problem with my CST and Basic Integrity. 

The problem occurs when installing ANY module and rebooting. The verification fails. After disabling modules and restarting the phone verification passes. I'm running 7.0 nougat on a Blu Pure View. Flashed through the manager as default. The installation of BusyBox also seems to trigger something but I'm not sure about it. Any help for my situation will be very much appreciated. Thank you.

**Comment by scottesmith2009** [comment]
I have just used a file to add su binary and busybox to sbin in system
only.  Gives you root access w/o supersu or busybox apps..I did add them
afterwards to try and get Flashfire app running properly on my S7.
Download link * https://androidfilehost.com/?fid=5862345805528063752. IDK
Really! But mabye you can  get ideas for your device, and could change
commands/Partitions in  root.Bat to fit your device.  It's just an
idea..nougat & oreo both I think, using ADB..but it would be what you want
to fix issues.  I'm not a big Magisk fan even though Im on this ever so
popular thread..

On Oct 16, 2018 10:16 AM, "JasonIbarrondo" <notifications@github.com> wrote:

Im having a problem with my CST and Basic Integrity.

The problem occurs when installing ANY module and rebooting. The
verification fails. After disabling modules and restarting the phone
verification passes. I'm running 7.0 nougat on a Blu Pure View. Flashed
through the manager as default. The installation of BusyBox also seems to
trigger something but I'm not sure about it. Any help for my situation will
be very much appreciated. Thank you.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/topjohnwu/Magisk/issues/683>, or mute the thread
