### ISSUE TITLE
Magisk Hide on ADB

### ISSUE THREAD

**Issue by zeromod** [topjohnwu/Magisk#688]
ADB is failing to detect root due to magisk hide. 
Scenario : adb root command from pc doesn't work when magisk hide is activated, when disable it and rebooted, command works.
Magisk version : 17.2
Android : 9.0
Device : mido

**Comment by vvb2060** [comment]
Intended behavior. You can use `su` after `adb shell`.

**Comment by vvb2060** [comment]
`su -mm`  use global mount namespace

**Comment by nlburgin** [comment]
If this is intended behavior, then it needs to be documented better, somewhere besides here.

Like in the README.md and/or in [here](https://forum.xda-developers.com/apps/magisk/official-magisk-v7-universal-systemless-t3473445)

It may be intended behavior, but unless Magisk warns that this is going to happen, then it is very counter-intuitive for the user. The user doesn't understand why they get a `adbd cannot run as root in production builds` message, and when they search the internet for answers, usually they find instructions on how to patch the boot img to set the security settings `default.prop` (except in this case, they're already set and Magisk is just hiding them).

I spent the whole day assuming it was my ROM that had failed to set up its `adbd` as root-capable, but it turned out that Magisk Hide was hiding the relevant properties, not just from apps that were specifically enabled for Magisk Hide, but even from `adbd` which is something that one would intuitively expect to have access to root.

And simply running `adb shell` and then `su` is only a partial workaround because it still doesn't give root access to `adb push`, `adb pull`, etc. Unless I'm mistaken, running `su` from `adb shell` doesn't really give you any more access than you'd have by running `su` from the terminal app inside the phone, it doesn't give you the full functionality of a rooted Debug Bridge.

If the design of Magsik Hide is inherently incompatible with rooted debug bridge, that's fine, but users should at least be **warned** of this incompatibility, preventing it from appearing as unexpected and confusing behavior.

**Comment by edrex** [comment]
I am seeing the message with `adb root` but disabling Magisk Hide and rebooting doesn't help (Bullhead/stock 8.1.0). Is there some other condition under which this is known to happen?

**Comment by jimbo1qaz** [comment]
Same issue, moto g5 plus, potter, stock ROM with ElementalX kernel to fix magisk module loopback mounting, Android 7.0. Disabling Magisk Hide and rebooting still produces `adbd cannot run as root in production builds`.

**Comment by daedroza** [comment]
@nlburgin : Thanks for explain things clearly. Clearly, A/B is just a waste of time. I have to flash whole ROM for one line of code change and it is getting on my nerves.

**Comment by ytrezq** [comment]
> Intended behavior. You can use `su` after `adb shell`.

@vvb2060 this is problematic because it also means it‘s impossible to use `adb push` or `adb pull` commands which would require rooting.
Something impossible to do through the shell especially if the files are too large.

**Comment by ytrezq** [comment]
> Same issue, moto g5 plus, potter, stock ROM with ElementalX kernel to fix magisk module loopback mounting, Android 7.0. Disabling Magisk Hide and rebooting still produces `adbd cannot run as root in production builds`.

@nyanpasu64 you have to set `ro.adb.secure=0` and `ro.secure=0` and `ro.oem_unlock_supported=1` and `ro.debuggable=1` in order to get the adb binary to accept running as root (accept to perform the steps required to be launched as root).

But depending on your case (like mine) this isn’t enough as oem security measures might prevent the steps done by the adb binary to become successful.

**Comment by vaishnavmhetre** [comment]
I've observed that [Hsbc India app](https://play.google.com/store/apps/details?id=in.hsbc.hsbcindia) uses adb shell to detect root. Hence Magisk Hide fails whatsoever. 

Any probable solution for this?
