### ISSUE TITLE
Unable to patch boot image on Pixel 6 Pro, Android 14 Beta 3.1 with Canary 26103

### ISSUE THREAD

**Issue by Hondo77** [topjohnwu/Magisk#7109]
Device: Pixel 6 Pro
Android version: Android 14 Beta 3.1
Magisk version name: a8c4a33
Magisk version code: 26103

Unable to patch the boot image on Pixel 6 Pro, Android 14 Beta 3.1. Results in a failed to process cpio error.

Loading cpio: [ramdisk.cpio.orig]
Failed to process cpio: No such file or directory (os error 2)
! Unable to patch ramdisk
! Installation failed

[magisk_install_log_2023-06-23T11.19.11.log](https://github.com/topjohnwu/Magisk/files/11850272/magisk_install_log_2023-06-23T11.19.11.log)

**Comment by srothkin** [comment]
I get same error trying to update a boot.img file on Pixel 6 with canary build 26103. Not sure if it is same issue since it was with file. Rolling back to 26102 I was able to update the file.

`- Device platform: arm64-v8a
- Installing: a8c4a33e (26103)
- Copying image to cache
Parsing boot image: [/data/user_de/0/com.topjohnwu.magisk/install/boot.img]
HEADER_VER      [4]
KERNEL_SZ       [25038091]
RAMDISK_SZ      [0]
PAGESIZE        [4096]
CMDLINE         []
- Unpacking boot image
KERNEL_FMT      [lz4_legacy]
VBMETA
- Checking ramdisk status
- Stock boot image detected
- Patching ramdisk
- Pre-init storage partition: metadata
Add file [init] (100750)
Create directory [overlay.d] (0750)
Create directory [overlay.d/sbin] (0750)
Add file [overlay.d/sbin/magisk32.xz] (100644)
Add file [overlay.d/sbin/magisk64.xz] (100644)
Add file [overlay.d/sbin/stub.xz] (100644)
Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[true]
Loading cpio: [ramdisk.cpio.orig]
Failed to process cpio: No such file or directory (os error 2)
! Unable to patch ramdisk
! Installation failed
`

**Comment by tgice** [comment]
> I get same error trying to update a boot.img file on Pixel 6 with canary build 26103. Not sure if it is same issue since it was with file. Rolling back to 26102 I was able to update the file.

Ugh, I've just run into this too, trying to upgrade to stock 202306 with PixelFlasher on a Pixel 6.

I've struggled to try to rollback Magisk (which I had upgraded to 26103 just before attempting the patching), and can't get it right.

I re-flashed my previous 202305 patched boot.img, and now have Magisk running at 26101 but can't for the life of me get the Magisk app to downgrade to 26101 or 26102 -- it keeps wanting to upgrade to 26103.

Any hints, or reference to an article describing how to do this with recent releases?

**Comment by blueset** [comment]
> Any hints, or reference to an article describing how to do this with recent releases?

I uninstalled Magisk fully (both boot.img and app), restarted my phone, downloaded the latest Beta release app (26100), patched the `boot.img` with the app, and then flashed it with PixelFlasher. That got me to a flashable state and upgraded my Pixel 6 Pro to 202306 succesfully.

**Comment by Nekolaa** [comment]
Help me

**Comment by tgice** [comment]
> 

blueset, thanks for the suggestion.  I was finally able to get this working with just a few short steps.

I didn't fully uninstall Magisk, just the app.  I left the device rooted, to the rolled-back 202305 image (with 26100 Magisk on it).  Then I think I rebooted, hooked up to PixelFlasher and used it to install Magisk beta 26100, which it did, over USB.

At that point I was running 202305 patched with 26100, and running 26100 in the app, so I again tried to patch 202306 with PixelFlasher and this time it worked, and I was able to then flash the patched image to my Pixel 6 and things are working.

The only thing that's odd is that whenever I launch Magisk now, it pops a dialog:

> *Requires Additional Setup*
> 
> Your device needs additional setup for Magisk to work properly.  Do you want to proceed and reboot?

and if I OK on that, I think it'll upgrade it to 26103, which I don't want at this point.  I can just press Cancel and continue to use Magisk as normal (I think), but it's a little annoying and I doubt it would've happened if I hadn't already upgraded to 26103 once.

Anyway, thanks for the assistance.

**Comment by zhuanyi** [comment]
Any chance that this fix was in place but it wasn't placed in magisk-file repo? It looks like the Canary version was last released from 3 wks ago (fom what I can see in: https://github.com/topjohnwu/magisk-files) and the patch was applied 2 wks ago.

**Comment by lssong99** [comment]
it seems not yet put into the canary release. However, you could use the patched "boot_patch.sh" and run from rooted shell directly to patch affected boot.img. Please don't forget to set environment variables as described in the boot_patch.sh.

The link to patched, working boot_patch.sh is located at: https://github.com/topjohnwu/Magisk/blob/33a9abc94665672e4e5692da64c1b3f026a62704/scripts/boot_patch.sh

"boot_patch.sh" needs to be run from rooted shell, Magisk.apk will always use old way even if the /scripts/boot_patch.sh are replaced with this new version. Developmer will need to release a new version for this to be incorporated into Magisk.apk.

**Comment by Hondo77** [comment]
Can confirm that Canary 26104 has resolved this issue. Patching the boot image on my Pixel 6 Pro running Android 14 Beta 4 was successful with Canary 26104.
