### ISSUE TITLE
Device stuck in boot animation after activating Zygisk on Magisk 26104

### ISSUE THREAD

**Issue by KaMyKaSii** [topjohnwu/Magisk#7191]
Device: Quantum Go Q2
Android version: 7.1.1
Magisk version name: d390ca2f
Magisk version code: 26104

I decided to uninstall the current Magisk 25200 installation with Zygisk enabled and do a clean install of version 26104 and Android starts normally with the new Magisk installed. But after activating Zygisk and restarting, the system is stuck in boot animation, attached logcat ran while device was in boot animation for 50 minutes. Going into TWRP and manually removing the /data/adb/magisk.db file to reset Magisk to default causes the system to boot again, so the problem is caused by some change in Zygisk implementation between versions 25200 and 26104.

[Boot and Magisk logs.zip](https://github.com/topjohnwu/Magisk/files/12208086/Boot.and.Magisk.logs.zip)

**Comment by b-risk** [comment]
Same issue here.

**Comment by KaMyKaSii** [comment]
It might be a good idea to also create a command to disable Zygisk (or return Magisk to default), just like there is a command `magisk --remove-modules` to fix bootloop caused by some module. So users without a working TWRP install can get their devices to boot again more easily.

**Comment by FuccDucc** [comment]
Can't reproduce on my Motorola, so it must be device specific bug

**Comment by ohoheli** [comment]
> Same issue here, just I wasn't able to boot into Magisk at all when i flashed it onto my device because it was stuck in the boot animation.

I got the same issue. What's the step by step guide to return magisk to default? 

Any leads would be much appreciated.

**Comment by nguyenhoangphuc121** [comment]
> 
change magisk canary channel to stable

**Comment by Mikmokless** [comment]
@KaMyKaSii 


Hey there, i uninstalled Magisk from my device (Samsung S10 duos) from inside the magisk app because my bank apps wont work and after googling a little i learnt is the Magisk app that was the issue. During the uninstall a couple code looking stuffs flashed and it automatically sent the device into a reboot.
It tries to boot then shows a recovery menu with the following texts below:

Reboot Recovery Cause is [UNKOWN]#
E: [libfs_mgr] Unable to disable quotas on /dev/block/platform/13d60000.ufs/by-name/userdata because /system/bin/tune2fs missing.
Supported API: 3

MANUAL MODE v1. 0. 0#

I desperately need help getting out of this as the **files on the device are of utmost importance.**
I have tried the option of wiping cache as i had recently read online, didn't work either.

I am not a tech person, but can follow instructions with exactness.

All inputs leading to a solution would be highly appreciated.

**Comment by osm0sis** [comment]
Try 26203?

**Comment by TyrasNistru** [comment]
Happened to me as well. Just installed Magisk on my ZS620KL (Zenfone 5z). Before enabling Zygisk, everything was working ok, but after enabling it and rebooting, it gets stuck at the "Powered by Android" logo for a few minutes and then goes straight to fastboot mode. 

Had to reflash the stock rom (without magisk) to make it boot.

**Comment by canyie** [comment]
```
07-29 17:13:17.278   287   287 F art     : art/runtime/jni_internal.cc:492] JNI FatalError called: frameworks/base/core/jni/com_android_internal_os_Zygote.cpp:500: Unable to construct file descriptor table.
07-29 17:13:17.279   862   862 E Zygote  : Unsupported st_mode 4480
07-29 17:13:17.279   862   862 F art     : art/runtime/jni_internal.cc:492] JNI FatalError called: frameworks/base/core/jni/com_android_internal_os_Zygote.cpp:500: Unable to construct file descriptor table.
```

**Comment by Da-OldMan** [comment]
You can try magisk with the fix that works for my bug report:
[app-debug.zip](https://github.com/topjohnwu/Magisk/files/12708185/app-debug.zip)

**Comment by zygisk22** [comment]
> It might be a good idea to also create a command to disable Zygisk (or return Magisk to default), just like there is a command `magisk --remove-modules` to fix bootloop caused by some module. So users without a working TWRP install can get their devices to boot again more easily.

I recommend adding a command line option for magisk similar to --remove-modules which does not need root in order to disable zygisk as it can cause system instability (missing status bar, system slow down and halting in my case running graphene os on pixel 8 pro) but even more detrimental stop the system from booting entirely which limits the ability to disable it. MagiskHide iirc when entering safe mode was disabled along with the modules, zygisk is not disabled automatically in this case. Even if you disable magisk by loading a stock init_boot/boot image in order to boot then you have no way to disable zygisk as accessing /data/adb/magisk.db requires root. Unless your shell has been granted root permissions prior then you have no way to use adb shell to fix this whether in safe mode or during the regular bootup since you cannot approve root permissions through the magisk app. And not everyone has a custom recovery, whether it be twrp or a modified stock recovery with adb and root enabled.

If you gain a shell with root then you can run:
magisk --sqlite "UPDATE settings SET value = 0 WHERE key = 'zygisk'" 
or simply delete the /data/adb directory to restore magisk to default condition.

Alternatively perhaps there is a way to add authorized root apps (in this case the system shell) to the magisk database through adb or in safe mode without interacting with the magisk app popup itself to approve it (highly doubt that's possible since that seems to be the sole gatekeeper).

The command line option and the autodisable in safe mode are two valuable features which should probably be available to the user so that they are not in a catch 22 with no way to disable zygisk unless they have root access of some sort.

I personally was stuck with my pixel 8 pro in this fashion after enabling zygisk. I was able to disable magisk and boot but no way to disable zygisk and re-enable magisk. Eventually the only solution I found other than wiping the phone or building some custom recovery was patching the stock init_boot with the latest canary build and flashing it then when I was able to boot regularly with root then I also upgraded the magisk app too which solved this zygisk issue however this problem could repeat itself in many variations as zygisk can affect the system just as much as any other module and it should have a foolproof way to be disabled seperate from the disabling of magisk itself.

**Comment by zygisk22** [comment]
And as a side note to anyone else experiencing this specific issue, apparently there is a quick fix for graphene os running on pixel 8 pro (and other phones probably) by disabling "secure app spawning". 

https://xdaforums.com/t/need-help-stuck-at-phone-is-starting-after-enabling-zygisk.4642084/
https://droidwin.com/fix-grapheneos-stuck-at-phone-is-starting-after-enabling-zygisk/

**Comment by ctsbrasil** [comment]
Hi. Same problem here, using a **Xiaomi Mi 9 SE**. 

After install Magisk v26.4 and activate Zygisk in configuration and restart, it pass the MIUI animation, and turns all black, the only thing that works is the power button (what gave me the options to power off or restart - If I restart, does the same). 

I had to unistall Magisk v26.4 and install back Magisk 26.3 (activate zygisk in this version, and everything is fine). 
Not using Magisk v26.4 untill a fix came out.

**Comment by zygisk22** [comment]
> If you gain a shell with root then you can run: magisk --sqlite "UPDATE settings SET value = 0 WHERE key = 'zygisk'" or simply delete the /data/adb directory to restore magisk to default condition.

Small tip if you are trying to run a complex command such as the one above through adb shell while booting up, do not run it with the "wait-for-device" flag since I've found it doesn't work well, if at all, when you have multiple quotations and apostrophes. Instead just run "adb wait-for-device shell su" and then when you get the shell immediately enter your command.

**Comment by ctsbrasil** [comment]
Thanks for your reply, 
I will try to install v26.4 again when i had more time, and try workaround with this issue.

**Comment by zbysogi** [comment]
> Hi. Same problem here, using a **Xiaomi Mi 9 SE**.
> 
> After install Magisk v26.4 and activate Zygisk in configuration and restart, it pass the MIUI animation, and turns all black, the only thing that works is the power button (what gave me the options to power off or restart - If I restart, does the same).
> 
> I had to unistall Magisk v26.4 and install back Magisk 26.3 (activate zygisk in this version, and everything is fine). Not using Magisk v26.4 untill a fix came out.

Hi. I can't even install older version without having the same exact problem. The older version is automatically promoting to upgrade to newer version. Any upcoming fixes?

**Comment by crunchbank** [comment]
After trying everything you guys did I was able to rescue my device by installing Magisk 26.0 (it runs despite zygote enabled) and disabling zygote in the app. Then update to 26.4.

**Comment by KaMyKaSii** [comment]
> > Hi. Same problem here, using a **Xiaomi Mi 9 SE**.
> > After install Magisk v26.4 and activate Zygisk in configuration and restart, it pass the MIUI animation, and turns all black, the only thing that works is the power button (what gave me the options to power off or restart - If I restart, does the same).
> > I had to unistall Magisk v26.4 and install back Magisk 26.3 (activate zygisk in this version, and everything is fine). Not using Magisk v26.4 untill a fix came out.
> 
> Hi. I can't even install older version without having the same exact problem. The older version is automatically prompting to upgrade to newer version. Any upcoming fixes?

If you just install an old version of Manager app it will always ask to update and then install/upgrade to the latest Magisk. To install an old version of Magisk, you have to rename the apk to zip and then install it through TWRP. Or take your device offline and then use the outdated Magisk app to patch the boot image and flash it using fastboot or similar

**Comment by zbysogi** [comment]
> > > Hi. Same problem here, using a **Xiaomi Mi 9 SE**.
> > > After install Magisk v26.4 and activate Zygisk in configuration and restart, it pass the MIUI animation, and turns all black, the only thing that works is the power button (what gave me the options to power off or restart - If I restart, does the same).
> > > I had to unistall Magisk v26.4 and install back Magisk 26.3 (activate zygisk in this version, and everything is fine). Not using Magisk v26.4 untill a fix came out.
> > 
> > 
> > Hi. I can't even install older version without having the same exact problem. The older version is automatically prompting to upgrade to newer version. Any upcoming fixes?
> 
> If you just install an old version of Manager app it will always ask to update and then install/upgrade to the latest Magisk. To install an old version of Magisk, you have to rename the apk to zip and then install it through TWRP. Or take your device offline and then use the outdated Magisk app to patch the boot image and flash it using fastboot or similar

Installing magisk via twrp or flashing the magisk boot.img file results in phone being stuck on miui logo 4 ever. I reckon only clean install will help so format is needed

**Comment by KaMyKaSii** [comment]
> > > > Hi. Same problem here, using a **Xiaomi Mi 9 SE**.
> > > > After install Magisk v26.4 and activate Zygisk in configuration and restart, it pass the MIUI animation, and turns all black, the only thing that works is the power button (what gave me the options to power off or restart - If I restart, does the same).
> > > > I had to unistall Magisk v26.4 and install back Magisk 26.3 (activate zygisk in this version, and everything is fine). Not using Magisk v26.4 untill a fix came out.
> > > 
> > > 
> > > Hi. I can't even install older version without having the same exact problem. The older version is automatically prompting to upgrade to newer version. Any upcoming fixes?
> > 
> > 
> > If you just install an old version of Manager app it will always ask to update and then install/upgrade to the latest Magisk. To install an old version of Magisk, you have to rename the apk to zip and then install it through TWRP. Or take your device offline and then use the outdated Magisk app to patch the boot image and flash it using fastboot or similar
> 
> Installing magisk via twrp or flashing the magisk boot.img file results in phone being stuck on miui logo 4 ever. I reckon only clean install will help so format is needed

If your TWRP can decrypt the contents of the data partition, it might be worth trying deleting the current Magisk binaries and configuration and letting the old Magisk installed in the boot image populate the files again
`rm -rf /data/adb/*`

**Comment by zbysogi** [comment]
> > > > > Hi. Same problem here, using a **Xiaomi Mi 9 SE**.
> > > > > After install Magisk v26.4 and activate Zygisk in configuration and restart, it pass the MIUI animation, and turns all black, the only thing that works is the power button (what gave me the options to power off or restart - If I restart, does the same).
> > > > > I had to unistall Magisk v26.4 and install back Magisk 26.3 (activate zygisk in this version, and everything is fine). Not using Magisk v26.4 untill a fix came out.
> > > > 
> > > > 
> > > > Hi. I can't even install older version without having the same exact problem. The older version is automatically prompting to upgrade to newer version. Any upcoming fixes?
> > > 
> > > 
> > > If you just install an old version of Manager app it will always ask to update and then install/upgrade to the latest Magisk. To install an old version of Magisk, you have to rename the apk to zip and then install it through TWRP. Or take your device offline and then use the outdated Magisk app to patch the boot image and flash it using fastboot or similar
> > 
> > 
> > Installing magisk via twrp or flashing the magisk boot.img file results in phone being stuck on miui logo 4 ever. I reckon only clean install will help so format is needed
> 
> If your TWRP can decrypt the contents of the data partition, it might be worth trying deleting the current Magisk binaries and configuration and letting the old Magisk installed in the boot image populate the files again `rm -rf /data/adb/*`

That's what makes the phone stuck on miui logo. As I said, I cleaned the phone from any magisk files by uninstalling it via twrp and then flashed older version of magisk boot.img through adb. Nothing worked. I reckon I tried so many times that the system won't even boot normally and the only solution would be to format which I don't want to do at the moment, don't have the time for it.
