### ISSUE TITLE
Device support Axon 7 A2017U for Magisk 17.x bootloops to recovery

### ISSUE THREAD

**Issue by bluenote73** [topjohnwu/Magisk#729]
Hi

Magisk 16.7 works fine on stock Rom B35 Nougat, but 17.1 and 17.3 both bootloop to recovery.
I don't observe any errors in the install process, it appears to work properly at least from what the Magisk script displays as it installs.  I have done an uninstall before installing as well, no change.

Here is the stock boot stack and /system (in post 2): https://forum.xda-developers.com/showpost.php?p=68873482&postcount=2

Please let me know if there's anything more needed.  For reference I was also originator of 13.x issue solved here: https://github.com/topjohnwu/Magisk/issues/229

Thanks

@Dryness in case you're still on this phone too?

**Comment by Dryness** [comment]
I am on the unofficial B12 Oreo release, using 16.7 without issue.
However, I also experience bootloops after installing any of the 17.x versions.  No errors appear in the TWRP log during or post install for me either.  

The boot image and bootstack for my ROM can be found in the following post, though the fix for Nougat I suspect may fix Oreo:
https://forum.xda-developers.com/axon-7/how-to/official-beta-android-8-0-0-v2-10b12-t3797085

**Comment by bluenote73** [comment]
I should clarify that i used the word "bootloop" incorrectly. Rebooting to the system does not work, it just boots to recovery each time, and if i reboot, it goes to recovery again. Sorry for the sloppiness.

**Comment by Dodgexander** [comment]
FYI I also have this issue but using the workaround posted by asderdd@xda here: https://forum.xda-developers.com/axon-7/development/kernel-magisk-17-stock-roms-t3856809 gets magisk working for me on Oreo.

Too cut a long story short this results in magisk hide being broken and some modules not functioning correctly as a result.

Here are the logs from my Magisk Canary build on stock b20 Oreo. On earlier versions magisk log is empty.
""Vold-posix : - Patching boot image
Vold-posix: - Target image: /dev/block/sde12
Vold-posix: - Unpacking boot image
Vold-posix: - Checking ramdisk status
Vold-posix: - Magisk patched boot image detected
Vold-posix: - Patching ramdisk
Vold-posix: - Repacking boot image
Vold-posix: - Flashing new boot image
Vold-posix: - Done, reboot to apply.""

I'm not sure if this helps with this issue but the bootloops using anything other than v16.7 is the case on all ZTE axon 7 stock ROMs.

I know that John doesn't like incorrectly reported bugs but I'm not sure what extra we can get? The bootloop means we can't get a logcat or dmesg. Maybe seeing the workaround will help him see what's wrong. I hope so at least because it would be great to get it working 100%

**Comment by Dodgexander** [comment]
My log was in error. Here's another:
"11-06 00:04:42.745  1275  3042 F libc    : Fatal signal 7 (SIGBUS), code 1, fault addr 0x7dd27c0c31 in tid 3042 (IzatProvider)
11-06 00:04:42.894  3118  3118 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-06 00:04:42.894  3118  3118 F DEBUG   : Build fingerprint: 'ZTE/P996A01_O/ailsa_ii:8.0.0/OPR1.170623.032/20180815.171922:user/release-keys'
11-06 00:04:42.894  3118  3118 F DEBUG   : Revision: '0'
11-06 00:04:42.894  3118  3118 F DEBUG   : ABI: 'arm64'
11-06 00:04:42.894  3118  3118 F DEBUG   : pid: 1275, tid: 3042, name: IzatProvider  >>> system_server <<<
11-06 00:04:42.894  3118  3118 F DEBUG   : signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0x7dd27c0c31
11-06 00:04:42.894  3118  3118 F DEBUG   :     x0   0000007dd2ad6700  x1   0000007da083fde4  x2   0000000000000002  x3   0000000000000004
11-06 00:04:42.894  3118  3118 F DEBUG   :     x4   0000000000000ace  x5   0000000000000004  x6   000000000000000e  x7   0000000000000ac0
11-06 00:04:42.894  3118  3118 F DEBUG   :     x8   0000007da083fd80  x9   0000007dd27c0c31  x10  0000007da8469798  x11  000000000000006b
11-06 00:04:42.894  3118  3118 F DEBUG   :     x12  0000000000000000  x13  00000000000016be  x14  0000000000000022  x15  0000000000000008
11-06 00:04:42.894  3118  3118 F DEBUG   :     x16  0000007da083fdd0  x17  0000000000000018  x18  0000000000000020  x19  0000007da84697a0
11-06 00:04:42.894  3118  3118 F DEBUG   :     x20  0000007da8456b14  x21  0000000013940210  x22  00000000160a1fb0  x23  0000000013955250
11-06 00:04:42.894  3118  3118 F DEBUG   :     x24  00000000139551e8  x25  0000000013940158  x26  0000000070872918  x27  0000000000000000
11-06 00:04:42.894  3118  3118 F DEBUG   :     x28  0000000000000000  x29  0000007da083fdc0  x30  0000007da8456b70
11-06 00:04:42.894  3118  3118 F DEBUG   :     sp   0000007da083fd60  pc   0000007dd27c0c31  pstate 0000000020000000
11-06 00:04:42.901  3118  3118 F DEBUG   : 
11-06 00:04:42.901  3118  3118 F DEBUG   : backtrace:
11-06 00:04:42.901  3118  3118 F DEBUG   :     #00 pc 0000000000543c31  /system/lib64/libart.so
11-06 00:04:42.901  3118  3118 F DEBUG   :     #01 pc 0000000000013b6c  /system/lib64/liblocationservice_jni.so (_ZL8onEnableP7_JNIEnvP8_jobjecti+88)
11-06 00:04:42.901  3118  3118 F DEBUG   :     #02 pc 0000000000281704  /system/priv-app/com.qualcomm.location/oat/arm64/com.qualcomm.location.odex (offset 0x98000)
Vold-posix: - Patching boot image
Vold-posix: - Target image: /dev/block/sde12
Vold-posix: - Unpacking boot image
Vold-posix: - Checking ramdisk status
Vold-posix: - Magisk patched boot image detected
Vold-posix: - Patching ramdisk
Vold-posix: - Repacking boot image
Vold-posix: - Flashing new boot image
Vold-posix: - Done, reboot to apply."

**Comment by Dryness** [comment]
I can confirm that I'm experiencing the same behaviour as the 17.x builds, and am still unable to boot system after flashing 18.x.

**Comment by Dodgexander** [comment]
Same here, still doesn't seem to like to work on A2017U Oreo B20 release. For some reason v16.7 was the last version to work.

Using the patched boot image here: https://forum.xda-developers.com/axon-7/development/kernel-magisk-17-stock-roms-t3856809

Lets magisk v17 at least boot, but it doesn't work properly still, magisk log is always empty and some modules don't boot.

**Comment by jawz101** [comment]
I tried Magisk 17.3, 18.0 and 18.1 on ZTE Axon 7 update B19 and B35.  phone reboots into recovery every time.

**Comment by topjohnwu** [comment]
#980

**Comment by bluenote73** [comment]
@Dryness @Dodgexander  I went through a couple iterations of installing, uninstalling, installing, using the latest, plus older uninstallers, then installing, and v19.0 beta still just boots to recovery for me.  Before I start complaining it would be good if you guys could confirm?

**Comment by Dodgexander** [comment]
@bluenote73 I'm not certain these changes are in the official beta. I've been using the custom builds here: https://github.com/ianmacd/MagiskBuilds

You'll still need the magisk module from here as WiFi is broken: https://forum.xda-developers.com/showthread.php?t=3856809

**Comment by bluenote73** [comment]
@Dodgexander are you saying that otherwise, that beta of magisk does in fact work, but it breaks wifi?

**Comment by Dodgexander** [comment]
> @Dodgexander are you saying that otherwise, that beta of magisk does in fact work, but it breaks wifi?

Yes. Magisk Hide is fixed with that release (Ianmacd) but it still breaks wifi so you still need the module linked (xda) last post to fix the wifi issue.

**Comment by bluenote73** [comment]
I've just tried this on v19.1 and it still has the exact same behaviour, just boots to recovery each time.
@topjohnwu perhaps you could reopen?

**Comment by japzone1** [comment]
Also encountering this still. Reboots into Recovery when using 19.1 just like it was 17.x+

**Comment by Dodgexander** [comment]
Can confirm this is still broken @topjohnwu

**Comment by bluenote73** [comment]
@Dodgexander unfortunately everyone involved with development is making this a lot harder to document and explain than it needs to be.  Can you confirm that one can use 19.x with asderdd's modification?  Even though we've both linked all this stuff, apparently it needs to be ... presented better to the dev's to be taken seriously.

**Comment by Dodgexander** [comment]
Part of the issue @bluenote73 is there are two issues. 

Issue 1 - Magisk Hide not working.

This has been fixed with recent builds and is the fix that @topjohnwu referenced above.

Issue 2 - Magisk causing device to bootloop.

This can be fixed by using asderdd's modification and magisk module patch. He has customised the stock boot image which in turn caused WiFi to break which he then patched with his module.

Issue 2 is still present as far as I am aware, but I have not tested v19.2 Magisk which does mention fixes for "Chinese" devices so maybe that acts differently.

Perhaps a new issue should be opened mentioning issue 2, as for all intense and purposes it seems that John thinks this has now been solved.

**Comment by bluenote73** [comment]
@Dodgexander He's aware it's still broken because I opened a new issue asking for this one to be reopened since I only reference booting to recovery in this definition, and he closed it with "not enough information".  I'm getting pretty frustrated.  Would you consider opening a new issue and giving them "enough information" ? :/

**Comment by Dodgexander** [comment]
> 
> 
> @Dodgexander He's aware it's still broken because I opened a new issue asking for this one to be reopened since I only reference booting to recovery in this definition, and he closed it with "not enough information". I'm getting pretty frustrated. Would you consider opening a new issue and giving them "enough information" ? :/

Its hard to give enough information because there are no logs or anything that can be passed on. This was the original problem I faced when I wanted to help report this issue. If you read the documentation and the procedure for filing a bug report it mentions things like Magisk log's and dmesg's.

None of this really applies, its not possible to pass information that isn't there. The issue happens before the phone boots up and before any logs are created. The only thing you can pass on is a installation log for magisk which only tells us it was installed successfully. 

If you are able to somehow log what happens when the device bootloops then that will help, but I think the whole issue here is it happens before any logs take place, with no info to pass on for it to be fixed.

Even asderdd who fixed the problem doesn't fully understand it, I already asked if he could add info here.

So I can see why its frustrating, for sure. I'm not running stock any more but I certainly can. But I can also see why it is that nothing has been done.

If nothing can be passed on that's useful to solving the issue, how can it be solved? To be fixed something wrong has to be logged in the first place and short of someone with the know-how from ZTE being able to log pre-boot actions I don't really see this changing.

**Comment by cntube** [comment]
the same issuse.
