### ISSUE TITLE
ADB not working over Huawei devices

### ISSUE THREAD

**Issue by Dil3mm4** [topjohnwu/Magisk#738]
Hello there, 
this issue was solved on 16.5 over Oreo ROMs. 

As of now the issue has appeared again with any build (canary/stable) and we're not able to get the device listed over the command `adb devices` (nor other commands via adb)

Tested over GSI Pie ROMs. 

If you need something additional infos, please, let me know.

**Comment by Dil3mm4** [comment]
I guess this is no longer working
https://github.com/topjohnwu/Magisk/commit/a6958ac13965ccad2e97da202321b84024df27c4#diff-94ef7dd6f867516e6b55f7b08479b8ebR537
since /sbin folder hasn't adbd bin in it

**Comment by Mdjbot79** [comment]
Why would you use a Huawei device......
Just go back to Samsung or LG and then you will not have the same problems
nobody works on or develops root methods for knock off bullshit

**Comment by topjohnwu** [comment]
@Dil3mm4 can you give me the output of `cat /proc/mounts` without installing Magisk? Thanks!

**Comment by Dil3mm4** [comment]
This is while Magisk is installed[
mountsmagisked.txt](https://github.com/topjohnwu/Magisk/files/2525489/mountsmagisked.txt)

This is while Magisk is not installed
[unmagiskedmounts.txt](https://github.com/topjohnwu/Magisk/files/2525506/unmagiskedmounts.txt)

For reference I think that you'll find useful this references:
https://github.com/phhusson/device_phh_treble/blob/0874fd8bc3e1604ba46a58edc2b6edb843254bad/vndk-detect#L12

when it gets triggered
https://github.com/phhusson/device_phh_treble/blob/006a105a320cee501733009eac75b1be517d69f3/vndk.rc#L2

its context:
https://github.com/phhusson/device_phh_treble/blob/aea19262a01e2f91287e4b5a9795f3cc411eb207/sepolicy/file_contexts#L2

Bonus info: running adbd from Terminal emulator via root privileges restores adb functionality (tho it seems "stripped down" infact adb remount it's failing denying attempts to push files onto system returning "read-only")

@Mdjbot79 Well, if you have a spare mid-tier device to send out I'd be glad to get rid of my Huawei phone. 
Unfortunately I'm not the kind of guy that each year buys a new phone, I keep them until their end of life (hardware side). 
When I bought this it was the period when Huawei was hyping its OSS program, so, since I'm not a clairvoyant I couldn't expect what happened later.

**Comment by topjohnwu** [comment]
@Dil3mm4 Why are there multiple `/sbin/adbd` mounts, and there is even a bind mount to `/system/bin/adbd`? From what I can see, phh's treble is pretty messed up and I really don't want to spend time fixing a ROM that uses so many dirty hacks without much consideration from the beginning...

If maybe one day I'm to bored I might get a chance to install a GSI on one of my devices, and I can try to fix the ROM.

**Comment by phhusson** [comment]
Oh well, that's interesting
My GSI only does one mount bind to /sbin/adbd, and I don't mount bind /system/bin/adbd at all (I've checked on one of my device, though not on a Huawei yet)

**Comment by topjohnwu** [comment]
@phhusson haha sorry the language I used was a bit extreme, wasn't in a good mood at that time and after seeing a big mess in `/proc/mounts` triggered me a bit. But what I said is really what I feel: you aim to support the maximum amount of devices with a single GSI, and most of the time it requires you to use some really wild hacks to accomplish it.

And also, I believe it is quite obvious that you don't spend effort on trying to support Magisk, I remember even seeing you recommending people *not* to use Magisk because it breaks stuffs. Magisk is based on the assumption of normal ROMs, not the custom hacks required for the general GSIs. People come to me to complain bugs that I can't understand what's even going on since there are already enough crazy stuffs happening on all kinds of devices, I don't have time to test every custom ROM out there, including GSIs.

I would be grateful even if you can point out the culprit that causes issues when Magisk is installed on GSIs. A pull request for a fix, or maybe some adjustments on your side would be highly appreciated.

**Comment by penn5** [comment]
Just wanted to add this, I have the same issue as dil3mm4, same chipset, etc. 
```
11-07 08:39:48.425   560   560 I Magisk  : ** Initializing Magisk
11-07 08:39:48.427   560   560 I Magisk  : * Creating /sbin overlay
11-07 08:39:48.443   560   560 E Magisk  : open: /sbin/adbd failed with 30: Read-only file system
11-07 08:39:48.443   560   560 E Magisk  : sendfile failed with 9: Bad file descriptor
11-07 08:39:48.445   560   560 E Magisk  : linkat adbd->adbd failed with 18: Cross-device link
```

I'm on a pie gsi (descendant, based on phh v106). Weirdly, the issue only began after switching from the stock EMUI kernel to Labyrinth r2.1.

**Comment by penn5** [comment]
If https://github.com/topjohnwu/Magisk/blob/master/native/jni/daemon/bootstages.cpp#L614 were changed to bind mount instead of copy, I think this would work...

**Comment by penn5** [comment]
@topjohnwu ping
just fyi, i havent checked that my fork of magisk is actually buildable.
