### ISSUE TITLE
Boot hangs after flashing patched image

### ISSUE THREAD

**Issue by 43615** [topjohnwu/Magisk#7534]
Device: SM-N976B
Android version: Lineage 20.0-20231112 (Android 13, kernel 4.14.316)
Magisk version name: aa6c7c15
Magisk version code: 26401

Just updated Lineage to the latest build and trying to reinstall Magisk. Boots fine on its own, but flashing a patched boot.img causes it to get stuck on the Lineage boot screen (stuck, not rebooting). Tried leaving it like that for 15+ minutes, no apparent change and device is noticeably warm from CPU usage.
No difference between release 26400 and debug build 26401.
Can't attach the images in question to the issue, you can get them from my NAS [here](https://43615.xyz/sharing/h1mH01Ol5).
If you need logs, please be nice and tell me how to get them. I'm willing to cooperate but a bit clueless.

**Comment by Unknown78** [comment]
Please try [the latest successful build that was pushed by topjohnwu](https://github.com/topjohnwu/Magisk/actions/workflows/build.yml?query=branch%3Amaster+is%3Asuccess+event%3Apush+actor%3Atopjohnwu).
> Currently it is [cfb20b0f86414d851b51e10cd633328d405ca4f7](https://github.com/topjohnwu/Magisk/suites/18073040664/artifacts/1041400471)

Click to download, extract the .zip file, you'll find the .apk to install.
Unhide and uninstall previous installation of Magisk.
Install it to get the App and do Direct-Install patch as usual.
If `app-release.apk` didn't work, try `app-debug.apk`. Both App and Direct-Install patch.

<hr>

If that didn't work, then we need logs with App and Direct-Install from that `app-debug.apk`.

Desktop requirements:
- Phone USB Drivers Installed
- `adb` from [Android SDK Platform-Tools](https://developer.android.com/tools/releases/platform-tools#downloads)

Phone requirements:
- USB Debugging enabled
- USB Debugging authorized/allowed the Desktop

Steps:
1. Turn off the phone.
2. On the desktop, open terminal/shell/cmd
3. Change directory to the extracted `platform-tools` folder.
4. Enter `adb logcat > logcat.log`
5. Connect the phone to desktop.
6. Turn on the phone, wait till home shows up or stuck screen if it does + another 60 seconds,
7. If you're **able** to open Magisk App, then go to Logs, tap the diskette icon. Get `magisk_log_dateTtime.log` in your internal storage Download folder.
8. Back to desktop, press `CTRL+C`
9. If earlier you're **not able** to open Magisk App, enter `adb shell su -c cat /cache/magisk.log > magisk.log`, otherwise skip this step.
10. Enter `adb shell su -c dmesg > dmesg.log`
11. Enter `adb shell su -c cat /proc/mounts > proc_mounts.log`
12. Restart the phone, wait till power on, and then enter `adb wait-for-device shell su -c cat /proc/last_kmsg > last_kmsg.log`

Attach all the log files here.

**Comment by 43615** [comment]
Tried both of those APKs, no difference in behavior.
Can't use su due to not having root, only have permission to read logcat and proc_mounts.
[proc_mounts.log](https://github.com/topjohnwu/Magisk/files/13403615/proc_mounts.log)
[logcat.log](https://github.com/topjohnwu/Magisk/files/13403616/logcat.log)

**Comment by yujincheng08** [comment]
because of your font module.

**Comment by 43615** [comment]
That's not very helpful. What is that and how can I fix it? If you don't want to help, please tell me to another place where I can ask.
