### ISSUE TITLE
Stuck at Your Device is Booting now

### ISSUE THREAD

**Issue by tkalfaoglu** [topjohnwu/Magisk#756]
I tried it with TWRP Advanced->ADB Sideload.. I got:
***********
MAGISK 17.3 Installer
***********
- Current boot slot: _a
- Mounting /system, /vendor
- Cannot mount /system
- Unmounting partitions
Updater Process ended with ERROR: 1

This is ALP-09 8.0.0.152(C432)

**Comment by Didgeridoohan** [comment]
A few things to note:

- Don't use ADB sideload. In TWRP, click Install and then navigate to the Magisk zip on your device (you'll have to place it there first, of course).
- Please use the latest Canary build when reporting bugs ([as described](https://github.com/topjohnwu/Magisk#bug-reports)). This is purely for future reference, since your issue likely is that you're doing it wrong.
- Please provide the recovery log when reporting bugs (in TWRP, after the error occurs, go to Advanced - Copy Log). This is purely for future reference, since your issue likely is that you're doing it wrong.

You can close this issue now (please do, so it doesn't clutter up the issue tracker).

**Comment by tkalfaoglu** [comment]
Thank you! I just ran the Magisk Uninstaller (which works great).
I then went to the main menu and mounted /system and /vendor, 
and installed the Magisk from its zip file. It went fine.
However, the phone is stuck again at the "your device is booting now".
I will try to get the log now..

**Comment by tkalfaoglu** [comment]
this is the log after uninstalling magisk. I will also provide the log after I re-install magisk..
[recovery.log](https://github.com/topjohnwu/Magisk/files/2547619/recovery.log)

**Comment by tkalfaoglu** [comment]
I will provide the log after installing magisk and before rebooting it as soon as the phone is ready.

**Comment by topjohnwu** [comment]
Try to install Magisk with patching stock boot images. It is very likely the TWRP you are using is faulty.

**Comment by tkalfaoglu** [comment]
Thank you; unfortunately twrp_bla_alp_0.7.img is the only available TWRP for a Mate 10.
I will try to find out how to patch stock boot images..
