### ISSUE TITLE
Magisk will not patch boot.img and no error output. 

### ISSUE THREAD

**Issue by Solace50** [topjohnwu/Magisk#7864]
[procmount.txt](https://github.com/topjohnwu/Magisk/files/14419418/procmount.txt)
[boot.zip](https://github.com/topjohnwu/Magisk/files/14419464/boot.zip)
[magisk_patched-27000_NQwjj.zip](https://github.com/topjohnwu/Magisk/files/14419467/magisk_patched-27000_NQwjj.zip)

Device: Slimbox ATV
Android version: 12
Magisk version name:27001
Magisk version code:27001
I have upload the boot img and final output which does not change as no patch is applied. No error is within Magisk during patching either direct install or file. Recovery.img suffers the same result.

**Comment by osm0sis** [comment]
Your boot.img is already Magisk patched.

**Comment by Solace50** [comment]
The app itself does not show the existing patch would be the proper submission then. It will still show no patch is present/version number.

**Comment by osm0sis** [comment]
Sure, but as you said, your boot and magisk_patched are identical, so maybe you should upload the original untouched boot for completeness.

Looks like A-only legacy SAR, so literally the worst to support.

**Comment by pndwal** [comment]
Looks like SlimBox is custom firmware for Amlogic boxes (from @SlimHouse on XDA) and device is NOT Slimbox even though some boxes are resold with Slimbox firmware pre-installed... Would be good to know actual device... Seems likely it's X96 AIR (Amlogic S905X3 TV box) from Shenzhen Acemax Electronics...

Some SlimBox firmwares have Magisk preloaded so that may be causing issues (I haven't checked files from op here).

Box models launched with Android 9 (legacy SAR), assuming A-only, will likely require Magisk in /recovery partition ramdisk as ramdisk is not supplied in /boot from OEM's... Magisk patching /boot may still work if bootloader happens to support ramdisk in /boot because Magisk always adds basic ramdisk when missing, otherwise patch /recovery...

Do you see Recovery Mode offered in Magisk App on this device? (Are you patching with it deselected for/boot?)

**Comment by Solace50** [comment]
> Sure, but as you said, your boot and magisk_patched are identical, so maybe you should upload the original untouched boot for completeness.
> 
> Looks like A-only legacy SAR, so literally the worst to support.

The boot file was original, same for recovery which was attempted as well. I would think if magisk was present the app would detect the patch?

**Comment by pndwal** [comment]
> The boot file was original, same for recovery which was attempted as well...

Maybe original SlimBox, but I doubt original stock images... Custom images can introduce issues too and trying with stock firmware may just work...

**Comment by osm0sis** [comment]
> The boot file was original, same for recovery which was attempted as well. I would think if magisk was present the app would detect the patch?

It's not the original, because I unpacked it and it contains Magisk.

**Comment by pndwal** [comment]
> > The boot file was original, same for recovery which was attempted as well. I would think if magisk was present the app would detect the patch?
> 
> It's not the original, because I unpacked it and it contains Magisk.

Yup, not original stock, but seems sellers are supplying boxes with SlimBox ROMs as I mentioned above, and @ SlimHouse has included Magisk with many builds.

**Comment by Solace50** [comment]
> > The boot file was original, same for recovery which was attempted as well. I would think if magisk was present the app would detect the patch?
> 
> It's not the original, because I unpacked it and it contains Magisk. Anyway, some devices with your setup just won't work since the device just refuses to use the added ramdisk.

Well root does exist however Magisk appears to not acknowledge it nor does the other (Fox) manager for adding plugins. Will try the magisk -c to see what is returned. If it is simply a ramdisk issue perhaps I can apply a fix myself. It is also a correct assumption the ROM is not stock. Oddly I've never had such an issue with other devices. 

I believe I did have 2600xx installed as well but nothing changed. I tried earlier versions to see if it simply was a build issue considering (I thought) the patch was not being applied. 

Is it possible to provide what with the ramdisk is missing? I likely could check/add what is needed if anyone had a theory. Coming up with that myself would take a lot more reading into the specifics of how Magisks functions, which I will likely do when I have some free time if no one has the insight.

**Comment by pndwal** [comment]
You think you have root?... Please say magisk -c and magisk -v output...

If it's an A-only device launched with Android 9 bootloader may simply not be able to support ramdisk in /boot... There will certainly be proper ramdisk installed if Magisk-patched however since Magisk has manually added that if missing (for devices like A-only Android 9 LV Xiaomi devices where bootloader inexplicably supports ramdisk in /boot), but unless bootloader is compatible the only option for Magisk in these devices is magiskinit injection in ramdisk in /recovery and booting to system with Magisk via Recovery key combo with attention to key release timing... So really that's a bootloader issue rather than a ramdisk one.

Unless it's A-only legacy SAR (I didn't believe there's any other than A9 LV devices), there will necessarily be bootloader support for ramdisk in /boot.

Don't forget 27000+ also has unresolved issues/regressions with recent refactoring and other changes (incl. root not found) although it works fine (it seems) on many devices...

**Comment by canyie** [comment]
>  root does exist

Do you mean `su` or `magisk` executable file the is accessible from adb shell? Can you gain root access by executing `su`?

**Comment by Solace50** [comment]
su is accessible from shell, magisk is not (despite the unpack from another shows it exists). su does elevate to root however magisk -v etc... does not exist.

**Comment by canyie** [comment]
Then your su file is not provided by magisk i think. It looks magisk does not take any effect. Try patching recovery.img and `adb reboot recovery` instead, since the device appears to be A-only legacy SAR and does not accept boot ramdisk I guess?

**Comment by pndwal** [comment]
Also, if you are able to locate stock firmware for this box, the OEM boot.img would likely give clues.

**Comment by Solace50** [comment]
:/data/data # magisk -v
17 me.phh.superuser cm-su subind suinit

I did patch recovery.img and reboot to recovery. I suppose the error makes more sense given the magisk -v output
After installing magisk into recovery the binary exists however I believe it is reporting a legacy version of v17? Still not detectable by other apps, should there be another user/binary present that apps check for?

**Comment by canyie** [comment]
Your recovery image already contains phh-superuser patches which are incompatible with magisk. Maybe a phh ROM is also installed on the device. I suggest you to reflash the stock firmware.

**Comment by mecdielhatib** [comment]
![Screenshot_20241228_170300](https://github.com/user-attachments/assets/0eeb1c1d-46d6-4397-8d48-ab46b26a13d5)
When I installed the additional settings magisk and restarted the device stopped at the company logo. What is the cause of the problem?
