### ISSUE TITLE
Broken stub 

### ISSUE THREAD

**Issue by RV7PR** [topjohnwu/Magisk#7967]
Device: Samsung Galaxy S23 Plus (SM-S916B)
Android version: 14
Magisk version name: 
Magisk version code: 27002

I'm on 27001 and I tried updating to 27002 but that didn't work using the app so I uninstalled magisk to try and install it manually but it always replaces it with the stub but now the stub can't install too because it's stuck at downloading
So how can I install magisk again?

https://github.com/topjohnwu/Magisk/assets/17615589/f7f76a8e-28ff-461f-9f72-6d7dacbba27b

**Comment by vvb2060** [comment]
I don't recommend using the ci version due to signature verification, please wait for the canary release.

**Comment by RV7PR** [comment]
@vvb2060 I already tried using [https://github.com/topjohnwu/magisk-files/blob/master/canary.json](url)
But it keeps replacing it with stub.
Or do you mean that with a new release this wont be an issue?

**Comment by vvb2060** [comment]
It looks like you are using the ci version, that's why we don't recommend it. Please uninstall magisk and then reinstall.

**Comment by RV7PR** [comment]
@vvb2060 can you clarify what you mean with uninstall and reinstall because thats the exact thing I can't do right now

**Comment by RV7PR** [comment]
@topjohnwu @yujincheng08 maybe you can help me with this issue. I would appreciate it🙏🏼

**Comment by pndwal** [comment]
Uninstalling _Magisk_ means restoring images you Magisk-patched to stock... Should be init_boot.img in your case... Uninstalling Magisk App does not uninstall Magisk, but residual stub apps can be removed from device settings, Apps.

Nb. The Magisk daemon performs the signature and version checks, so you will have issues moving from Canary or public to CI builds or vice versa, as well as downgrading unless you remove core Magisk (or install a debug build which bypasses these checks).

**Comment by RV7PR** [comment]
@pndwal Is it possible to patch init_boot.img from another android device and use that to reinstall magisk as debug build or do you always have to patch on the same device you're using it for?
Thx for helping out btw!

**Comment by pndwal** [comment]
You shouldn't do that especially since 26.0... Refactoring determination of sepolicy/module rule folder meaning patching must be done on the booted device... All devices, even the same, may select a different directory... If you must patch on another device, use 25.x etc... should work if it's another device with same boot type, in your case late 2SI... Not sure what other issues there may be though.

Why not just uninstall Magisk (ie. flash the stock boot image that contains generic ramdisk, ie. init_boot.img for S23) as suggested, remove any residual stub apps (locate in system settings, apps), then install whatever Magisk app you want and patch boot image on the device, problem solved???

Anyway, debug build will bypass version and signing checks to move back to official or older builds if you really don't want to remove Magisk. (Install Debug App, take Direct Install to install Debug Magisk, then install whatever releases build App you want and take Direct Install again... Voila!) ... Either way will prevent forced removal of the app after signature or version verification by Magisk daemon (and daemon trying to install App data matching current version/signature in stub that you seem to be fighting with) however. (Of course, uninstalling Magisk removes the daemon.)...

**Comment by RV7PR** [comment]
@pndwal 

> You shouldn't do that especially since 26.0... Refactoring determination of sepolicy/module rule folder means patching must now be done on the booted device... All devices, even the same, may select a different directory... If you must patch on another device, use 25.x stable/beta or earlier, then update by Direct Install... Should work if it's another device with same boot type, in your case late 2SI... Not sure what other issues there may be though.

Not going to try that then😅


> Why not just uninstall Magisk (ie. flash the stock boot image that contains generic ramdisk, ie. init_boot.img for S23) as suggested, remove any residual stub apps (locate in system settings, apps), then install whatever Magisk app you want and patch boot image on the device, problem solved???

I would like to try this but i dont know how to do that with ODIN and also I'm not sure if I just can flash stock boot image without some boot protection mechanism comes active and prevents me from booting and I have to fully reflash stock image and then my data will be gone. So can this be done without loss of my data?


> Anyway, debug build will bypass version and signing checks to move back to official or older builds if you really don't want to remove Magisk. (Install Debug App, take Direct Install to install Debug Magisk, then install whatever releases build App you want and take Direct Install again... Voila!) ... Either way will prevent forced removal of the app after signature or version verification by Magisk daemon (and daemon trying to install App data matching current version/signature in stub that you seem to be fighting with) however. (Of course, uninstalling Magisk removes the daemon.)...

I understand but this is not an option because the magisk app keeps being replaced with stub

**Comment by pndwal** [comment]
> I would like to try this but i dont know how to do that with ODIN and also I'm not sure if I just can flash stock boot image without some boot protection mechanism comes active and prevents me from booting and I have to fully reflash stock image and then my data will be gone. So can this be done without loss of my data?

Ah yes...  According to official instructions you should never do that on Sammy devices... @vvb2060 may have forgotten that yours is Samsung... 😜 (FWIW, just means flashing all stock binaries with Odin with home_csc to keep data) So only do that with a full data wipe I guess...

> I understand but this is not an option because the magisk app keeps being replaced with stub

Why 'not an option '??

Try it... Like I said, Debug builds bypass/disable signature and version checking (so app removal shouldn't occur).

**Comment by RV7PR** [comment]
So I fixed it, luckily I still had all odin binaries saved on my laptop from my last update, including the magisk patched AP file with debug build, so I reflashed it so now I could finally install any magisk apk without being replaced🙏🏼

**Comment by pndwal** [comment]
You could have installed the Debug App without issues even with CI Magisk/daemon still installed also (no need to use Odin at all; just Direct Install)...

You just didn't try.

**Comment by RV7PR** [comment]
Problem was I didn't have the debug build installed, it was canary, that was the whole issue, there was no way of installing magisk without the use of the stub but since that also didnt work I was stuck, I already tried every possible magisk build but it just keeps replacing it with stub

**Comment by pndwal** [comment]
I know that... Did you really try installing official Debug App?... Was that forcibly uninstalled too?...

**Comment by RV7PR** [comment]
So what I did was first install latest ci build and probably used the release apk so after direct install and reboot I switched to canary and then again direct install and reboot.

Yes I tried latest ci builds and official apk links, everything got replaced

**Comment by pndwal** [comment]
I think I'm understanding what occurred now...

So you switched channel in CI App to Canary, next took Install, Direct install for Magisk itself?... So you hadn't first taken Install for App (to get Canary app/binary package installed)??... If not **you would still have been installing CI Magisk core/mask** since Update channel (JSON) no longer calls Magisk binaries online, only the all-in-one package... Update channel from 22.0 only affects which _app/package_ is installed and Magisk core/mask installation is done entirely offline.

Since (it seems) you still had CI Magisk (different signing), daemon would have forcibly removed removed Stable/Beta/Canary App builds, but the CI App would still have installed... I thought official Debug App should install too but I maybe won't from CI... You could have installed CI debug build App/package however, then taken Install Magisk, Direct install (to get debug Magisk w/ bypass for signature & version checks), put channel to **any** Stable/Beta/Canary build, taken App Install (to load package for Magisk installation), then taken Direct install to get back to Stable/Beta/Canary Magisk. 🙃

**Comment by RV7PR** [comment]
Like I said, ci builds also didn't work , didn't matter what I tried (stable, beta, canary, ci and for everyone I tried the release and debug apk) 🤷🏼‍♂️
