### ISSUE TITLE
Unable to root Pixel 7 after updating to Android 14.0.0 (AP2A.240805.005, Aug 2024)

### ISSUE THREAD

**Issue by joshotws** [topjohnwu/Magisk#8313]
Device: Google Pixel 7
Android version: 14.0.0 (AP2A.240805.005, Aug 2024)
Magisk version name: Debug
Magisk version code: 27006

I am trying to report a bug after updating my Pixel 7 to the latest Android version 14.0.0 (AP2A.240805.005, Aug 2024). After installing Magisk version 27.0 and patching the boot image, I flashed it to init_boot but I am still unable to achieve root access. 

I have attached the debug logs and the init_boot.img file that I flashed. Could you please help me identify the issue? 
Thank you in advance.

[magisk_log_2024-08-16T23.39.04.log](https://github.com/user-attachments/files/16638971/magisk_log_2024-08-16T23.39.04.log)
[magisk_patched-27006_26il4.zip](https://github.com/user-attachments/files/16638974/magisk_patched-27006_26il4.zip)
[init_boot.zip](https://github.com/user-attachments/files/16638978/init_boot.zip)

**Comment by yujincheng08** [comment]
But I can see `/system/bin/magisk` in your system. There should be root access.

**Comment by joshotws** [comment]
But it showed up like that. And when I opened the root checker app, it
didn't work.

LoveSy ***@***.***> 於 2024年8月18日 週日 12:28 寫道：

**Comment by joshotws** [comment]
Sorry, I forgot to attach the file in my previous email reply. I have now attached the file.

![Screenshot_20240818-124805](https://github.com/user-attachments/assets/e7312bce-0676-4399-a3ef-d459ce4aa0ee)
![Screenshot_20240818-125329](https://github.com/user-attachments/assets/9732a4e0-9b1b-48a5-bf97-526b5f3c0c74)

**Comment by joshotws** [comment]
I performed  "wipe all" again to clear all the data, and now it's working normally. Thank you for your assistance.

**Comment by StressFreeNetwareRepos** [comment]
Use calyxos is what I would recommend (Because they're completely non proprietary and have working micro G services out of the box, and they respect ur freedom and privacy) to do the same and also make sure that when you flash init boot you are flashing it to the init_boot slot and not the boot slot. I am also currently on a pixel 7 and have done this up to Android 15 through 13 and with a pixel 6 and 7 and Also make sure that you are not using SDK platform tools version 34.0.1 because fastboot is broken in that SDK. 

fastboot flash init_boot init_boot.img(magisk patched)

I have seen mentions of a --slot all being added to the above command I have never had to, and If my understanding of how A and B devices actually work is correct, the flag is unnecessary.

Also if ur having trouble getting into fastbootd to do the flash (not sure if ur dirty flashing or what exactly but attempting to cover many bases for ya

adb reboot-bootloader ; fastboot reboot fastboot



Also make sure you have disabled verity and verification.
