### ISSUE TITLE
zygisk on android 15

### ISSUE THREAD

**Issue by User10987654321** [topjohnwu/Magisk#8616]
Device: pixel 7
Android version: 15
Magisk version name:28101
Magisk version code: 28101
zygisk appears to not work on android 15, no matter what the magisk version or the presence of the ReZygisk module
no lsposed error appears in any circumstance

no matter the combination of modules or magisk versions, the result is always:

magisk root installed: yes
zygisk: no
ramdisk: yes

no errors at all, just failure to work as intended without any error message

**Comment by User10987654321** [comment]
https://github.com/mywalkb/LSPosed_mod/releases/download/v1.9.3_mod/LSPosed-v1.9.3_mod-7244-zygisk-release.zip also makes no difference, just results in zygisk not activating with no error message to be found.

magisk is an unsupported project - any dependencies it may have that "aren't working" is ultimately just the failure of magisk.
any maintainer that claims they have a working build with zygisk on latest android (15) is lying because zygisk does not work on android 15

**Comment by User10987654321** [comment]
After like 10 minutes with above LSPosed_mod addon, i get a notification saying "lsposed loaded: Tap the notification to open manager" but when tapped, it closes the notifications dropdown and opens nothing.

**Comment by Gamiac69** [comment]
I was in the exact same situation as you
Device: Pixel7 (GrapheneOS)
Android version: 15
Magisk version name:28103 (D)
Magisk version code: 28103 (D)

Magisk Root: yes
zygisk: no
ramdisk: yes

[magisk_log_2025-03-30T17.28.21.log (Before ReZygisk)](https://github.com/user-attachments/files/19526510/magisk_log_2025-03-30T17.28.21.log)

It would be nice for this to be fixed without having to install something like ReZygisk. ReZygisk isn't stable and ZygiskNext isn't truly open source. When I tried, installing ReZygisk with Zygisk not enabled in Magisk settings it still shows I don't have Zygisk on the manager, but ReZygisk seems to show it is, I'm not really sure.

Also seems like GrapheneOS in particular has a lot of problems with Zygisk. For example, I have LineageOS on my A52s running Zygisk on android 15 with no problems - I didn't need ReZygisk.

I'm not too familiar with how reporting issues works on GitHub but would it be good to maybe keep the issue open so that we don't need supplements to fix problems?

[magisk_log_2025-03-30T17.51.24.log (After ReZygisk)](https://github.com/user-attachments/files/19526589/magisk_log_2025-03-30T17.51.24.log)
