### ISSUE TITLE
Unable to charge device when turned off

### ISSUE THREAD

**Issue by topjohnwu** [topjohnwu/Magisk#906]
This is an issue that cannot be fixed on my side. Patching the kernel to force load ramdisk alone is enough to trigger this bug on several devices.

**Comment by ebiel** [comment]
Even though I haven't tried it myself it seems to have worked in Oxygen OS Beta 7 (OB7) but is not working in OB8 and the latest beta OB9 (source: https://forum.xda-developers.com/showpost.php?p=78470912&postcount=43).
@topjohnwu if you could provide more information I'd very much like to make a report in the OnePlus Support Forum.

**Comment by bdashore3** [comment]
@ebiel, the same thing happened with me on the 1st gen pixel. It works on the November update, but the December update just screwed up the charging animation. Perhaps the January update may fix the issue.

**Comment by ebiel** [comment]
Just an update for the OP6 regarding the behavior:
- this was fixed with Oxygen OS Open Beta 10 and Oxygen OS 9.0.3
- charging always worked when the OP6 was powered off. It was just that the charging animation didn't show up; instead the bootloader unlocked message was shown indefinitely after plugging in the USB cable connected to a charger.

**Comment by Darkcast** [comment]
Is there no way to fix it this issue can lead to screen burn

**Comment by topjohnwu** [comment]
@Darkcast just turn the device on! What's wrong with that?

**Comment by bailey-01** [comment]
Browsing around some of the Android docs for unrelated reasons, I found [this](https://source.android.com/devices/bootloader/unlock-trusty#off-mode-charging) section, describing a fastboot command that should provide a partial workaround, assuming the manufacturer or whoever responsible has done whatever is needed to support it and your device supports fastboot commands in the first place.

I've tried this on my Pixel 1, with the only side effect being that the "your device can't be checked for corruption" screen sticks around for a few seconds longer than usual if it powers up via cable as opposed to the button. 

I haven't yet tested what happens if the device goes flat (0%) and is then plugged in. If you can help it, you may want to turn your phone off before Android does it for you in a low-battery state.
As you've read 1000s of times already: you proceed at your own risk, and agree not to hold anyone but you and only you responsible if your phone does Weird Shit as a result of doing this.

The steps:
- Enter the bootloader, plug a USB cable in.
- On the connected machine, `fastboot oem off-mode-charge 0`.
- Boot into Android.
- Test by disconnecting the cable, powering the phone off normally using the power button menu, then plugging it into any power source and observing the result.

The end result should be a phone that powers up to Android and bypasses any charging mode or screen as soon as it receives external power. This should then allow the system to boot without hanging on the charge screen, thus allowing OS power management functionality to start working and thus to turn off the display according to the system's activity timer/display timeout settings.

To reverse this, enter the bootloader and run `fastboot oem off-mode-charge 1`.

**Comment by osm0sis** [comment]
Worth noting off-mode-charge didn't work on OP6 or OP6T when I tried - it still would get stuck at the unlocked notice.

On the upside, the latest Magisk Canary builds seem to have resolved this issue somehow at least from what I have seen on my OnePlus devices.
