### ISSUE TITLE
mi 8 se  will boot loop when version is higher than 16.6

### ISSUE THREAD

**Issue by kissunyeason** [topjohnwu/Magisk#926]
这个问题有可能会修复吗？
在rec刷入没有任何错误提示，但是开机时会卡在“mi”，然后无限重启。需要我提供什么文件或者日志吗？

Is it possible to fix this bug?
 There will be no error prompt when rec flash in, but when booting up, it will be stuck in the "mi" and boot loop. what files or logs do I need to provide?

**Comment by xiaowyyyyya** [comment]
Same issue here!
Magisk won't boot on Mi8se since a few months ago, all version above 16.6 won't boot. I am on the latest firmware for sure. And unfortunately adb logcat does not work because the boot admination won't even show up. But the good news is that I have the ramoops files and a few logs from recovery, I hope that will help. If you need any additional information, please leave a comment. Hopefully there is gonna be a fix coming soon))) https://drive.google.com/drive/folders/1F_LGXoYs9mrMBX1aCZXvgJQAGpzATTc3?usp=sharing
Thank you! Really appreciate your hard work!

**Comment by topjohnwu** [comment]
Please check #980
