### ISSUE TITLE
Sometimes the safetynet will become false

### ISSUE THREAD

**Issue by yuningning520** [topjohnwu/Magisk#944]
[magisk_log_20190102_102650.log](https://github.com/topjohnwu/Magisk/files/2719809/magisk_log_20190102_102650.log)
mipad1 los15.1 rom
but in magisk 17.3 did not appear

**Comment by papjul** [comment]
Hi, I believe (like many others) that I have the same issue. Please let me know otherwise if you want me to open another issue.

- SafetyNet request is success but fails on both checks (red mark) after few minutes to hours
- It is a regression introduced between 17.3 and 18.0. Latest Canary still affected (1df65940b9e3a63eaaa1a87df3b24210677fe1af currently)

I have a log from latest Canary debug channel so it may be more useful:
[magisk_log_20190102_134915.log](https://github.com/topjohnwu/Magisk/files/2720795/magisk_log_20190102_134915.log)

SafetyNet was tested from Magisk Manager regularly (you can see that I was playing Pokemon Go), and failed at 13:41:00 when I checked SafetyNet from Magisk Manager. At 13:42:00, I requested su access from file manager, so I was a bit surprised to not find any log regarding the SafetyNet request at 13:41 but this is maybe intended to not be logged?

**Comment by Didgeridoohan** [comment]
https://github.com/topjohnwu/Magisk/issues/907
